OEL-446: OE Showcase scaffolding
openeuropa/oe_showcase pull request #1
Opened 2021-08-25 10:20 UTC by abel-santos-corral

We need to create the scaffolding for oe_showcase. Add base elements

2021-08-26 07:19 UTC, drishu requested changes

2021-08-26 07:19 UTC, drishu commented on README.md
> +Opting for a minimalistic installation profile will make it easier to deal with a fully distributed approach: the
The rationale is different here, the showcase is for showcasing the openeuropa library features, so that developers have examples as guid to how to build these features. Try to word that idea better though.

2021-08-26 07:19 UTC, drishu commented on README.md
> +[1]: https://www.drupal.org/project/bartik
remove this line, no need to put emphasis on it as we will change it to oe_whitelabel in near future

2021-08-26 07:19 UTC, drishu commented on README.md
> +2. Setup `seven` as administrative theme and [`bartik`][1] as front-end theme.
```suggestion
2. Setup `seven` as administrative theme.
```

we will change bartik in near future so lets not mention it

2021-08-26 07:19 UTC, drishu commented on .drone.yml
> +  sparql:
this isn't used at the moment, lets remove it

2021-08-26 07:19 UTC, drishu commented on docker-compose.yml
> +  sparql:
this isn't used at the moment, lets remove it

2021-08-26 07:19 UTC, drishu commented on runner.yml.dist
> +    databases:
this isn't used at the moment, lets remove it

2021-08-26 07:19 UTC, drishu commented on docker-compose.yml
> +      # XDEBUG_CONFIG: "client_host=172.17.0.1" # Non-Mac users.
uncomment this

2021-08-26 07:19 UTC, drishu commented on docker-compose.yml
> +      XDEBUG_CONFIG: "client_host=172.17.0.1 client_port=9000  remote_host=172.17.0.1 remote_port=9000 remote_enable=1, idekey=VSCODE"
dont add this, if you need it, add a docker-compose.override.yml (into your local install, not in the codebase)

2021-08-26 07:19 UTC, drishu commented on docker-compose.yml
> +      # XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9000 remote_enable=1, idekey=VSCODE
```suggestion
      # XDEBUG_CONFIG: "client_host=host.docker.internal" # Mac users.
```

2021-08-26 07:19 UTC, drishu commented on docker-compose.yml
> +      XDEBUG_SESSION: "VSCODE"
```suggestion
      # XDEBUG_SESSION: 1
```
again, add your own config in override

2021-08-26 07:19 UTC, drishu commented on phpunit.xml.dist
> +    <env name="SIMPLETEST_SPARQL_DB" value="sparql://${drupal.sparql.host}:${drupal.sparql.port}/?module=sparql_entity_storage"/>
remove this for now

2021-08-26 07:19 UTC, drishu commented on phpunit.xml.dist
> +    <testsuite>
add name property to testsuite

2021-08-26 07:19 UTC, drishu commented on runner.yml.dist
> +  sparql:
remove for now

2021-08-26 07:19 UTC, drishu commented on runner.yml.dist
> +  sparql:purge:
remove all this sparql stuff till needed

2021-08-26 08:10 UTC, abel-santos-corral commented
Some extra changes were added:

- Removing minimal from profile variable at runner component
- Removed all stuff from components regarding the selenium part. It was not present in the oe_profile model we had. We brought it from another example (oe_authentication).
- Added two more instructions on runner to add the un-aggregation of CSS and JS. At testing we saw that content page was not properly shown. We tried to add 777 permissions to files folder, but that alone didn't work.

2021-08-26 13:26 UTC, drishu submitted a review, later dismissed

2021-09-02 11:11 UTC, GilNovacomm approved these changes
Review ok.

2021-09-02 11:12 UTC, Maxfire approved these changes
Changes reviewed, looks good, thanks

2021-09-02 11:13 UTC, drishu approved these changes

2021-09-02 11:13 UTC, merged