OEL-1421: Fix cosmetic changes on project
openeuropa/oe_showcase pull request #105
Opened 2022-04-08 14:05 UTC by Maxfire

Cosmetic changes and tests provided.

2022-04-11 10:54 UTC, abel-santos-corral requested changes

2022-04-11 10:54 UTC, abel-santos-corral commented on config/install/field.field.node.oe_project.oe_cx_impacts.yml
> +      - rich_text
Please, check if tests for this change can be done. See the model of SearchTextTest.php file at oe_whitelabel_paragraphs submodile at OE Whitelabel. E.g.     $text = $crawler->filter('p#paragraph-2 strong');

2022-04-11 12:25 UTC, abel-santos-corral submitted a review, later dismissed

2022-04-12 13:55 UTC, drishu requested changes

2022-04-12 13:55 UTC, drishu commented on tests/src/ExistingSite/ProjectTest.php
> +    // Create a node, without project details.
rather where a project is first created and we fill in the project details (starting line 73), **don't**, assert what you wanted from the project detaild group and then, edit the node, add the values, and assert that the values and group are now there

2022-04-12 13:55 UTC, drishu commented on tests/src/ExistingSite/ProjectTest.php
> +    $page->fillField('oe_project_participants[form][0][name][0][value]', 'Developer participant name');
add contribution

2022-04-12 13:55 UTC, drishu commented on tests/src/ExistingSite/ProjectTest.php
> +    $page->fillField('oe_cx_lead_contributors[form][0][name][0][value]', 'Lead contributors name');
add contribution

2022-04-12 13:55 UTC, drishu commented on tests/src/ExistingSite/ProjectTest.php
> +    $correct_order = [
either check the order of everything or dont check order

2022-04-12 13:55 UTC, drishu commented on tests/src/ExistingSite/ProjectTest.php
> +  protected function createView(): void {
remove this

2022-04-12 13:55 UTC, drishu commented on tests/src/ExistingSite/ProjectTest.php
> +    $this->markEntityTypeForCleanup('view');
remove this

2022-04-12 13:55 UTC, drishu commented on tests/src/ExistingSite/ProjectTest.php
> +    $this->drupalGet('/project-listing-page');
just use /node

2022-04-12 15:33 UTC, Maxfire commented on tests/src/ExistingSite/ProjectTest.php
> +    $page->fillField('oe_cx_lead_contributors[form][0][name][0][value]', 'Lead contributors name');
no need cause I'm going to use the previous one which have contribution.

2022-04-12 15:33 UTC, Maxfire commented on tests/src/ExistingSite/ProjectTest.php
> +    $page->fillField('oe_project_participants[form][0][name][0][value]', 'Developer participant name');
no need cause I'm going to use the previous one which have contribution.

2022-04-13 07:24 UTC, drishu requested changes

2022-04-13 07:24 UTC, drishu commented on tests/src/ExistingSite/ProjectTest.php
> +      $assert_session->elementContains('xpath', "(//ul[contains(@class, 'nav-pills')]//li[contains(@class, 'nav-item')])[" . $key . "]", $value);
can't we use li.nav-item:nth-child as selector, then getText and compare ? would be clearer

2022-04-13 07:24 UTC, drishu commented on tests/src/ExistingSite/ProjectTest.php
> +    // Check the correct order.
Rather say your asserting the in-page nav, and if you do this here do this also above, when you have all items present, so we can see that it changed

2022-04-13 07:24 UTC, drishu commented on tests/src/ExistingSite/ProjectTest.php
> +    dump($page->getHtml());
left over, remove

2022-04-13 07:24 UTC, drishu commented on tests/src/ExistingSite/ProjectTest.php
> +    // Node doesn't contain any period, therefore no empty span.
I dont understand what we are asserting here

2022-04-13 07:24 UTC, drishu commented on tests/src/ExistingSite/ProjectTest.php
> +    $assert_session->elementNotExists('css', '.card-body:nth-child(1) .text-muted');
we check that no meta is present, can we check somewhere also a case where it is

2022-04-13 07:24 UTC, drishu commented on tests/src/ExistingSite/ProjectTest.php
> +
I see a lot of "Improve the field locator." could you do me a favour, remove them all and add just one todo in the function comment explaining that we want to use labels not machine names in the future

2022-04-13 07:27 UTC, Maxfire commented on tests/src/ExistingSite/ProjectTest.php
> +    $assert_session->elementNotExists('css', '.card-body:nth-child(1) .text-muted');
we are, just a bit up.

2022-04-13 09:09 UTC, drishu approved these changes, later dismissed

2022-04-13 09:38 UTC, abel-santos-corral submitted a review, later dismissed

2022-04-13 09:56 UTC, abel-santos-corral approved these changes

2022-04-13 09:56 UTC, drishu approved these changes

2022-04-13 09:57 UTC, merged