OEL-1247: Integration listing page.
openeuropa/oe_showcase pull request #109
Opened 2022-04-18 07:13 UTC by Maxfire

Integration listing page on showcase.

2022-04-19 15:43 UTC, donquixote commented
The sad thing: We now need a (post?) update hook.
If all the config goes to a new submodule (oe_showcase_list_pages), we only need an update hook that enables the new submodule from oe_showcase.install.
The goal is that in a project like OESA the configuration will be applied automatically via install-clone.

(Personally I don't like that we have to do this, but this is now the way of things).

2022-04-19 16:07 UTC, donquixote commented
This makes me wonder:
Are the facets and search index specific to list pages, or would we use the same index for regular search?
If the facets are specific to list pages, can and should we prefix their names?

2022-04-19 19:14 UTC, donquixote commented on tests/src/ExistingSite/ListPagesTest.php
> +    $day = 00;
```suggestion
    $day = 0;
```

2022-04-19 19:23 UTC, donquixote commented on tests/src/ExistingSite/ListPagesTest.php
> +          'value' => '2022-04-' . $day++,
Now I see what you are trying to achieve with the `00` above :) but it won't work as you expect.
https://3v4l.org/uSOmV
https://stackoverflow.com/a/1699980/246724
https://3v4l.org/2lRtG

```suggestion
          'value' => sprintf('2022-04-%02d', $i + 1),
```

2022-04-19 19:24 UTC, donquixote commented on tests/src/ExistingSite/ListPagesTest.php
> +    $day = 00;
Actually we can drop the `$day` variable, see below.

2022-04-19 19:26 UTC, donquixote commented on tests/src/ExistingSite/ListPagesTest.php
> +      $date = new DrupalDateTime('20-10-2020');
Why use d-m-Y here, but Y-m-d below? 
Imo, for code, we should always use Y-m-d, it is the least ambiguous format.
```suggestion
      $date = new DrupalDateTime('2020-10-20');
```

2022-04-19 19:31 UTC, donquixote commented on tests/src/ExistingSite/ListPagesTest.php
> +    $role->setIsAdmin(TRUE);
Do we need to be admin? Is there currently no other role that can add list pages?
Perhaps there should be, so that people can test it without being admin.

2022-04-19 19:40 UTC, donquixote commented on tests/src/ExistingSite/ListPagesTest.php
> +      $date = new DrupalDateTime('20-10-2020');
Btw why do we need to set a created timestamp?

2022-04-19 19:51 UTC, donquixote commented on tests/src/ExistingSite/ListPagesTest.php
> +        ],
Will it work if we pass the value directly without an array level?
(I don't know, try it)
```suggestion
        'oe_publication_date' => sprintf('2022-04-%02d', $i + 1),
```

2022-04-19 20:05 UTC, donquixote commented on tests/src/ExistingSite/ListPagesTest.php
> +  }
The entire test seems to be mostly a copy of the ListPagesTest in oe_whitelabel.
With some modifications for the new facet.
It feels wrong to me, especially with all the detailed assertions about html classes and attributes.
We mostly want to verify that the facets and the search results show up, and that blocks are not placed in the wrong region. We don't need to test every visual detail.
Also I already don't like the test in whitelabel very much tbh - but this is merged.

A nice example for a search page test is here, https://github.com/openeuropa/oe_showcase/pull/87/files
However, I don't know how far we want to go for something that is already tested in whitelabel.
The copy + paste is definitely a "cheap" solution, and does the job. It can be ok if we plan to refactor it later.

2022-04-19 20:07 UTC, donquixote commented on tests/src/ExistingSite/ListPagesTest.php
> +  }
We could even have a ListPageAssertion, like we do for patterns :) but that's a wild idea, let's not do it now.

2022-04-19 20:09 UTC, donquixote commented on tests/src/ExistingSite/ListPagesTest.php
> +    $assert_session->elementExists('css', 'div.row > div.col-12.col-lg-9.col-xxl-8');
I don't like the selector, and I don't think we need to verify that a "right column" exists.
I know this is copied from the whitelabel test, but still..

2022-04-19 20:17 UTC, donquixote commented
Btw, I notice that the filter icon does not work, but this will be fixed in next version of BCL.

2022-04-20 08:57 UTC, Maxfire commented on tests/src/ExistingSite/ListPagesTest.php
> +    $role->setIsAdmin(TRUE);
There's no other role to allow that, nothing specified in the requirements, so we keep it as is.

2022-04-20 17:36 UTC, GilNovacomm submitted a review, later dismissed

2022-04-21 10:11 UTC, donquixote commented on modules/oe_showcase_list_pages/tests/src/ExistingSite/ListPagesTest.php
> +use Drupal\user\Entity\Role;
Please reorder the imports and remove blank line. PhpStorm: Ctrl+Alt+O.
Also please add a namespace declaration.
```suggestion
namespace Drupal\Tests\oe_showcase_list_pages\ExistingSite;

use Behat\Mink\Element\NodeElement;
use Drupal\node\Entity\Node;
use Drupal\node\NodeInterface;
use Drupal\Tests\oe_showcase\ExistingSite\ShowcaseExistingSiteTestBase;
use Drupal\Tests\search_api\Functional\ExampleContentTrait;
use Drupal\user\Entity\Role;
```

2022-04-21 10:16 UTC, donquixote commented on modules/oe_showcase_list_pages/tests/src/ExistingSite/ListPagesTest.php
> +    $search_form = $assert_session->elementExists('css', '#oe-list-pages-facets-form');
Can we call this `$filter_form` instead?

2022-04-21 10:17 UTC, donquixote commented on modules/oe_showcase_list_pages/tests/src/ExistingSite/ListPagesTest.php
> +    // Use the site-wide search for filter news created after 4th april 2022.
I don't think we are using the site-wide search here.
We are using the filter widgets on the list page.
"Site-wide search" would refer to the global search element in the page header.

2022-04-21 10:17 UTC, donquixote commented on modules/oe_showcase_list_pages/tests/src/ExistingSite/ListPagesTest.php
> +    // Use the site-wide search for filter news with specific title.
Same here, this is not the site-wide search.

2022-04-21 10:18 UTC, donquixote commented on modules/oe_showcase_list_pages/tests/src/ExistingSite/ListPagesTest.php
> +    // Use the site-wide search for filter news with specific title.
```suggestion
    // Filter results by title.
```

2022-04-21 10:19 UTC, donquixote commented on modules/oe_showcase_list_pages/tests/src/ExistingSite/ListPagesTest.php
> +    // Use the site-wide search for filter news created after 4th april 2022.
```suggestion
    // Filter results by date.
```

2022-04-21 10:19 UTC, donquixote commented on modules/oe_showcase_list_pages/tests/src/ExistingSite/ListPagesTest.php
> +    ]);
Let's insert a blank line here.
```suggestion
    ]);

```

2022-04-21 10:26 UTC, donquixote commented on modules/oe_showcase_list_pages/tests/src/ExistingSite/ListPagesTest.php
> +  }
The method does not do what the doc comment and the name suggest.
It selects the entire right/main column, not just the top region.
I suggest to drop this method, as it is only used once.

2022-04-21 10:54 UTC, donquixote commented on modules/oe_showcase_list_pages/tests/src/ExistingSite/ListPagesTest.php
> +    $title = $this->getSearchTopRegion()->find('css', 'h4.mb-0');
```suggestion
    $title = $this->assertSession()->find('css', '.col-xxl-8 h4.mb-0');
```
There is no good selector for this unfortunately, so this is the best we can do.
(And this allows to drop the ->getSearchTopRegion() method)

2022-04-21 11:02 UTC, donquixote commented on modules/oe_showcase_list_pages/tests/src/ExistingSite/ListPagesTest.php
> + */
The comment text is weird.
```suggestion
/**
 * Tests list pages.
 */
```

2022-04-21 11:18 UTC, donquixote commented on modules/oe_showcase_list_pages/README.md
> +```
Really?
The `oe_list_pages` module will be already enabled, if this submodule is enabled.
In showcase, it is going to be enabled by default.

2022-04-21 12:38 UTC, donquixote requested changes

2022-04-21 12:38 UTC, donquixote commented on modules/oe_showcase_list_pages/README.md
> +### Create list pages:
No colon (":") after hx elements.

2022-04-21 12:38 UTC, donquixote commented on modules/oe_showcase_list_pages/README.md
> +### Add new bundles you should:
This phrase is weird. Sounds like Yoda talking :)

2022-04-21 12:38 UTC, donquixote commented on modules/oe_showcase_list_pages/README.md
> +* Click on ```List Page``` link to collapse the available configuration.
No triple backticks for inline code snippets.
Also this is not really a code snippet, is it?
Just use regular quotes.
And "expand", not "collapse".
```suggestion
* Expand the "List Page" section in the right panel.
```

2022-04-21 12:38 UTC, donquixote commented on modules/oe_showcase_list_pages/README.md
> +* Select Content on the ```Source entity type```.
This is already the default value.

2022-04-21 12:38 UTC, donquixote commented on modules/oe_showcase_list_pages/README.md
> +* Select the bundle on ```Source bundle```.
Should be "News".

2022-04-21 12:38 UTC, donquixote commented on modules/oe_showcase_list_pages/README.md
> +* Go to ```config/search/search_api```.
```suggestion
* Go to `config/search/search-api`.
```

2022-04-21 12:38 UTC, donquixote commented on modules/oe_showcase_list_pages/config/install/search_api.server.oe_whitelabel_list_page_search_server_test.yml
> +name: oe_whitelabel_list_page_search_server_test
Can we give this a human label?

2022-04-21 12:38 UTC, donquixote commented on modules/oe_showcase_list_pages/config/install/search_api.index.oe_whitelabel_list_page_index_test.yml
> +name: oe_whitelabel_list_page_index_test
Can we give this a human label?

2022-04-21 12:38 UTC, donquixote commented on modules/oe_showcase_list_pages/config/install/search_api.index.oe_whitelabel_list_page_index_test.yml
> +id: oe_whitelabel_list_page_index_test
Why "whitelabel"? and why "_test"?

2022-04-21 12:38 UTC, donquixote commented on modules/oe_showcase_list_pages/README.md
> +* Go to ```config/search/search_api```.
I was going to say most of this stuff should be documented in oe_list_pages, not here. But perhaps it is ok to do it here, following the issue description.

2022-04-21 12:38 UTC, donquixote commented on modules/oe_showcase_list_pages/README.md
> +## Setting up bundles and filters
Title does not really describe what the section is about.

2022-04-21 15:05 UTC, Maxfire commented on modules/oe_showcase_list_pages/README.md
> +* Select the bundle on ```Source bundle```.
depends cause if the user follows the instructions, could be custom.

2022-04-21 15:22 UTC, Maxfire commented on modules/oe_showcase_list_pages/tests/src/ExistingSite/ListPagesTest.php
> +    $title = $this->getSearchTopRegion()->find('css', 'h4.mb-0');
$title = $this->assertSession()->elementExists('css', '.col-xxl-8 h4.mb-0');
:)

2022-04-21 15:49 UTC, donquixote commented on modules/oe_showcase_list_pages/README.md
> +* Select the bundle on ```Source bundle```.
Yeah, sorry. This was my earlier assumption that the readme is for users of showcase. But it is for users who create their own website.

2022-04-21 16:56 UTC, donquixote commented on modules/oe_showcase_list_pages/README.md
> +* Go to `config/search/search_api`.
```suggestion
* Go to `config/search/search-api`.
```

2022-04-21 16:58 UTC, donquixote commented on modules/oe_showcase_list_pages/README.md
> +* Go to add/oe_list_page.
```suggestion
* Go to `node/add/oe_list_page`.
```

2022-04-21 17:03 UTC, donquixote commented on modules/oe_showcase_list_pages/README.md
> +By default enables oe_list_pages, the news bundle as well as the title and publication date filters are available.
You changed this sentence, but it is still weird

2022-04-21 17:06 UTC, donquixote commented on modules/oe_showcase_list_pages/README.md
> +By default enables oe_list_pages, the news bundle as well as the title and publication date filters are available.
We basically have two cases:
- If you are playing with showcase, all you need to do is enable `oe_showcase_list_pages` and create a custom list page for news.
- If you build your own website without showcase, you would enable `oe_list_pages` and `oe_whitelabel_list_pages`, then you would create search index and facets, then you would create your list page, or you would leave this to editors on production.

With the sentence above, I am not sure which case is being addressed here.
(talk to me in chat)

2022-04-21 17:12 UTC, donquixote commented on oe_showcase.post_update.php
> +  \Drupal::service('kernel')->invalidateContainer();
We should only do this if we really need it.
The comment does not really tell me why, I suspect it is copied from somewhere.

2022-04-21 17:14 UTC, donquixote commented on modules/oe_showcase_list_pages/README.md
> +```
Resolved, but I added a new comment.

2022-04-21 17:15 UTC, donquixote commented on modules/oe_showcase_list_pages/README.md
> +* Go to "admin/config/search/facets".
Let's be consistent.
UI labels in quotes, url paths in backticks.
```suggestion
* Go to `admin/config/search/facets`.
```

2022-04-21 17:17 UTC, donquixote commented on modules/oe_showcase_list_pages/README.md
> +* Go to ```config/search/search_api```.
Not fixed. But I created a new comment, so I will resolve this one.

2022-04-21 17:19 UTC, donquixote commented on modules/oe_showcase_list_pages/config/install/search_api.server.oe_list_page_search_server.yml
> +id: oe_list_page_search_server
I don't know if `oe_list_page_` is the best prefix. But I say it is good enough for showcase.
(the module name would be `oe_list_pages_` with -s. But I don't even know if this should be our prefix. So let's accept your choice.).

2022-04-21 17:20 UTC, donquixote commented on modules/oe_showcase_list_pages/README.md
> +## Setting up bundles and filters
Still a bit weird, but let's resolve this one.

2022-04-21 17:21 UTC, donquixote commented on modules/oe_showcase_list_pages/README.md
> +By default enables oe_list_pages, the news bundle as well as the title and publication date filters are available.
If you can think of an easy improvement, go ahead. Otherwise leave it be: I want to change the readme myself anyway. Perhaps in a follow-up issue.

2022-04-21 18:32 UTC, Maxfire commented on modules/oe_showcase_list_pages/README.md
> +By default enables oe_list_pages, the news bundle as well as the title and publication date filters are available.
Improved it a bit

2022-04-21 18:54 UTC, donquixote commented on modules/oe_showcase_list_pages/README.md
> +By default enables oe_list_pages, the news bundle as well as the title and publication date filters are available.
Still weird but let's address this in a follow-up.

2022-04-21 18:55 UTC, donquixote approved these changes

2022-04-22 08:02 UTC, GilNovacomm approved these changes

2022-04-22 08:05 UTC, merged