OEL-1453: Consolidate theme regions
openeuropa/oe_showcase pull request #111
Opened 2022-04-20 10:13 UTC by escuriola

## OPENEUROPA-1453

### Description

Configure oe_whitelabel navigation blocks on oe_showcase

### Change log

- Added:oe_showcase_post_update
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2022-04-20 18:15 UTC, brummbar requested changes
Two minor remarks.

2022-04-20 18:15 UTC, brummbar commented on oe_showcase.post_update.php
> +function oe_showcase_post_update_10001(&$sandbox) {
Let's start from 00001.

2022-04-20 18:15 UTC, brummbar commented on oe_showcase.post_update.php
> +    if ($block->getTheme() === 'oe_whitelabel') {
Is there a specific reason for checking the theme? That block ID is specific to our theme, plus in showcase we can assume the state of the config.

2022-04-21 19:09 UTC, brummbar submitted a review, later dismissed

2022-04-22 10:45 UTC, drishu requested changes
You need to update the region of oe_whitelabel_search_form also in oe_showcase_search

2022-04-22 11:36 UTC, drishu approved these changes

2022-04-22 11:37 UTC, drishu submitted a review, later dismissed

2022-04-22 12:16 UTC, brummbar approved these changes

2022-04-22 12:27 UTC, drishu approved these changes

2022-04-22 12:58 UTC, merged