OEL-1458: Activate block Social share module
openeuropa/oe_showcase pull request #112
Opened 2022-04-22 09:51 UTC by abel-santos-corral

## OPENEUROPA-[OEL-1458](https://citnet.tech.ec.europa.eu/CITnet/jira/browse/OEL-1458)

### Description

Activate module oe_webtools_social_share and place block Social share.

### Change log

- Added: config/optional/block.block.showcase_socialshare.yml
- Changed: oe_showcase.info.yml

2022-04-22 14:46 UTC, drishu requested changes

2022-04-22 14:46 UTC, drishu commented on config/optional/block.block.showcase_socialshare.yml
> +  request_path:
please enable this for all content types

2022-04-22 14:46 UTC, drishu commented on oe_showcase.info.yml
> +  - oe_webtools_social_share
add a post_update hook to enable this module

2022-04-22 14:46 UTC, drishu commented on tests/src/ExistingSite/SmokeTest.php
> +    $assert_session->elementExists('xpath', '//div[@class="container mt-5"]/*//div[@id="block-showcase-socialshare"]');
this line makes the above one redundant, rather:
-grab the parent container, the main page content, use cores cssSelect() or whatever you like and grab the blocks wrapper
-assert the block title is present
-do this with a helper in ShowcaseExistingSiteTestBase
-check for this in all the content type tests: page, news, event
-remove this code from the smoke test

2022-04-26 09:23 UTC, drishu requested changes

2022-04-26 09:23 UTC, drishu commented on tests/src/ExistingSite/SmokeTest.php
> +    $assert_session = $this->assertSession();
revert this change, no need to create a variable just for this

2022-04-26 09:23 UTC, drishu commented on tests/src/ExistingSite/ShowcaseExistingSiteCreateEventTest.php
> +    $assert_session->elementExists('xpath', '//div[@class="container mt-5"]/*//div[contains(., "Share this page") and @id="block-showcase-socialshare"]');
checking for the id doesn't help, either check for the json, or just the title.

And in the end, now you have to change it in 3 places, so better with the helper method

2022-04-26 10:18 UTC, drishu approved these changes

2022-04-26 10:19 UTC, drishu submitted a review, later dismissed

2022-04-26 17:35 UTC, brummbar requested changes
Code is good but we need to override the template and use a `h3.fw-bold` as per Figma:
![image](https://user-images.githubusercontent.com/8488617/165359297-c487a4f4-45a0-4f76-9ab9-6cccde201885.png)

This is what we have:
![image](https://user-images.githubusercontent.com/8488617/165359329-5a5fe215-1fbc-4f23-9705-c3dd20e7d831.png)

2022-04-26 17:37 UTC, brummbar commented
Just the title, the widget cannot and shouldn't be themed.

2022-04-29 16:56 UTC, brummbar requested changes
A very very very small nit.
For the rest the code is good, but it points out that we really need a child theme in our profile.
I'll open the ticket, but this code can move forward now.

2022-04-29 16:56 UTC, brummbar commented on modules/oe_showcase_page/templates/oe-webtools-social-share.html.twig
> + * @see ./modules/contrib/oe_webtools/modules/oe_webtools_social_share/templates/oe_webtools_social_share.html.twig
Nit:
```suggestion
 * @see ./modules/contrib/oe_webtools/modules/oe_webtools_social_share/templates/oe-webtools-social-share.html.twig
```

2022-05-02 08:13 UTC, brummbar approved these changes

2022-05-02 08:15 UTC, drishu approved these changes

2022-05-02 08:44 UTC, merged