OEL-1374: Search page change published on > creation date.
openeuropa/oe_showcase pull request #113
Opened 2022-04-25 07:25 UTC by escuriola

## OPENEUROPA-1374

### Description

Search page change published on > creation date.

### Change log

- Added:
- Changed: Search page change published on > creation date.
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2022-04-28 10:54 UTC, drishu requested changes

2022-04-28 10:54 UTC, drishu commented on modules/oe_showcase_search/config/install/facets.facet.published_on.yml
> +      from: 'Creation date (from)'
either provide and update hook or don't touch it

2022-04-29 07:13 UTC, drishu requested changes

2022-04-29 07:13 UTC, drishu commented on modules/oe_showcase_search/config/install/facets.facet.published_on.yml
> +      from: 'Creation date (from)'
either provide and update hook or don't touch it

2022-04-29 07:13 UTC, drishu commented on modules/oe_showcase_search/config/overrides/facets.facet.published_on.yml
> +langcode: en
override folder is for overriding, like displays in the theme, this should go into a post_update folder.

But we are apending to much time for nothing, drop the facet label changes.
Lets fix this on v2 or something..

2022-05-02 06:06 UTC, drishu approved these changes, later dismissed

2022-05-03 07:38 UTC, drishu submitted a review, later dismissed

2022-05-04 12:11 UTC, Maxfire approved these changes, later dismissed

2022-05-04 12:56 UTC, Maxfire approved these changes, later dismissed

2022-05-12 14:02 UTC, drishu submitted a review, later dismissed

2022-05-12 14:11 UTC, Maxfire submitted a review, later dismissed

2022-05-12 14:38 UTC, Maxfire approved these changes

2022-05-12 14:40 UTC, drishu approved these changes

2022-05-12 14:40 UTC, merged