OEL-1446: Add cookie consent management
openeuropa/oe_showcase pull request #114
Opened 2022-04-25 09:25 UTC by abel-santos-corral

## OPENEUROPA-[OEL-1446](https://citnet.tech.ec.europa.eu/CITnet/jira/browse/OEL-1446)

### Description

We need to have cookie consent management at OE Showcase

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

2022-04-27 11:17 UTC, drishu requested changes

2022-04-27 11:17 UTC, drishu commented on tests/src/ExistingSite/ShowcaseExistingSiteTestBase.php
> +  protected function assertCookieConsentBlock(): void {
this is not a block, also this needs to appear in all pages, not just content type, so we need to assert in a few scenarios:
-like the front page, 
-yes a node (this way we cover entity urls), 
-you can do also the node listing (the one from core /node),
and for me that would be enough, maybe also just checking front would suffice, but better to have a bit more coverage.
In any case, create a separate test, ad this helper there no here

2022-04-27 11:17 UTC, drishu commented on tests/src/ExistingSite/ShowcaseExistingSiteTestBase.php
> +    $head_content = $this->cssSelect('head')[0];
since this is not a block we really don't care about its placement, just fetch the page content

2022-04-27 11:17 UTC, drishu commented on tests/src/ExistingSite/ShowcaseExistingSiteTestBase.php
> +    $this->assertSession()->elementExists('css', 'script[type="application/json"]');
y, but since this is a tag in the head section, you can just assert the tag is there
like assertStringContainsString('<script type..', $page->getHtml()) something like this

2022-04-27 11:17 UTC, drishu commented on modules/oe_showcase_page/tests/src/ExistingSite/PageTest.php
> +    $this->assertCookieConsentBlock();
remove

2022-04-27 11:17 UTC, drishu commented on tests/src/ExistingSite/ShowcaseExistingSiteCreateEventTest.php
> +    $this->assertCookieConsentBlock();
remove

2022-04-27 11:17 UTC, drishu commented on tests/src/ExistingSite/ShowcaseExistingSiteCreateNewsTest.php
> +    $this->assertCookieConsentBlock();
remove

2022-04-29 05:49 UTC, drishu reviewed
Take a closer look at the comments pls

2022-04-29 05:49 UTC, drishu commented on tests/src/ExistingSite/ShowcaseExistingSiteCookieConsentTest.php
> +class ShowcaseExistingSiteCookieConsentTest extends ShowcaseExistingSiteTestBase {
CookieConsentTest

2022-04-29 05:49 UTC, drishu commented on tests/src/ExistingSite/ShowcaseExistingSiteCookieConsentTest.php
> +   * @dataProvider cookieConsentBlockPagesPathProvider
dont use a provider just call drupalGet a few times and the assert

2022-04-29 05:49 UTC, drishu commented on tests/src/ExistingSite/ShowcaseExistingSiteCookieConsentTest.php
> +   * Asserts Cookie Consent block.
not a block

2022-04-29 05:49 UTC, drishu commented on tests/src/ExistingSite/ShowcaseExistingSiteCookieConsentTest.php
> +  public function testCookieConsentBlock(string $page): void {
not a block

2022-04-29 05:49 UTC, drishu commented on tests/src/ExistingSite/ShowcaseExistingSiteTestBase.php
> +  protected function assertCookieConsentBlock(): void {
not a block

2022-04-29 05:49 UTC, drishu commented on tests/src/ExistingSite/ShowcaseExistingSiteTestBase.php
> +    $page = $this->getSession()->getPage();
no point in creating a variable for a one time use

2022-04-29 05:49 UTC, drishu commented on tests/src/ExistingSite/ShowcaseExistingSiteCookieConsentTest.php
> + * Class to test Cookie Consent existing.
at least drop the "existing"

2022-05-02 12:48 UTC, drishu requested changes

2022-05-02 12:48 UTC, drishu commented on oe_showcase.post_update.php
> +function oe_showcase_post_update_00003(&$sandbox) {
make this oe_showcase_post_update_00002, as it has not been released yet

2022-05-02 12:48 UTC, drishu commented on tests/src/ExistingSite/ShowcaseExistingSiteTestBase.php
> +  protected function assertCookieConsent(): void {
move this to CookieConsentTest, don't know if we will need these somewhere else later but for now we need it only there

2022-05-03 07:26 UTC, drishu approved these changes

2022-05-03 16:02 UTC, brummbar approved these changes

2022-05-03 16:02 UTC, merged