OEL-1459: Activate Feedback block
openeuropa/oe_showcase pull request #116
Opened 2022-04-26 14:18 UTC by abel-santos-corral

## OPENEUROPA-[OEL-1459](https://citnet.tech.ec.europa.eu/CITnet/jira/browse/OEL-1459)

### Description

We have been requested to add Feedback block at oe_showcase in all pages.
Users with specific permissions should be able to configure the feedback form ID and status.

2022-04-29 18:40 UTC, brummbar requested changes

2022-04-29 18:40 UTC, brummbar commented on tests/src/ExistingSite/ShowcasePageFeedbackFormTest.php
> +    $this->languageManager = $this->container->get('language_manager');
What is this needed for?

2022-04-29 18:40 UTC, brummbar commented on tests/src/ExistingSite/ShowcasePageFeedbackFormTest.php
> +    $this->assertEquals('block-showcase-pagefeedbackform', $page_feedback->getAttribute('id'));
A small improvement since we have an easier way in our theme:
```
$this->assertSession()->elementExists('css', '#block-showcase-pagefeedbackform + #block-oe-whitelabel-neutral-footer');
```
This gets converted to a similar xpath to the above, but it's much easier to read.

2022-04-29 18:40 UTC, brummbar commented on oe_showcase.info.yml
> +  - oe_webtools_page_feedback
Down below, we need to add our two new configs to the config_devel entries.

2022-05-06 10:25 UTC, abel-santos-corral commented on oe_showcase.post_update.php
> +use Drupal\oe_bootstrap_theme\ConfigImporter;
This has to be refered to the oe_showcase element. Please, change it.

2022-05-06 10:37 UTC, brummbar requested changes

2022-05-06 10:37 UTC, brummbar commented on src/ConfigImporter.php
> +class ConfigImporter {
This is a 1 to 1 copy from the bootstrap one, which always worked for us too, now that I checked. What are we doing?

2022-05-06 10:37 UTC, brummbar commented on tests/src/ExistingSite/ShowcasePageFeedbackFormTest.php
> +    $this->assertSession()->elementExists('css', '#block-showcase-pagefeedbackform + #block-oe-whitelabel-neutral-footer');
The 3rd line was my suggestion to replace the other two.

2022-05-06 10:37 UTC, brummbar commented on oe_showcase.post_update.php
> +use Drupal\oe_bootstrap_theme\ConfigImporter;
No, the whole class is useless, as we just renamed a parameter.

2022-05-09 13:59 UTC, brummbar approved these changes, later dismissed

2022-05-09 14:22 UTC, brummbar submitted a review, later dismissed

2022-05-10 07:17 UTC, abel-santos-corral commented on src/ConfigImporter.php
> +    return new FileStorage(\Drupal::service('extension.list.module')->getPath($profile) . $path);
@escuriola : My error is that I didn't corrected that, instead of that extension.list.module, it's supposed to be extension.list.profile. The only reason to use this configImporter was to get the config/post_update inside a module of the profile. 
But in on a comment @brummbar states that is not necessary to add a configImporter for the small change we are doing. Nevertheless, you have to check if configImporter must need dual use for profile and modules (at oe_bootstrap_theme) and if so, create a ticket on jira.

2022-05-10 13:48 UTC, brummbar commented on src/ConfigImporter.php
> +    return new FileStorage(\Drupal::service('extension.list.module')->getPath($profile) . $path);
No @abel-santos-corral , the error was to raise a concern for something that was not needed.
This is in the `extension.list.module` service:
![image](https://user-images.githubusercontent.com/8488617/167641601-e82e4b96-6c53-41db-a947-cc69ae338f07.png)
We don't need to change anything here, because it already takes care of the profiles folder.
We did already the changes anyway for take into account themes or modules in another ticket.

2022-05-13 08:06 UTC, drishu requested changes

2022-05-13 08:06 UTC, drishu commented on tests/src/ExistingSite/ShowcasePageFeedbackFormTest.php
> +  protected $languageManager;
this is not used, please remove

2022-05-13 12:07 UTC, drishu submitted a review, later dismissed

2022-05-13 12:38 UTC, brummbar requested changes

2022-05-13 12:38 UTC, brummbar commented on tests/src/ExistingSite/ShowcasePageFeedbackFormTest.php
> +class ShowcasePageFeedbackFormTest extends ExistingSiteBase {
Let's use \Drupal\Tests\oe_showcase\ExistingSite\ShowcaseExistingSiteTestBase, in showcase always use our base tests.

2022-05-13 13:56 UTC, brummbar requested changes

2022-05-13 13:56 UTC, brummbar commented on tests/src/ExistingSite/ShowcasePageFeedbackFormTest.php
> +    $this->restoreConfiguration();
The parent does this already, and most of the setup too.

2022-05-13 15:47 UTC, brummbar approved these changes

2022-05-13 17:55 UTC, drishu approved these changes

2022-05-15 08:11 UTC, merged