OEL-1498: User management role and settings
openeuropa/oe_showcase pull request #117
Opened 2022-04-29 11:27 UTC by GilNovacomm

## OPENEUROPA-[Insert ticket number here]

### Description

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2022-04-29 13:12 UTC, Maxfire commented on oe_showcase.info.yml
> +  - block
This should go on top.

2022-04-29 13:14 UTC, Maxfire commented on src/ConfigImporter.php
> +<?php
If we're using the oe_bootstrap_theme configImporter I guess we can remove this.

2022-04-29 13:22 UTC, Maxfire commented on tests/src/ExistingSite/ManageUsersRoleTest.php
> +    // Assert users without the "Manage users" role cannot edit user accounts.
```suggestion
    $assertions = $this->assertSession();
```

2022-04-29 13:24 UTC, Maxfire commented on tests/src/ExistingSite/ManageUsersRoleTest.php
> +    $this->assertSession()->pageTextContains('Access denied');
```suggestion
    $assertions = $this->assertSession();
    $assertions->->getPage();
```

2022-05-02 12:38 UTC, drishu requested changes

2022-05-02 12:38 UTC, drishu commented on composer.json
> +        "drupal/roleassign": "1.x-dev@dev",
why not use the beta release ?

2022-05-02 12:38 UTC, drishu commented on oe_showcase.post_update.php
> + * Import the Manage users role.
we are doing more then the role also 'Create' is a better choice

but also merge this with the one above as oe_showcase_post_update_00002 was not released yet

2022-05-02 12:38 UTC, drishu commented on tests/src/ExistingSite/ManageUsersRoleTest.php
> +    $user = $this->createUser();
seems redundant, maybe with an editor would make more sense

2022-05-02 12:38 UTC, drishu commented on tests/src/ExistingSite/ManageUsersRoleTest.php
> +    $config = \Drupal::config('roleassign.settings');
rather with above logged in user, go to the user creation page, and confirm other roles cannot be assigned (as in roles that should not be present on the page)

2022-05-02 12:38 UTC, drishu commented on tests/src/ExistingSite/ManageUsersRoleTest.php
> +  }
we also need to test for the other changes: lock permissions, prevent role assignments during bulk import, new users need to be approved upon registration

2022-05-02 16:00 UTC, GilNovacomm commented on tests/src/ExistingSite/ManageUsersRoleTest.php
> +    $user = $this->createUser();
I need it to not have a role in order to test later that a user with Manage users role can assign this user the Editor role.

2022-05-05 12:05 UTC, drishu commented on oe_showcase.post_update.php
> +    'roleassign.settings',
this is not the way to do it, it will throw an error

2022-05-05 12:05 UTC, drishu commented on tests/src/ExistingSite/ManageUsersRoleTest.php
> +class ManageUsersRoleTest extends ExistingSiteBase {
I dont get why we dont use ShowcaseExistingSiteTestBase

2022-05-05 12:05 UTC, drishu commented on tests/src/ExistingSite/ManageUsersRoleTest.php
> +  use AuthenticationTrait;
remove these

2022-05-05 12:05 UTC, drishu commented on tests/src/ExistingSite/ManageUsersRoleTest.php
> +  protected function setUp(): void {
adapt this

2022-05-05 12:05 UTC, drishu commented on tests/src/ExistingSite/ManageUsersRoleTest.php
> +  public function tearDown(): void {
remove this

2022-05-05 12:05 UTC, drishu commented on tests/src/ExistingSite/ManageUsersRoleTest.php
> +    $user = $this->createUser();
you'r not even logging the user in, what's the point of visiting 'admin/people' as anopnymous user, this needs to be removed

2022-05-05 13:03 UTC, drishu requested changes
Please rework the test, its a mess.
Pls go over the points in the description and make a plan for each one

2022-05-05 13:03 UTC, drishu commented on tests/src/ExistingSite/ManageUsersRoleTest.php
> +
We need to test a user with the permissions to visit this page and assert that the edit and delete links are missing.

2022-05-05 13:03 UTC, drishu commented on tests/src/ExistingSite/ManageUsersRoleTest.php
> +    $this->backupSimpleConfig('user.role.manage_users');
where are these changed? I dont see it, please could you point it out

2022-05-05 13:03 UTC, drishu commented on tests/src/ExistingSite/ManageUsersRoleTest.php
> +    // Assert the People administration page is available only for users with
this comment is wrong, its not "only for users with .."

2022-05-05 13:03 UTC, drishu commented on tests/src/ExistingSite/ManageUsersRoleTest.php
> +    // Assure users with the "Manage users" role can assign
this is the bulk import test, the comment is wrong

2022-05-05 13:03 UTC, drishu commented on tests/src/ExistingSite/ManageUsersRoleTest.php
> +    $this->assertTrue(in_array('editor', $user->getRoles()));
I dont mind the double check but use assertIsArray()

2022-05-05 13:03 UTC, drishu commented on tests/src/ExistingSite/ManageUsersRoleTest.php
> +    $assertions->pageTextContains('Add the Editor role to the selected user(s)'
also assert the manage users role is not present

2022-05-05 13:03 UTC, drishu commented on tests/src/ExistingSite/ManageUsersRoleTest.php
> +    $this->drupalGet('admin/people');
didn't we go to admin/people before with the same user logged in? seems to check the same thing, this needs some order

2022-05-05 13:03 UTC, drishu commented on tests/src/ExistingSite/ManageUsersRoleTest.php
> +    $this->assertTrue($authenticated_user->isBlocked());
this gives the same result no matter what setting I use, rather go to /user/register, submit the form, assert the result

2022-05-05 13:27 UTC, drishu commented on tests/src/ExistingSite/ManageUsersRoleTest.php
> +    $user_role = Role::load('manage_users');
rather than doing this I would create a user with permissions and try to add a new permission to a role (can be the manage_users).

2022-05-12 06:51 UTC, drishu commented on tests/src/ExistingSite/AuthorisationTest.php
> + * Tests that users can only access pages they are authorized to.
Most of these comments I would have written differently but I wanted to follow ewcms more closely

2022-05-12 06:51 UTC, drishu commented on tests/src/ExistingSite/AuthorisationTest.php
> + * Tests that users can only access pages they are authorized to.
Most of these comments I would have written differently but I wanted to follow ewcms more closely

2022-05-12 06:52 UTC, drishu commented on tests/src/ExistingSite/AuthorisationTest.php
> +  public function testManageUsersRoleAssign(): void {
this was under authorisation but I feel it belongs more under UserManagement

2022-05-12 06:52 UTC, drishu commented on tests/src/ExistingSite/AuthorisationTest.php
> +  public function testManageUsersRoleAssign(): void {
this was under authorisation but I feel it belongs more under UserManagement

2022-05-12 06:54 UTC, drishu commented on tests/src/ExistingSite/AuthorisationTest.php
> +  protected function assertCheckboxesDisabled(): void {
this one I copied over from the test I deleted but was 2 tired to make a separate commit with attribution or cherry pick

2022-05-12 06:54 UTC, drishu commented on tests/src/ExistingSite/AuthorisationTest.php
> +  protected function assertCheckboxesDisabled(): void {
this one I copied over from the test I deleted but was 2 tired to make a separate commit with attribution or cherry pick

2022-05-12 06:55 UTC, drishu commented on tests/src/ExistingSite/EULoginTest.php
> +      $this->assertSession()->buttonExists('Login!');
Login! is there only if eulogin mock is used btw

2022-05-12 06:55 UTC, drishu commented on tests/src/ExistingSite/EULoginTest.php
> +      $this->assertSession()->buttonExists('Login!');
Login! is there only if eulogin mock is used btw

2022-05-12 06:57 UTC, drishu commented on tests/src/ExistingSite/EULoginTest.php
> +    if ($user) {
I feel this should fail if user is empty, is copy pasta, so if it was reviewed and demed ok there then..

2022-05-12 06:57 UTC, drishu commented on tests/src/ExistingSite/EULoginTest.php
> +    if ($user) {
I feel this should fail if user is empty, is copy pasta, so if it was reviewed and demed ok there then..

2022-05-12 06:58 UTC, drishu commented on tests/src/Traits/UserTrait.php
> +   *   The user.
majestic

2022-05-12 06:58 UTC, drishu commented on tests/src/Traits/UserTrait.php
> +   *   The user.
majestic

2022-05-12 06:59 UTC, drishu commented on tests/src/Traits/UserTrait.php
> +      throw new \Exception(sprintf('The user with the name %s does not exist.', $username));
copy pasta, feel like I should replace there with ->assert(..

2022-05-12 06:59 UTC, drishu commented on tests/src/Traits/UserTrait.php
> +      throw new \Exception(sprintf('The user with the name %s does not exist.', $username));
copy pasta, feel like I should replace there with ->assert(..

2022-05-12 07:02 UTC, drishu commented on runner.yml.dist
> +    - "./vendor/bin/drush en config_devel oe_authentication_eulogin_mock -y"
in ewcms the service is also started, but I dont see the value of that for us, if we use the actual eulogin then we can also test the user fields in a manual test

2022-05-12 07:02 UTC, drishu commented on runner.yml.dist
> +    - "./vendor/bin/drush en config_devel oe_authentication_eulogin_mock -y"
in ewcms the service is also started, but I dont see the value of that for us, if we use the actual eulogin then we can also test the user fields in a manual test

2022-05-12 07:07 UTC, drishu commented on tests/src/ExistingSite/EULoginTest.php
> +    $this->assertSession()->addressEquals('/en');
I feel I should have grabbed the Url with '<front>' and compared but I'm 2 tired to judge right now, so I leave that 2 next reviewer

2022-05-12 07:08 UTC, drishu submitted a review, later dismissed
Comments I left above are more things I point out than feedback, I feel I brought enough improvements, and we need to move on, so I approve.

2022-05-18 20:37 UTC, donquixote commented on composer.json
> +        "drupal/cas_mock_server": "^1.4",
This should probably be in require-dev.

2022-05-18 20:39 UTC, donquixote commented on oe_showcase.info.yml
> +  - cas_mock_server
No need to enable by default, or is it?

2022-05-18 21:03 UTC, donquixote commented on config/post_updates/00003_manage_users/roleassign.settings.yml
> +  manage_users: '0'
This file seems not necessary for post update.

2022-05-18 21:03 UTC, donquixote commented on config/post_updates/00003_manage_users/user.role.manage_users.yml
> +  - 'view the administration theme'
Also this one: It is a new role, so no post update needed.

2022-05-18 21:03 UTC, donquixote commented on oe_showcase.post_update.php
> +  ConfigImporter::importMultiple('profile', 'oe_showcase', '/config/post_updates/00003_manage_users', $configs);
Not needed, this is a new role.

2022-05-18 21:09 UTC, donquixote commented on config/post_updates/00003_manage_users/roleassign.settings.yml
> +  manage_users: '0'
It will be a pain to keep this up to date.
In most recent 1.x we now have `user.role.configure_page_feedback_form`.

2022-05-18 21:42 UTC, donquixote commented on oe_showcase.profile
> +    foreach ($permissions_by_provider as $provider => $permissions) {
We are overwriting the outer scope variable `$permissions`. No harm here, but not good practice.
(I know it is copied but still)

2022-05-18 22:03 UTC, donquixote commented on oe_showcase.profile
> +    foreach ($permissions_by_provider as $provider => $permissions) {
Also we are not really using the `$provider` variable.
The code is trying to replicate UserPermissionsForm, but it is not needed here.

2022-05-18 22:05 UTC, donquixote commented on oe_showcase.profile
> +        $form['permissions'][$perm][$rid]['#attributes']['disabled'] = TRUE;
Let's use `'#disabled' => TRUE` instead of `'#attributes']['disabled' => TRUE`, to prevent client-side tampering.
See https://drupal.stackexchange.com/questions/262646/how-to-make-form-field-read-only#comment393084_262647

2022-05-18 22:27 UTC, donquixote commented on oe_showcase.profile
> +  \Drupal::messenger()->addMessage(t('Role management is disabled in OE Showcase. Roles and associated permissions are only changeable by users with Manage users role.'), MessengerInterface::TYPE_WAR
I think this message is not fully accurate for our situation.
I see it is coming [from ewcms}(https://github.com/ec-europa/ewcms/blob/develop/modules/ewcms_authorisation/ewcms_authorisation.module#L23), but their setup is a bit different.

I think for us it is like this:
- Roles and permissions are managed by developers by deploying new code.
- Users with 'Manage users' role can assign specific roles to users.
- This form is read-only.

2022-05-18 22:28 UTC, donquixote commented on oe_showcase.profile
> +  $form['actions']['submit']['#access'] = FALSE;
I was a bit curious if this is fully reliable against client-side tampering. What if we insert a client-side button?
Doesn't seem to work. The form is not submitted.
So it _seems_ to be safe.

2022-05-18 22:32 UTC, donquixote commented on oe_showcase.profile
> +  foreach ($form['entities'] as &$entity) {
Weird variable name for a form/render element array.

2022-05-18 22:33 UTC, donquixote commented on oe_showcase.profile
> +  foreach ($form['entities'] as &$entity) {
But ok if we want to align with ewcms.

2022-05-18 22:35 UTC, donquixote commented on oe_showcase.profile
> +      }
So we remove 'edit' and 'delete' but we keep 'Edit permissions' and 'Translate'.
Ok I guess.
The 'Edit permissions' goes to the read-only form so it is fine.

2022-05-18 22:43 UTC, donquixote commented on oe_showcase.profile
> +      ->get('roleassign_roles')));
We could apply the array_intersect_key directly on `$form['roles']['#options']` instead of calling `user_role_names()` first.
But let's keep aligned with ewcms.

2022-05-18 22:45 UTC, donquixote commented on oe_showcase.profile
> +      ->get('roleassign_roles')));
Also the local variable `$assignable_roles` is a bit pointless if it contains 1:1 what we write to '#options'.
A local var for the rolassign setting would make more sense, as it would help to split up the long expression.

I see this is copied from roleassign module itself, so whatever.

2022-05-18 22:55 UTC, donquixote commented on tests/src/ExistingSite/AuthorisationTest.php
> +    }
Shouldn't we login first, if we want to test authenticated user? Or does this magically happen somewhere?

2022-05-18 22:55 UTC, donquixote commented on tests/src/ExistingSite/AuthorisationTest.php
> +  }
This method is pointless, add the urls to the tests above.

2022-05-18 22:56 UTC, donquixote commented on tests/src/ExistingSite/AuthorisationTest.php
> +  }
(if we are still testing for anon and authenticated)

2022-05-18 22:57 UTC, donquixote commented on tests/src/ExistingSite/AuthorisationTest.php
> +  public function testManageUsersRoleAssign(): void {
I think we should have one method per role we want to test, and cover paths with and without access.
Or we could use a data provider - but let's keep it simple for now.

2022-05-18 22:59 UTC, donquixote commented on tests/src/ExistingSite/AuthorisationTest.php
> +    $this->drupalLogin($user);
We call this regularly, so what about a helper to be called like this:
```suggestion
    $this->loginWithRoles(['manage_users']);
```

2022-05-18 23:12 UTC, donquixote commented on tests/src/ExistingSite/UserManagementTest.php
> +    $link = $this->getSession()->getPage()->findLink($username);
My IDE (+ EA plugin) would like to see `$this->assertNotNull($link)` here to avoid inspection warning below.
But perhaps we don't care in tests, and use the error as test fail.

2022-05-18 23:14 UTC, donquixote commented on tests/src/ExistingSite/AuthorisationTest.php
> +    $this->assertRoleOptionsNotAvailable(['Manage users']);
I think this part should go into UserManagementTest.
Instead of testing individual operations we can simply check the complete list of bulk update options. This way we test everything the user manager can do.
I think we can't do a negative test, because users without this perm can't even visit the page..

2022-05-18 23:18 UTC, donquixote commented on tests/src/ExistingSite/AuthorisationTest.php
> +    ]);
This test is a bit pointless:
- We don't even have a role field on user edit form. We disabled it in the form settings. So the user with 'manage_users' role would also not get these options.
- Lack of contrasting test for user 'manage_users' role. -> this would reveal why it's pointless.
- Assertion does not distinguish between not having these specific role checkboxes vs not having a roles input group at all.

2022-05-18 23:18 UTC, donquixote commented on tests/src/ExistingSite/AuthorisationTest.php
> +    $this->assertSession()->statusCodeEquals(403);
This can be covered in the route tests above.

2022-05-18 23:20 UTC, donquixote commented on tests/src/ExistingSite/AuthorisationTest.php
> +    $this->assertRoleOptionsNotAvailable(['Manage users']);
> I think we can't do a negative test, because users without this perm can't even visit the page..
actually yes we can with custom perm

2022-05-18 23:24 UTC, donquixote commented on tests/src/ExistingSite/AuthorisationTest.php
> +    $this->assertCheckboxesDisabled();
Does this really need to be a helper method?
Seems it is only used 1x.

2022-05-18 23:27 UTC, donquixote commented on tests/src/ExistingSite/AuthorisationTest.php
> +      ->findAll('css', '.form-checkbox');
Do we want to rely on `'.form-checkbox'`?
If for some reason the class is removed from checkbox elements, then we will get a passing test that checks nothing.

2022-05-18 23:30 UTC, donquixote commented on tests/src/ExistingSite/AuthorisationTest.php
> +      ->findAll('css', '.form-checkbox');
Maybe assert a min count? E.g. min 30 checkboxes. And use different kind of selector?
Use count queries and compare count of `input[type=checkbox][disabled]` vs count of `input[type=checkbox]`?
Target the form?

2022-05-18 23:33 UTC, donquixote commented on tests/src/ExistingSite/AuthorisationTest.php
> +  }
These two methods could be combined:
Assert the full list of role options.

2022-05-18 23:35 UTC, donquixote commented on tests/src/ExistingSite/AuthorisationTest.php
> +    $assert->linkNotExistsExact('Delete');
There should be a contrasting test for user with manage_users who _can_ see these links.

2022-05-18 23:37 UTC, donquixote commented on tests/src/ExistingSite/AuthorisationTest.php
> +    $assert->linkNotExistsExact('Delete');
Also we should verify that the other links are still there, and that the list of roles is not empty.

2022-05-18 23:39 UTC, donquixote commented on tests/src/ExistingSite/AuthorisationTest.php
> +    $this->assertCheckboxesDisabled();
Also check that the form is still there.
E.g. we could check one or a few example role/perm checkboxes.

2022-05-18 23:42 UTC, donquixote commented on tests/src/ExistingSite/EULoginTest.php
> +      $this->assertSession()->buttonExists('Login!');
And the existence of 'Login!' button tells us reliably that "EU login is enforced"? Interesting.

2022-05-18 23:46 UTC, donquixote commented on tests/src/ExistingSite/EULoginTest.php
> +    $this->markEntityTypeForCleanup('user');
Shouldn't this be called before creating entities?
Or in case of user it might not be needed at all?

2022-05-18 23:46 UTC, donquixote commented on tests/src/ExistingSite/EULoginTest.php
> +    $this->markEntityTypeForCleanup('user');
How to test: Run the test, see if leftover user is still there.

2022-05-18 23:49 UTC, donquixote commented on tests/src/ExistingSite/EULoginTest.php
> +    $this->assertIsHomepage();
Is there no way to assert if you are currently logged in or not?
I assume the first attempt fails, the second attempt is successful, and then the logout is successful again.

2022-05-18 23:52 UTC, donquixote commented on tests/src/ExistingSite/EULoginTest.php
> +    $this->assertSession()->addressEquals('/en');
Yeah seems a bit awkward, but it does the job.
It does not check query parameters but that's ok.

2022-05-18 23:56 UTC, donquixote commented on tests/src/ExistingSite/EULoginTest.php
> +    if ($user) {
Indeed we should assert not null instead of this if().
I did not find the tests in ewcms, but I believe you saying it is copypasta. But we should fix where it makes sense, and possibly report back to the source after.

2022-05-18 23:59 UTC, donquixote commented on runner.yml.dist
> +    - "./vendor/bin/drush en config_devel oe_authentication_eulogin_mock -y"
No opinion on this atm, I would need to try it myself.

2022-05-19 00:00 UTC, donquixote commented
One thing I notice:
The roles element is disabled in the used edit form display.
This means the only way to assign roles is via bulk edit.
Is this how we want it to be?

2022-05-19 10:20 UTC, drishu commented on oe_showcase.profile
> +    foreach ($permissions_by_provider as $provider => $permissions) {
dont want to touch it if no adaptation needed

2022-05-19 10:21 UTC, drishu commented on oe_showcase.profile
> +        $form['permissions'][$perm][$rid]['#attributes']['disabled'] = TRUE;
dont want to touch

2022-05-19 10:21 UTC, drishu commented on oe_showcase.profile
> +  \Drupal::messenger()->addMessage(t('Role management is disabled in OE Showcase. Roles and associated permissions are only changeable by users with Manage users role.'), MessengerInterface::TYPE_WAR
dont want to touch

2022-05-19 10:22 UTC, drishu commented on oe_showcase.profile
> +  $form['actions']['submit']['#access'] = FALSE;
ok

2022-05-19 10:22 UTC, drishu commented on oe_showcase.profile
> +  foreach ($form['entities'] as &$entity) {
dont want to touch

2022-05-19 10:23 UTC, drishu commented on oe_showcase.profile
> +      }
y

2022-05-19 10:23 UTC, drishu commented on oe_showcase.profile
> +      ->get('roleassign_roles')));
yes, lets keep aligned

2022-05-19 10:27 UTC, drishu commented on config/post_updates/00003_manage_users/roleassign.settings.yml
> +  manage_users: '0'
done

2022-05-19 10:30 UTC, drishu commented on tests/src/ExistingSite/AuthorisationTest.php
> +  }
forgot the create the user with the role, thx

2022-05-19 10:31 UTC, drishu commented on tests/src/ExistingSite/AuthorisationTest.php
> +  public function testManageUsersRoleAssign(): void {
so it was like this in ewcms where I copied the approach from, again, I would have done it slightly differently but the scope of the ticket was to have ewcms as a guideline

2022-05-19 10:35 UTC, drishu commented on tests/src/ExistingSite/AuthorisationTest.php
> +    $this->assertRoleOptionsNotAvailable(['Manage users']);
its a bit gray here, I think the logic is that we assert the access to that functionality is restricted

2022-05-19 10:36 UTC, drishu commented on tests/src/ExistingSite/AuthorisationTest.php
> +    $this->assertSession()->statusCodeEquals(403);
in ewcms they test more roles, we will also have more roles, so I think this partitioning will start to pay off soon

2022-05-19 10:48 UTC, drishu commented on tests/src/ExistingSite/AuthorisationTest.php
> +    $this->assertCheckboxesDisabled();
for readability

2022-05-19 10:55 UTC, drishu commented on tests/src/ExistingSite/AuthorisationTest.php
> +  }
we can discuss in a follow up

2022-05-19 10:56 UTC, drishu commented on tests/src/ExistingSite/AuthorisationTest.php
> +      ->findAll('css', '.form-checkbox');
yes, I will assert count

2022-05-19 10:58 UTC, drishu commented on tests/src/ExistingSite/EULoginTest.php
> +      $this->assertSession()->buttonExists('Login!');
yes

2022-05-19 11:00 UTC, drishu commented on tests/src/ExistingSite/EULoginTest.php
> +    $this->assertSession()->addressEquals('/en');
well keep like this

2022-05-19 11:30 UTC, drishu commented on tests/src/ExistingSite/AuthorisationTest.php
> +    $assert->linkNotExistsExact('Delete');
follow up

2022-05-19 11:42 UTC, drishu commented on tests/src/ExistingSite/EULoginTest.php
> +    $this->markEntityTypeForCleanup('user');
I tested, it works fine and its needed, we create a user through eulogin mock so we need to delete him

2022-05-19 11:44 UTC, drishu commented on tests/src/ExistingSite/EULoginTest.php
> +    $this->assertIsHomepage();
its not fancy but I added something for it

2022-05-19 12:12 UTC, drishu commented on tests/src/ExistingSite/AuthorisationTest.php
> +    $this->drupalLogin($user);
> One thing I notice: The roles element is disabled in the used edit form display. This means the only way to assign roles is via bulk edit. Is this how we want it to be?

No, we should create a ticket to not hide those elements via form display but via access in form alter

2022-05-19 15:18 UTC, brummbar commented on tests/src/Traits/UserTrait.php
> +      throw new \Exception(sprintf('The user with the name %s does not exist.', $username));
No, this is not an assertion, this is an helper method. The test using this can catch and re-launch if needed.

2022-05-19 15:35 UTC, donquixote commented on oe_showcase.post_update.php
> +  $roleassign_config->set('roleassign_roles', $roleassign_roles)->save();
One more role needed.
Otherwise ok for me.

2022-05-19 15:46 UTC, donquixote commented on oe_showcase.profile
> +}
I've been thinking: What we are doing here is super weird.
All of the modifications on permissions page and roles page only apply to users with `'administer permissions'`.
However, none of the roles we create have this perm.

In ewcms it is a bit different:
- The 'manage_patform_user' role has 'administer permissions', but not 'assign roles'. Don't ask me why!
- The 'manage_users' role has 'assign roles', but not 'administer permissions'.
- The custom form alter hooks make sure that the 'administer (roles and) permissions' is effectively just 'view (roles and) permissions'. But this is only relevant for 'manage_platform_user' role.

2022-05-19 15:56 UTC, donquixote commented on oe_showcase.profile
> +}
Anyway no time to change it now.

2022-05-19 15:57 UTC, donquixote commented on tests/src/Traits/UserTrait.php
> +   * Creates a user, assigns given roles and logs the user in.
Not really, no login happens here.

2022-05-19 15:58 UTC, donquixote commented on tests/src/Traits/UserTrait.php
> +   * Creates a user, assigns given roles and logs the user in.
```suggestion
   * Creates a user with given roles.
```

2022-05-19 16:00 UTC, donquixote commented on tests/src/ExistingSite/AuthorisationTest.php
> +      '/admin/people/roleassign',
I think we can add admin/people/permissions

2022-05-19 16:07 UTC, donquixote commented on tests/src/ExistingSite/AuthorisationTest.php
> +    $assert->statusCodeEquals(200);
This seems like a bug: You can add roles but you cannot edit?
But let's leave it like this, this entire functionality might be pointless anyway if nobody has 'administer permissions'.

2022-05-19 16:09 UTC, donquixote commented on tests/src/ExistingSite/EULoginTest.php
> +    $this->assertIsHomepage();
hm I don't like relying on text not exists.
But let's keep it.

2022-05-19 16:22 UTC, donquixote commented on tests/src/Traits/UserTrait.php
> +      throw new \Exception(sprintf('The user with the name %s does not exist.', $username));
I don't think the separation is so strict. There are assert calls in other places, e.g. in core UserCreationTrait:.createUser().
And tests usually don't want to catch exceptions, they assume it works, and if not we want the test to fail.
But let's keep it for now. An uncaught non-assert exception is also a kind of fail.

2022-05-19 16:25 UTC, donquixote commented on tests/src/ExistingSite/AuthorisationTest.php
> +    $this->assertCheckboxesDisabled();
Readability argument only works if the reader trusts that the helper method will do what is promised :)
But let's keep it
(resolve after reading)

2022-05-19 16:27 UTC, donquixote commented on oe_showcase.profile
> +}
(resolve after reading)

2022-05-19 16:36 UTC, donquixote commented on tests/src/ExistingSite/AuthorisationTest.php
> +    $assert->statusCodeEquals(200);
(resolve after reading)

2022-05-19 17:02 UTC, drishu commented on tests/src/ExistingSite/AuthorisationTest.php
> +    $assert->statusCodeEquals(200);
yes, the request was to prevent "user manager" specifically to access the role add

2022-05-19 18:56 UTC, donquixote approved these changes

2022-05-20 08:21 UTC, brummbar approved these changes

2022-05-20 08:22 UTC, merged