OEL-1248 - Events listing page.
openeuropa/oe_showcase pull request #118
Opened 2022-04-29 15:45 UTC by GilNovacomm

## OPENEUROPA-[Insert ticket number here]

### Description

[Insert description here]

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2022-05-02 10:53 UTC, drishu requested changes

2022-05-02 10:53 UTC, drishu commented on modules/oe_showcase_list_pages/tests/src/ExistingSite/ListPagesEventTest.php
> +class ListPagesEventTest extends ShowcaseExistingSiteTestBase {
for the testing, since we made changes to the scope, we should rather change ListPagesTest (where listings are already tested) and just 

1. add one event node,
2. when asserting the news items, now, also assert that ony news items are present
3. add another listing page but for events
4. assert the event items, and that ony those are present

2022-05-03 11:22 UTC, drishu approved these changes, later dismissed

2022-05-03 11:22 UTC, drishu commented on modules/oe_showcase_list_pages/oe_showcase_list_pages.info.yml
> +  - oe_starter_content:oe_starter_content_event
sort these lines

2022-05-03 11:44 UTC, donquixote commented on modules/oe_showcase_list_pages/oe_showcase_list_pages.info.yml
> +  - oe_starter_content:oe_starter_content_event
e before n

2022-05-03 13:59 UTC, donquixote requested changes

2022-05-03 13:59 UTC, donquixote commented on modules/oe_showcase_list_pages/tests/src/ExistingSite/ListPagesTest.php
> +      sprintf('%s list page (%s)', $listing_page_content, $expected_count),
```suggestion
      sprintf('%s (%s)', $list_page_title, $expected_count),
```

2022-05-03 13:59 UTC, donquixote commented on modules/oe_showcase_list_pages/tests/src/ExistingSite/ListPagesTest.php
> +  protected function assertSearchResultsTitle(string $listing_page_content, int $expected_count): void {
```suggestion
  protected function assertSearchResultsTitle(string $list_page_title, int $expected_count): void {
```

2022-05-03 13:59 UTC, donquixote commented on modules/oe_showcase_list_pages/tests/src/ExistingSite/ListPagesTest.php
> +   *   Expected List page content type title.
First, the parameter name `$listing_page_content` is weird.
Second, why not pass the complete node title of the list page?

```suggestion
   * @param string $list_page_title
   *   Title of the list page node.
```

2022-05-03 13:59 UTC, donquixote commented on modules/oe_showcase_list_pages/tests/src/ExistingSite/ListPagesTest.php
> +    $this->assertSearchResultsTitle('News', 6);
As suggested below, let's pass the entire node title to the method.
```suggestion
    $this->assertSearchResultsTitle('News list page', 6);
```

2022-05-03 13:59 UTC, donquixote commented on modules/oe_showcase_list_pages/tests/src/ExistingSite/ListPagesTest.php
> +    $this->assertSearchResultsTitle('News', 1);
As suggested let's pass the entire title to the method.
```suggestion
    $this->assertSearchResultsTitle('News list page', 1);
```

2022-05-03 13:59 UTC, donquixote commented on modules/oe_showcase_list_pages/tests/src/ExistingSite/ListPagesTest.php
> +    $this->assertSearchResultsTitle('Event', 0);
```suggestion
    $this->assertSearchResultsTitle('Event list page', 0);
```

2022-05-03 13:59 UTC, donquixote commented on modules/oe_showcase_list_pages/tests/src/ExistingSite/ListPagesTest.php
> +    ]);
We are not filtering anything here if there is only one event and it has "Event" in the title..

2022-05-03 13:59 UTC, donquixote commented on modules/oe_showcase_list_pages/config/install/facets.facet.oelp_oe_sc_event__content_type.yml
> +    settings: {  }
I tried and we don't need this facet.
We only need the content type field in the search index, that's enough.

2022-05-03 13:59 UTC, donquixote commented on modules/oe_showcase_list_pages/config/install/facets.facet.oelp_oe_sc_news__content_type.yml
> +    settings: {  }
I tried and we don't need this facet.
We only need the content type field in the search index, that's enough.

2022-05-03 13:59 UTC, donquixote commented on modules/oe_showcase_list_pages/tests/src/ExistingSite/ListPagesTest.php
> +    for ($i = 0; $i < 10; $i++) {
Why reduce it to 10 nodes?
With 12 nodes we can also test pagination.

2022-05-03 13:59 UTC, donquixote commented on modules/oe_showcase_list_pages/tests/src/ExistingSite/ListPagesTest.php
> +    ]);
If we have only a single event, we need to test 2x for date: One time with a date where the result will be empty, another time with a date where the existing event shows in the result.

This said, why do we only have one event? With multiple events we could test it all in one go.

2022-05-03 17:27 UTC, GilNovacomm commented on modules/oe_showcase_list_pages/tests/src/ExistingSite/ListPagesTest.php
> +    for ($i = 0; $i < 10; $i++) {
I've restored the number of items to test also pagination.

2022-05-03 17:30 UTC, GilNovacomm commented on modules/oe_showcase_list_pages/tests/src/ExistingSite/ListPagesTest.php
> +    ]);
I've followed the same number of Event nodes as for News to test filtering and pagination.

2022-05-03 19:34 UTC, donquixote commented on modules/oe_showcase_list_pages/oe_showcase_list_pages.info.yml
> -    - facets.facet.oelp_oe_sc_event__content_type
This would have been part of the other commit but ok :)

2022-05-03 19:41 UTC, donquixote approved these changes

2022-05-05 05:57 UTC, drishu approved these changes

2022-05-05 05:59 UTC, merged