OEL-1367: New Look & Feel for search form in search page.
openeuropa/oe_showcase pull request #122
Opened 2022-05-09 08:44 UTC by escuriola

## OPENEUROPA-1367

### Description

New Look & Feel for search form in search page and remove theming from block config form

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2022-05-10 13:22 UTC, drishu requested changes
the config changes need a update path

2022-05-15 08:13 UTC, drishu requested changes

2022-05-15 08:13 UTC, drishu commented on modules/oe_showcase_search/oe_showcase_search.post_update.php
> +    'block.block.oe_whitelabel_search_form',
this one you are doing already in the other PR

2022-05-15 08:13 UTC, drishu commented on modules/oe_showcase_search/oe_showcase_search.post_update.php
> +  ConfigImporter::importMultiple('module', 'oe_showcase_search', '/config/post_updates/00001', $configs);
this is not the way to do it, you are overriding stuff you should not touch

2022-05-15 08:46 UTC, drishu commented on modules/oe_showcase_search/config/optional/block.block.showcase_header_search_form.yml
> +    region: navigation_right
this would be the header region, looks like manually inserted here, pls update in UI and reexport via config_devel

2022-05-15 09:57 UTC, drishu requested changes
Also check if the existing test in oe_showcase_search needs to be amended

2022-05-24 16:10 UTC, drishu commented on modules/oe_showcase_search/oe_showcase_search.post_update.php
> +  ConfigImporter::importSingle(
I like it better on a single line but its not important

2022-05-24 16:10 UTC, drishu submitted a review, later dismissed

2022-05-25 15:28 UTC, drishu approved these changes, later dismissed

2022-06-03 15:26 UTC, donquixote commented on modules/oe_showcase_search/config/install/core.entity_view_display.node.oe_showcase_search_demo.teaser.yml
>    search_api_excerpt: true
Why commit noise in unrelated config files?
Ok to keep, just saying.

2022-06-03 15:26 UTC, donquixote commented on modules/oe_showcase_search/config/install/core.entity_view_display.node.oe_showcase_search_demo.teaser.yml
>    search_api_excerpt: true
Why commit noise in unrelated config files?
Ok to keep, just saying.

2022-06-07 13:24 UTC, donquixote submitted a review, later dismissed

2022-06-08 15:27 UTC, drishu submitted a review, later dismissed

2022-06-09 08:56 UTC, drishu submitted a review, later dismissed

2022-06-09 10:23 UTC, donquixote approved these changes

2022-06-09 10:38 UTC, drishu approved these changes

2022-06-09 10:39 UTC, merged