OEL-1543: Introduce oe_showcase_theme.
openeuropa/oe_showcase pull request #123
Opened 2022-05-10 21:05 UTC by donquixote

2022-05-13 19:07 UTC, brummbar requested changes
All is good, just watch out on rebase because the blocks "search exposed form" and "search results" are swapped in weight on 1.x.

2022-05-13 19:07 UTC, brummbar commented on themes/oe_showcase_theme/oe_showcase_theme.info.yml
> +# ThemeExtensionList::$defaults['regions'].
I'm conflicted if to ask to remove this or not. This is common knowledge, child themes don't inherit regions from parents.

2022-05-13 19:07 UTC, brummbar commented on themes/oe_showcase_theme/tests/src/Unit/IntegrityTest.php
> +    $whitelabel_info_file = dirname(__DIR__, 5) . '/build/themes/contrib/oe_whitelabel/oe_whitelabel.info.yml';
I know that we made the unit test for speed, but I'm not 100% convinced.
This could have been an existing site test, and we could use drupal api.
Ok to leave it for now, but if we ever need to update it we will convert it.

2022-05-13 19:07 UTC, brummbar commented on oe_showcase.post_update.php
> +  // have already been customized by a user / site builder.
This probably belongs more to the ticket itself rather than there.

2022-05-13 19:07 UTC, brummbar commented on themes/oe_showcase_theme/config/optional/block.block.oe_showcase_theme_search_form.yml
> +theme: oe_showcase_theme
Tiniest nit for this file, if I re-export it I get:
```
diff --git a/themes/oe_showcase_theme/config/optional/block.block.oe_showcase_theme_search_form.yml b/themes/oe_showcase_theme/config/optional/block.block.oe_showcase_theme_search_form.yml
index 7521552..2e861e7 100644
--- a/themes/oe_showcase_theme/config/optional/block.block.oe_showcase_theme_search_form.yml
+++ b/themes/oe_showcase_theme/config/optional/block.block.oe_showcase_theme_search_form.yml
@@ -21,10 +21,10 @@ settings:
   input:
     name: search_api_fulltext
     label: Search
-    classes: null
+    classes: ''
     placeholder: Search
   button:
-    classes: null
+    classes: ''
   view_options:
     enable_autocomplete: true
     id: showcase_search
```

2022-05-16 15:27 UTC, donquixote commented on themes/oe_showcase_theme/tests/src/Unit/IntegrityTest.php
> +    $whitelabel_info_file = dirname(__DIR__, 5) . '/build/themes/contrib/oe_whitelabel/oe_whitelabel.info.yml';
My philosophy here is that I want to test the raw code, not the emergent functionality.
In my book this is unit test material.
We can hard-code the location of the base theme because we know how composer works.

2022-05-16 22:22 UTC, donquixote commented on themes/oe_showcase_theme/oe_showcase_theme.info.yml
> +# ThemeExtensionList::$defaults['regions'].
I am going to replace with a simple one-liner.

2022-05-16 22:26 UTC, donquixote commented on oe_showcase.post_update.php
> +  // have already been customized by a user / site builder.
People looking at this code maybe won't have access to the ticket.

But I can remove it.

2022-05-16 23:09 UTC, donquixote commented on themes/oe_showcase_theme/config/optional/block.block.oe_showcase_theme_search_form.yml
> +theme: oe_showcase_theme
> All is good, just watch out on rebase because the blocks "search exposed form" and "search results" are swapped in weight on 1.x.

Not just that: We also have a new block.
I am adding weaving these changes into the existing history where they belong.

2022-05-17 12:03 UTC, brummbar commented on oe_showcase.post_update.php
> +  // have already been customized by a user / site builder.
Yes let's drop it.

2022-05-17 12:58 UTC, donquixote commented on oe_showcase.post_update.php
> +  // have already been customized by a user / site builder.
Done

2022-05-18 07:01 UTC, brummbar approved these changes, later dismissed

2022-05-18 11:32 UTC, drishu requested changes
Not to exagerate with buckets but think we should add content type related stuff in tempaltes/content, blocks related in templates/block, etc

Also, didn't look deep into it but found:
<img width="1001" alt="Screenshot 2022-05-18 at 14 01 07" src="https://user-images.githubusercontent.com/11507647/169029128-6ca408c6-dab2-4cc6-9a2c-69d9967fabff.png">
dono if related or not but I didn't see this in 1.x last time I checked.

2022-05-18 11:32 UTC, drishu commented on themes/oe_showcase_theme/oe_showcase_theme.info.yml
> +core_version_requirement: ^8.9 || ^9.1
think we can go for ^9.2

2022-05-18 11:32 UTC, drishu commented on themes/oe_showcase_theme/oe_showcase_theme.info.yml
> +screenshot: screenshot.png
screenshot is inherited

2022-05-31 21:42 UTC, donquixote commented on themes/oe_showcase_theme/tests/src/Unit/IntegrityTest.php
> +    $whitelabel_info_file = dirname(__DIR__, 5) . '/build/themes/contrib/oe_whitelabel/oe_whitelabel.info.yml';
Drupal API could verify that even after applying some crazy alter hooks (e.g. `hook_system_info_alter()`), regions are still the same. Right now I am not interested in that, I just want to compare the raw info.

2022-05-31 22:24 UTC, donquixote commented
> Also, didn't look deep into it but found: <img alt="Screenshot 2022-05-18 at 14 01 07" width="1001" src="https://user-images.githubusercontent.com/11507647/169029128-6ca408c6-dab2-4cc6-9a2c-69d9967fabff.png"> dono if related or not but I didn't see this in 1.x last time I checked.

Is this about the underline in the linked badges?
Seems ok now, they have standalone class.
And with new version of bcl it will change again.

2022-06-01 17:49 UTC, drishu approved these changes

2022-06-01 17:50 UTC, drishu commented
> > Also, didn't look deep into it but found: <img alt="Screenshot 2022-05-18 at 14 01 07" width="1001" src="https://user-images.githubusercontent.com/11507647/169029128-6ca408c6-dab2-4cc6-9a2c-69d9967fabff.png"> dono if related or not but I didn't see this in 1.x last time I checked.
> 
> Is this about the underline in the linked badges? Seems ok now, they have standalone class. And with new version of bcl it will change again.

No, it was about the sort being much lower, but now its fixed

2022-06-01 17:51 UTC, drishu commented on composer.lock
> +    "plugin-api-version": "2.3.0"
dont think we need these changes

2022-06-01 17:54 UTC, drishu approved these changes, later dismissed
We agreed to leave it like it is till we merge whitelabel, then we should drop composer and lock changes

2022-06-01 18:06 UTC, donquixote commented on composer.lock
> +    "plugin-api-version": "2.3.0"
I consistently get this on `composer update --lock`, but not sure why.

2022-06-07 16:40 UTC, brummbar submitted a review, later dismissed

2022-06-21 14:31 UTC, escuriola submitted a review, later dismissed

2022-06-24 11:23 UTC, drishu approved these changes, later dismissed

2022-06-24 20:25 UTC, brummbar approved these changes

2022-06-24 20:27 UTC, drishu approved these changes

2022-06-24 20:27 UTC, merged