OEL-1463: Update pager test assertions for first/last.
openeuropa/oe_showcase pull request #126
Opened 2022-05-12 13:17 UTC by donquixote

2022-05-12 14:39 UTC, drishu requested changes

2022-05-12 14:39 UTC, drishu commented on modules/oe_showcase_search/tests/src/ExistingSite/IntegrationTest.php
> +      $active_link = $pagination->find('css', 'li.active:last-child > a');
isn't it sufficient to call li.active to fetch the active link?

2022-05-12 14:39 UTC, drishu commented on modules/oe_showcase_search/tests/src/ExistingSite/IntegrationTest.php
> +      $last_link = NULL;
->find returns null if not found no ?
combined with above comment I think we can skip the if else and just grap the 2 things, then check for null or something

2022-05-12 14:39 UTC, drishu commented on modules/oe_showcase_search/tests/src/ExistingSite/IntegrationTest.php
> +    $get_page_index = static function (NodeElement $link): string {
I agree that I would have also put it in a helper function, named or not, both are fine for me here, but do try to stick to certain scenarios when using them:
1. when there is no reusability within your project/you use it only in that specific place
2. as value of a callable parameter

at least this is my compass for it

2022-05-12 14:40 UTC, donquixote commented on modules/oe_showcase_search/tests/src/ExistingSite/IntegrationTest.php
> +      $active_link = $pagination->find('css', 'li.active:last-child > a');
in this case the active and last link are identical. i want to verify that this is the case.

2022-05-12 14:52 UTC, drishu commented on modules/oe_showcase_search/tests/src/ExistingSite/IntegrationTest.php
> +      $active_link = $pagination->find('css', 'li.active:last-child > a');
you check the page index of the active link and then separately  for the last link, I dont see why you would care if its the same, but I wont insist, end result is the same so up 2 u

2022-05-12 16:02 UTC, drishu commented on modules/oe_showcase_search/tests/src/ExistingSite/IntegrationTest.php
> +  protected function assertPagerLinkPageNumber(int $expected, NodeElement $pager_link): void {
I would have expected a string and typecasted when sending the value but not a biggy

2022-05-12 16:02 UTC, drishu approved these changes, later dismissed

2022-05-14 15:57 UTC, donquixote commented on modules/oe_showcase_search/tests/src/ExistingSite/IntegrationTest.php
> +  protected function assertPagerLinkPageNumber(int $expected, NodeElement $pager_link): void {
I'd say semantically it is a number, and the `int` is more restrictive so gives a better idea what kind of value we expect.

2022-05-14 16:32 UTC, donquixote commented on modules/oe_showcase_search/tests/src/ExistingSite/IntegrationTest.php
> +      $active_link = $pagination->find('css', 'li.active:last-child > a');
I agree now.
My earlier motivation was that I don't fully trust the pager, and wanted to be sure the last item is really the last link with the icon, not a bug where the last link is missing for some reason. This is why I wanted to check labels _and_ link destination.
But we cannot reliably check this anyway. So now I drop the label checks.

2022-05-14 16:34 UTC, donquixote commented on modules/oe_showcase_search/tests/src/ExistingSite/IntegrationTest.php
> +  protected function assertPagerLinkPageNumber(int $expected, NodeElement $pager_link): void {
Also I wanted to get the typecast out of the calling code, e.g. no `(string) ($total - 1)`.

2022-05-16 09:11 UTC, drishu submitted a review, later dismissed

2022-05-16 10:02 UTC, escuriola submitted a review, later dismissed

2022-05-16 10:04 UTC, brummbar approved these changes, later dismissed

2022-05-16 10:08 UTC, donquixote commented
Pushed again, removed the commit in composer.json

2022-05-16 10:42 UTC, drishu approved these changes

2022-05-16 11:09 UTC, brummbar approved these changes

2022-05-16 11:17 UTC, merged