OEL-1573: Patch facets_form to fix conflict with oe_list_pages.
openeuropa/oe_showcase pull request #134
Opened 2022-05-18 17:25 UTC by donquixote

2022-05-19 06:26 UTC, drishu approved these changes

2022-05-19 06:50 UTC, escuriola submitted a review, later dismissed

2022-05-19 07:15 UTC, drishu requested changes
w8, I'll merge the facets upgrade soon, that will resolve this issue

2022-05-24 16:16 UTC, drishu commented on composer.json
>          "drupal/facets": "^1.8.0",
this had to be bumped up also, but its ok as it is resolved by https://github.com/openeuropa/oe_showcase/pull/131/files

2022-05-24 16:17 UTC, drishu commented
closing as fixed by https://github.com/openeuropa/oe_showcase/pull/131/files

2022-05-24 16:17 UTC, closed without merging