OEL-1614: Permissions and roles for pages and contact forms
openeuropa/oe_showcase pull request #135
Opened 2022-05-19 23:07 UTC by donquixote

2022-05-20 13:50 UTC, drishu requested changes
round 1

2022-05-20 13:50 UTC, drishu commented on tests/src/Traits/PathAccessTrait.php
> +declare(strict_types=1);
how did this pass phpcs ?

2022-05-20 13:50 UTC, drishu commented on config/install/user.role.manage_contact_forms.yml
> +  - 'administer contact forms'
the user has to know the urls by heart, lets add some permissions to view the admin pages, access toolbar

2022-05-20 13:50 UTC, drishu commented on config/install/user.role.manage_contact_forms.yml
> +  - 'view contact messages'
we also agreed that this role (and only this role) would have the "access site-wide contact form", this way after creating the form he/she can already view the form and embed once good and ready

2022-05-20 14:30 UTC, drishu submitted a review, later dismissed

2022-05-20 20:39 UTC, brummbar requested changes
I like the tests!

2022-05-20 20:39 UTC, brummbar commented on tests/src/Traits/PathAccessTrait.php
> +trait PathAccessTrait {
This trait contains path assertions, let's rename it accordingly:

```suggestion
trait AssertPathAccessTrait {
```

2022-05-20 20:39 UTC, brummbar commented on tests/src/Traits/PathAccessTrait.php
> +   * - Changes currently visited page.
This can be seen in the code easily. Let's drop all of these entries, also in the other methods.

2022-05-20 20:39 UTC, brummbar commented on tests/src/Traits/PathAccessTrait.php
> +    // Test editor.
```suggestion
    // Test the specified role.
```

2022-05-20 20:39 UTC, brummbar commented on tests/src/Traits/PathAccessTrait.php
> +    // Test editor.
Just as a note, it might be that in the future multiple roles can access a route, so we will have to change it.
Since we don't have such scenario now, let's leave this like it is now.

2022-05-20 20:48 UTC, donquixote commented on tests/src/Traits/PathAccessTrait.php
> +   * - Changes currently visited page.
A method name + doc comment should reflect how the method behaves to the outside.
If the name starts with `assert`, I would typically expect a pure method with no side effect.
This is not the case here, the behavior defies expectation for an assert method - this is worthwhile to mention in a  comment.
If you can propose a different name, I am ready to drop the comment :)

2022-05-20 20:51 UTC, donquixote commented on tests/src/Traits/PathAccessTrait.php
> +    // Test editor.
+1 for the comment fix.

> Just as a note, it might be that in the future multiple roles can access a route, so we will have to change it.
> Since we don't have such scenario now, let's leave this like it is now.

I was thinking the same.
We should change it based on an actual scenario, otherwise we risk to add a useless dimension of flexibility.

2022-05-23 08:08 UTC, brummbar commented on tests/src/Traits/PathAccessTrait.php
> +   * - Changes currently visited page.
Uhm let's keep it indeed.

2022-05-23 09:15 UTC, brummbar approved these changes

2022-05-23 09:17 UTC, drishu approved these changes

2022-05-23 09:30 UTC, merged