OEL-1618: Upgrade to BCL 0.23.0.
openeuropa/oe_showcase pull request #137
Opened 2022-05-20 10:44 UTC by escuriola

## OPENEUROPA-1618

### Description

[Insert description here]

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2022-06-01 22:01 UTC, donquixote commented
We must upgrade composer.lock or it won't work.

2022-06-01 22:02 UTC, donquixote commented
> We must upgrade composer.lock or it won't work.
```
docker-compose exec web composer update openeuropa/oe_whitelabel openeuropa/oe_bootstrap_theme
```
This also explains the failing test.

2022-06-01 22:56 UTC, donquixote commented
I notice we have some templates where we put custom hx elements with fw-bold class.
I found these by looking for "fw-bold" in the few templates we have in showcase.

```
modules/oe_showcase_page/templates/oe-webtools-social-share.html.twig
modules/oe_showcase_user_profile/templates/user--full.html.twig
```

In netlify these are not bold, from what I found.

TBD if we do this in a follow-up or here.

2022-06-03 16:06 UTC, donquixote commented
I still see fw-bold here.

2022-06-13 16:37 UTC, donquixote commented on modules/oe_showcase_user_profile/templates/user--full.html.twig
> +      } only %}
I suspect that h2 would be more consistent here. But netlify still has h3 on user profile page, so let's keep it like that.

2022-06-13 18:12 UTC, donquixote commented on modules/oe_showcase_page/templates/oe-webtools-social-share.html.twig
> +  } only %}
In netlify I find this, https://oelibrary.netlify.app/default/?path=/story/paragraphs-social-media-follow--default but it looks a bit different because it does not use webtools. Not sure if this is the right place to look.
In netlify this has h2, not h3.

2022-06-15 17:43 UTC, donquixote submitted a review, later dismissed

2022-06-22 12:58 UTC, brummbar requested changes

2022-06-22 12:58 UTC, brummbar commented on composer.json
> -                "Support Address field in country code processor": "https://patch-diff.githubusercontent.com/raw/openeuropa/oe_list_pages/pull/139.diff"
How come we are dropping this?

2022-06-22 12:58 UTC, brummbar commented on modules/oe_showcase_page/templates/oe-webtools-social-share.html.twig
> +  } only %}
Actually this was asked to be changed by UX and since we are here, let's replace it with a `<div class="fs-4 fw-semibold mb-3">`.

2022-06-24 14:55 UTC, drishu approved these changes

2022-06-24 15:50 UTC, brummbar approved these changes

2022-06-24 15:51 UTC, merged