OEL-1169: OE Webtools ETrans integration
openeuropa/oe_showcase pull request #142
Opened 2022-05-24 10:41 UTC by escuriola

## OPENEUROPA-1169

### Description

Enable oe_webtools_etrans module and block on the footer region

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2022-05-25 15:20 UTC, drishu requested changes
- the etrans should appear in the language switcher next to the dropdown
- we should override the template like here https://github.com/ec-europa/ewcms/blob/c054179566b25e6b80c4f063db83394e82c9d83e/themes/ewcms_theme/templates/monolingual-etrans-block.html.twig
- ideally it should appear only when a translation is not available

2022-05-25 15:20 UTC, drishu commented on modules/oe_showcase_multilingual/config/optional/block.block.openeuropa_webtools_etrans.yml
> +id: openeuropa_webtools_etrans
lets make it showcase_etrans

2022-05-25 15:20 UTC, drishu commented on modules/oe_showcase_multilingual/config/post_updates/00001_webtools_etrans/block.block.openeuropa_webtools_etrans.yml
> +id: openeuropa_webtools_etrans
showcase_etrans

2022-05-25 15:20 UTC, drishu commented on modules/oe_showcase_multilingual/tests/src/ExistingSiteJavascript/WebToolsEtransTest.php
> +    $this->clickLink('español');
just visit `$this->drupalGet('/es/node/' . $node->id());`

2022-05-25 15:20 UTC, drishu commented on modules/oe_showcase_multilingual/tests/src/ExistingSiteJavascript/WebToolsEtransTest.php
> +    // Assert excluded language after changing the current language.
what do you mean by excluded language?

2022-05-25 15:20 UTC, drishu commented on modules/oe_showcase_multilingual/tests/src/ExistingSiteJavascript/WebToolsEtransTest.php
> +    // Assert WebToolsEtrans Block is not visible out of a node.
```suggestion
    // Assert Etrans is not visible outside of nodes.
```
Something like this

2022-05-25 15:20 UTC, drishu commented on modules/oe_showcase_multilingual/tests/src/ExistingSiteJavascript/WebToolsEtransTest.php
> +    // Assert WebToolsEtrans Block exists if node and is placed in the footer.
```suggestion
    // Assert Etrans is loaded for nodes.
```

2022-05-25 15:20 UTC, drishu commented on modules/oe_showcase_multilingual/tests/src/ExistingSiteJavascript/WebToolsEtransTest.php
> +  }
Not sure about the test, we should revisit after these major changes

2022-05-30 20:20 UTC, drishu approved these changes, later dismissed

2022-06-07 18:57 UTC, brummbar requested changes
For me the link was unstyled, is it correct?
Maybe we should ask BAs and UX to place this slightly better.

2022-06-07 18:57 UTC, brummbar commented on composer.json
> +                "oe_webtools_etrans": "https://patch-diff.githubusercontent.com/raw/openeuropa/oe_webtools/pull/178.patch"
This has been merged into master, let's use that branch.

2022-06-07 18:57 UTC, brummbar commented on modules/oe_showcase_multilingual/oe_showcase_multilingual.module
> +  $node = \Drupal::routeMatch()->getParameter('node');
This is quite loose, the best would be to use the node context, but it's ok for now.

2022-06-07 18:57 UTC, brummbar commented on modules/oe_showcase_multilingual/oe_showcase_multilingual.module
> +    return AccessResult::neutral();
We are missing the cache context 'route'.

2022-06-07 18:57 UTC, brummbar commented on modules/oe_showcase_multilingual/oe_showcase_multilingual.module
> +  return AccessResult::forbidden();
A few things:

1. We should add the node as cache dependency. Everything works now, because the context adds it, but better to be explicit.
2. We should return forbidden if the translations are empty. Otherwise we should return neutral, and leave the applied contexts to determine the result. By returning allowed, we are saying "show it even if the context don't match". Again it's ok in this case, but better not to.

2022-06-07 18:57 UTC, brummbar commented on modules/oe_showcase_multilingual/tests/src/ExistingSite/WebToolsEtransTest.php
> +    $etrans_block = $page->find('css', 'main > div.container > div.row > div.col-12 > div#block-showcase-etrans');
```suggestion
    $etrans_block = $assert_session->elementExists('css', 'main > div.container > div.row > div.col-12 > div#block-showcase-etrans');
```
So we can drop the $page too.

2022-06-07 18:57 UTC, brummbar commented on modules/oe_showcase_multilingual/tests/src/ExistingSite/WebToolsEtransTest.php
> +
Unnecessary space.

2022-06-07 18:57 UTC, brummbar commented on modules/oe_showcase_multilingual/tests/src/ExistingSite/WebToolsEtransTest.php
> +
Unnecessary space.

2022-06-07 18:57 UTC, brummbar commented on modules/oe_showcase_multilingual/tests/src/ExistingSite/WebToolsEtransTest.php
> +    $this->markEntityTypeForCleanup('node');
Not needed. createNode() marks them already.

2022-06-16 20:28 UTC, donquixote commented on modules/oe_showcase_multilingual/oe_showcase_multilingual.module
> +  $node = \Drupal::routeMatch()->getParameter('node');
It will/would also match on node/*/edit pages or other node routes.
But I think this is excluded in the block visibility settings, and anyway these pages use the back-end theme.
So yeah seems ok for now.

2022-06-16 20:28 UTC, donquixote commented on modules/oe_showcase_multilingual/oe_showcase_multilingual.module
> +  return AccessResult::forbidden();
> We should return forbidden if the translations are empty.
I think you mean the opposite.

2022-06-16 20:32 UTC, donquixote approved these changes, later dismissed
Seems alright to me, but needs rebase and resolving of conflicts.
I am not going to merge it myself, I was not enough involved in the issue.
Also, I see

2022-06-16 20:32 UTC, donquixote commented on modules/oe_showcase_multilingual/config/post_updates/00001_webtools_etrans/block.block.showcase_etrans.yml
> +region: content
Issue said to put it in the footer.
But I assume this placement has been agreed on. If so then ok for me.

2022-06-16 20:32 UTC, donquixote commented on modules/oe_showcase_multilingual/config/post_updates/00001_webtools_etrans/block.block.showcase_etrans.yml
> +  include: 'main, .bcl-header'
I know this was requested in the issue summary.
To me it seems a bit strange that we make the translation dependent on the node translate status, but then we also translate the header.
But ok for me considering it has been decided like this.

2022-06-23 07:49 UTC, drishu requested changes

2022-06-23 07:49 UTC, drishu commented on composer.json
> +        "openeuropa/oe_webtools": "^1.17",
you changed the webtool version but this is not reflected in the lock;
also bump up to 1.18, the patch does not install anymore.

2022-06-23 16:30 UTC, drishu approved these changes

2022-06-23 16:37 UTC, brummbar approved these changes

2022-06-23 16:47 UTC, merged