OEL-1571: Improve Contact Forms testing.
openeuropa/oe_showcase pull request #143
Opened 2022-05-24 16:56 UTC by escuriola

## OPENEUROPA-1571

### Description

[Insert description here]

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2022-05-25 12:05 UTC, donquixote commented on modules/oe_showcase_contact_forms/tests/src/ExistingSite/ContactFormTest.php
> +namespace Drupal\Tests\oe_showcase_contact_forms;
Why?
We are in `/ExistingSite/` subdir, so this should also be reflected in the namespace.
Looks like the namespace was already fixed here, a5c64c6db430aa810abe4ebba84844836c4daed0

2022-05-25 12:13 UTC, donquixote commented on modules/oe_showcase_contact_forms/tests/src/ExistingSite/ContactFormTest.php
> +    $this->assertStringContainsString('Example Message text', $confirm_message->getText());
If we fully rely on ->getText(), we could call it once and have a local var that only contains the text, instead of a NodeElement.
```php
    $confirm_message = $page->find('css', 'div.alert.alert-success')->getText();
```

2022-05-25 12:14 UTC, donquixote commented on modules/oe_showcase_contact_forms/tests/src/ExistingSite/ContactFormTest.php
> +namespace Drupal\Tests\oe_showcase_contact_forms;
I notice the Jira issue says we should move it to `Drupal\\Tests\\oe_showcase_contact_forms`. This was wrong advice :)

2022-05-25 18:59 UTC, donquixote submitted a review, later dismissed

2022-05-31 15:49 UTC, donquixote approved these changes, later dismissed

2022-06-02 06:15 UTC, drishu requested changes

2022-06-02 06:15 UTC, drishu commented on modules/oe_showcase_contact_forms/tests/src/ExistingSite/ContactFormTest.php
> +    // Disable the flood limits for contact forms.
There are two good reasons to add a comment:
1) the code is unclear, obfuscated and need clarifications;
here we add a comment explaining what the code does.
2) the code is clear but the reason for adding it is not;
here we add a comment why we added the code, the reason/motivation.

Here we are in the second situation, what the code does is clear, but the reason for adding it is not:
```suggestion
    // Disable the flood limits to avoid submit failure when run multiple times.
```

2022-06-02 07:25 UTC, drishu submitted a review, later dismissed

2022-06-02 07:52 UTC, drishu approved these changes, later dismissed

2022-06-02 10:23 UTC, donquixote approved these changes

2022-06-02 10:52 UTC, drishu approved these changes

2022-06-02 10:53 UTC, merged