OEl-1652: Test Drupal upgrade paths
openeuropa/oe_showcase pull request #148
Opened 2022-05-31 16:01 UTC by drishu

## OEl-1652

### Description

Automate upgrade testing by leveraging 

### Change log

- Added: drone steps
- Changed: drone matrix

2022-05-31 16:08 UTC, drishu commented on .drone.yml
>          exclude: tag
not in scope, but was thinking, shouldn't we leave the install test to run when building a tag (so remove the exludes from install-branch, grumphp, and phpunit)?

2022-05-31 16:10 UTC, drishu commented on .drone.yml
> +  install-branch:
should we invest in a task that sets up the needed config in settings.php so we dont run the full site-install on the branch when in the update scenario ?

2022-06-07 13:35 UTC, escuriola approved these changes, later dismissed

2022-06-07 16:18 UTC, brummbar requested changes

2022-06-07 16:18 UTC, brummbar commented on .drone.yml
> +  include:
We don't need the include.

2022-06-07 17:02 UTC, brummbar approved these changes

2022-06-07 17:25 UTC, escuriola approved these changes

2022-06-07 17:27 UTC, merged