OEL-265: Initial commit for OE Showcase Page with basic configuration.
openeuropa/oe_showcase pull request #15
Opened 2021-09-23 08:31 UTC by GilNovacomm

## OPENEUROPA-[Insert ticket number here]

### Description

Create new showcase module oe_showcase_page

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2021-09-28 13:12 UTC, Maxfire submitted a review, later dismissed

2021-09-29 09:46 UTC, drishu requested changes

2021-09-29 09:46 UTC, drishu commented on modules/oe_showcase_page/oe_showcase_page.info.yml
> +  - drupal:field_ui
we don't need field_ui

2021-09-29 09:46 UTC, drishu commented on modules/oe_showcase_page/oe_showcase_page.info.yml
> +themes:
remove this, also from the other modules if present

2021-09-29 10:17 UTC, drishu approved these changes

2021-09-29 10:18 UTC, abel-santos-corral approved these changes

2021-09-29 10:38 UTC, merged