OEL-1677: Add location facet to events.
openeuropa/oe_showcase pull request #152
Opened 2022-06-06 07:34 UTC by drishu

## OEL-1677

### Description

Add location facet to events.

### Change log

- Added:
  - patch to fix country labels
  - patch to fix error in facet
  - location facet
  - enabled oe_list_pages_address
  - oe_sc_event_location to index
- Fixed: whitelabel package require

2022-06-07 16:01 UTC, donquixote requested changes
Seems ok, but we need to enhance the test case.
I also left some notes in the readme, but we can also improve it later.

2022-06-07 16:01 UTC, donquixote commented on modules/oe_showcase_list_pages/README.md
> +```
Maybe this part can be refined, but let's do this in OEL-1516.

2022-06-07 16:01 UTC, donquixote commented on modules/oe_showcase_list_pages/README.md
> +```composer log
Is 'composer log' a language recognized by github or some other markdown viewer?

2022-06-07 16:01 UTC, donquixote commented on modules/oe_showcase_list_pages/README.md
> +```
Blank lines are inconsistent..

2022-06-07 16:17 UTC, drishu commented on modules/oe_showcase_list_pages/README.md
> +```composer log
github suggested, but I'll change to json, is better

2022-06-08 12:49 UTC, donquixote commented on modules/oe_showcase_list_pages/tests/src/ExistingSite/ListPagesTest.php
> +    $location->selectOption('FR');
We should verify that country names are spelled out.
```suggestion
    $location->selectOption('France');
```

2022-06-08 16:04 UTC, escuriola approved these changes

2022-06-08 16:43 UTC, donquixote approved these changes

2022-06-08 17:12 UTC, merged