OEL-1675: News title facet should search in all fields.
openeuropa/oe_showcase pull request #153
Opened 2022-06-07 15:50 UTC by drishu

## OEL-1675

### Description

Requirements ask for it to be search in title, synopsis, and content.

The other way around for event, now that we add new fulltext fields, we need to make sure that it does not break the Event name search by searching in these new fields.

### Change log

- Added: fields body and oe_summary to the index
- Changed:
  - news title facet
  - event title facet
  - listed the new fields in the lowercase processors
  - adapted the tests

2022-06-07 20:20 UTC, donquixote requested changes
I think we should normalize the config changes via re-save + re-export.

2022-06-07 20:20 UTC, donquixote commented on modules/oe_showcase_list_pages/config/install/facets.facet.oelp_oe_sc_event__oe_sc_event_dates.yml
> +show_title: false
Noise?

2022-06-07 20:20 UTC, donquixote commented on modules/oe_showcase_list_pages/config/install/facets.facet.oelp_oe_sc_event__title.yml
> +    settings: {  }
The config files seem to have different levels or "normalization":
After re-save + re-export (drush cde), this one has noise, the others are clean.

For this issue, we should re-save and re-export all of the modified files for a clean slate.

For future issues, I like to do this "normalization" in a separate commit, so that the actual commits are cleaner. It can be done like this:
- In a first iteration just change everything as needed and commit all at once. This is because at this time we might not know yet which configs we want to change.
- Look at the diff to identify anything that looks like "noise".
- As a second iteration, use `git rebase -ir`, put a break at the start of the branch, then import or reinstall, re-save + re-export, commit only those files that we care about, then `git rebase --continue` to replay the other changes on top of it. Resolve conflicts by prefering the new version from REBASE_HEAD.
- We end up with a branch where the first commit(s) contain the noise, and the subsequent commit(s) are reduced to meaningful intentional changes.

2022-06-07 20:20 UTC, donquixote commented on modules/oe_showcase_list_pages/tests/src/ExistingSite/ListPagesTest.php
> +    $this->assertSearchResultsTitle('Event list page', 0);
I think I would use less generic words (fruit, animals etc) and make at least some of them unique per node and per field. But, I think it works fine, it is good enough.

We could also test search terms in shuffled order, repeated search terms, mix of uppercase / lowercase, combination of words from different fields. E.g. "10 introduction nUmber content introduction". This would fail if we change the processors configuration for the search index or the facets, or if we add a custom processor that behaves weirdly.

I think we don't want to cover the behavior of contrib modules, but there are enough things we can mess up on our side. E.g. if we get a new version of facets or search_api, but don't properly update our settings.

But I leave it to you if we want to do that extra step (perhaps one more test is enough to cover enough of it).

2022-06-07 20:20 UTC, donquixote commented on modules/oe_showcase_list_pages/config/install/facets.facet.oelp_oe_sc_news__title.yml
> +name: Keyword
I don't like "Keyword" for this, maybe "Search terms" is better?

2022-06-08 08:37 UTC, drishu commented on modules/oe_showcase_list_pages/config/install/facets.facet.oelp_oe_sc_event__oe_sc_event_dates.yml
> +show_title: false
yes

2022-06-08 08:40 UTC, drishu commented on modules/oe_showcase_list_pages/config/install/facets.facet.oelp_oe_sc_news__title.yml
> +name: Keyword
it used to be title, but requirements ask for keywords

2022-06-08 08:47 UTC, drishu commented on modules/oe_showcase_list_pages/config/install/facets.facet.oelp_oe_sc_event__title.yml
> +    settings: {  }
Sounds like spending extra time on something that is not worth it, can also introduce issues when solving the conflicts.
We should rather pay attention at each config change and make sure we understand the changes.

2022-06-08 08:48 UTC, drishu commented on modules/oe_showcase_list_pages/tests/src/ExistingSite/ListPagesTest.php
> +    $this->assertSearchResultsTitle('Event list page', 0);
More randomness is a good idea, but the shuffling of words will have to do for now

2022-06-08 09:13 UTC, drishu commented on modules/oe_showcase_list_pages/config/install/facets.facet.oelp_oe_sc_event__title.yml
> +    settings: {  }
I did go into more detail in the PR description though

2022-06-08 10:28 UTC, donquixote commented on modules/oe_showcase_list_pages/config/install/facets.facet.oelp_oe_sc_news__title.yml
> +name: Keyword
I did not see them, but ok.

2022-06-08 10:39 UTC, donquixote commented on modules/oe_showcase_list_pages/config/install/facets.facet.oelp_oe_sc_news__title.yml
> +name: Keyword
But then it would be "Keywords", not "Keyword"?
I was not able to find an explicit instruction for this in confluence.

2022-06-08 13:07 UTC, donquixote approved these changes

2022-06-08 15:21 UTC, escuriola approved these changes

2022-06-08 15:30 UTC, merged