OEL-1662: Add event registration url field
openeuropa/oe_showcase pull request #160
Opened 2022-06-21 12:27 UTC by escuriola

## OPENEUROPA-1662

### Description

Add event registration url field.

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2022-06-22 13:13 UTC, drishu requested changes

2022-06-22 13:13 UTC, drishu commented on tests/src/ExistingSite/ShowcaseExistingSiteCreateEventTest.php
> +    $assert_session->responseContains('Register');
cool, but lets assert also the target blank thing to assert that our formatter is used

2022-06-23 13:18 UTC, drishu submitted a review, later dismissed

2022-06-27 21:46 UTC, donquixote approved these changes
I think this one is good enough.
We don't override the config, so the tests from whitelabel cover the details.

2022-07-18 14:45 UTC, donquixote commented on tests/src/ExistingSite/ShowcaseExistingSiteCreateEventTest.php
> +    $assert_session->responseContains('Register');
This was done.

2022-07-18 14:46 UTC, donquixote submitted a review, later dismissed

2022-07-29 08:29 UTC, drishu approved these changes

2022-07-29 10:57 UTC, donquixote approved these changes

2022-07-29 10:58 UTC, merged