Prepare release 1.0.0-alpha5.
openeuropa/oe_showcase pull request #161
Opened 2022-06-22 15:19 UTC by drishu

## OPENEUROPA-[Insert ticket number here]

### Description

[Insert description here]

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2022-06-22 15:31 UTC, escuriola submitted a review, later dismissed

2022-06-22 15:32 UTC, brummbar requested changes
We shoudln't point to a temp release of oe_whitelabel.

2022-06-23 11:58 UTC, escuriola approved these changes

2022-06-23 13:21 UTC, brummbar approved these changes

2022-06-23 13:21 UTC, merged