OEL-1439: Project list pages.
openeuropa/oe_showcase pull request #163
Opened 2022-06-29 09:59 UTC by drishu

## OEL-1439

### Description

Add search api fields and facets needed for the project content type.

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2022-07-20 15:54 UTC, donquixote requested changes

2022-07-20 15:54 UTC, donquixote commented on modules/oe_showcase_list_pages/tests/src/ExistingSite/ListPagesTest.php
> +      'exposed_filters' => $exposed_filters,
I like this method. But let's simplify the `$exposed_filters` parameter.
Let it expect a simple array of strings, and then here we can call `array_combine($exposed_filters, $exposed_filters)`.
```suggestion
      'exposed_filters' => array_combine($exposed_filters, $exposed_filters),
```
See other comments above.

2022-07-20 15:54 UTC, donquixote commented on modules/oe_showcase_list_pages/tests/src/ExistingSite/ListPagesTest.php
> +      'oelp_oe_sc_event__oe_sc_event_dates' => 'oelp_oe_sc_event__oe_sc_event_dates',
Let's simplify the parameter, then here we can do this:
```suggestion
      'oelp_oe_sc_event__location',
      'oelp_oe_sc_event__title',
      'oelp_oe_sc_event__oe_sc_event_dates',
```
See my other comment below.

2022-07-20 15:54 UTC, donquixote commented on modules/oe_showcase_list_pages/tests/src/ExistingSite/ListPagesTest.php
> +      'oelp_oe_sc_news__oe_publication_date' => 'oelp_oe_sc_news__oe_publication_date',
Simplify as suggested in other comments below:
```suggestion
      'oelp_oe_sc_news__title',
      'oelp_oe_sc_news__oe_publication_date',
```

2022-07-20 15:54 UTC, donquixote commented on modules/oe_showcase_list_pages/tests/src/ExistingSite/ListPagesTest.php
> +    $this->drupalGet($list_page->toUrl());
Actually.. now we no longer use the UI to create these list pages. Is this good?
I agree we don't have to do this each time, but at least once, or not?
Why else do we log in as editor?

2022-07-20 15:54 UTC, donquixote commented on modules/oe_showcase_list_pages/tests/src/ExistingSite/ListPagesTest.php
> +      'title' => 'Results',
I think 'Results' is confusing as a node title here.
```suggestion
      'title' => 'Example list page',
```

2022-07-20 15:54 UTC, donquixote commented on modules/oe_showcase_list_pages/tests/src/ExistingSite/ListPagesTest.php
> +    $filter_form->findButton('Clear filters')->click();
```suggestion
    $filter_form->pressButton('Clear filters');
```
This way the IDE does not need to complain about "could be NULL".

2022-07-20 15:54 UTC, donquixote commented on modules/oe_showcase_list_pages/tests/src/ExistingSite/ListPagesTest.php
> +    $search_button = $filter_form->find('css', '#edit-submit');
We forgot one assertNotNull():
```suggestion
    $search_button = $filter_form->find('css', '#edit-submit');
    $this->assertNotNull($filter_status);
```
My IDE complains if a variable could be NULL..

2022-07-20 15:54 UTC, donquixote commented on modules/oe_showcase_list_pages/tests/src/ExistingSite/ListPagesTest.php
> +    $filter_form->findButton('Clear filters')->click();
It also throws an exception if the button is not found, which is good.

2022-07-20 15:55 UTC, donquixote commented on modules/oe_showcase_list_pages/tests/src/ExistingSite/ListPagesTest.php
> +    $this->drupalGet($list_page->toUrl());
Discuss in chat if needed.

2022-07-20 18:09 UTC, drishu commented on modules/oe_showcase_list_pages/tests/src/ExistingSite/ListPagesTest.php
> +      'exposed_filters' => $exposed_filters,
If we will ever want to do something like 
```
      'oelp_oe_sc_event__location' => 'oelp_oe_sc_event__location',
      'oelp_oe_sc_event__title' => 0,
      'oelp_oe_sc_event__oe_sc_event_dates' => 'oelp_oe_sc_event__oe_sc_event_dates',
```
we wont be able to, but for our test seems like an edge case, at least at this point, so ok for now, lets see what the future brings.

2022-07-20 19:17 UTC, drishu commented on modules/oe_showcase_list_pages/tests/src/ExistingSite/ListPagesTest.php
> +    $this->drupalGet($list_page->toUrl());
I yielded

2022-07-22 12:39 UTC, donquixote commented on modules/oe_showcase_list_pages/tests/src/ExistingSite/ListPagesTest.php
> +      'exposed_filters' => $exposed_filters,
Or we could skip that item in that case.
Although, the reason to include it would be to verify that all the options exist.

But for this we could also pass this instead:
```php
      'oelp_oe_sc_event__location' => TRUE,
      'oelp_oe_sc_event__title' => FALSE,
      'oelp_oe_sc_event__oe_sc_event_dates' => TRUE,
```

2022-07-22 12:57 UTC, donquixote approved these changes

2022-07-22 13:59 UTC, escuriola approved these changes

2022-07-22 14:52 UTC, merged