OEL-1516: Improve the README for oe_showcase_list_pages.
openeuropa/oe_showcase pull request #165
Opened 2022-07-04 20:25 UTC by donquixote

2022-07-04 21:18 UTC, donquixote commented on modules/oe_showcase_list_pages/README.md
> +  * In "Facet source", choose e.g. "List node:oe_sc_news", if the content type machine name is `oe_sc_news`.
Note: The labels of these facet sources are weird, and they are different on this "Add facet" page vs the facets overview page. Please confirm and tell me if I am wrong.

2022-07-05 11:37 UTC, drishu requested changes
Remove the oe_list_pages patch from the readme, it was merged and released, see https://github.com/openeuropa/oe_list_pages/releases/tag/0.18.0
so maybe in the required modules section specify the min version or in the composer json example I requested.

2022-07-05 11:37 UTC, drishu commented on modules/oe_showcase_list_pages/README.md
> +  * It is probably a good idea to have dedicated search indices for list pages and for regular site search.
Give instructions, not suggestions, so do this do that

2022-07-05 11:37 UTC, drishu commented on modules/oe_showcase_list_pages/README.md
> +* In the "Fields" tab, add the fields you need:
not the fields you need, rather mention that these fields will be the filters later on

2022-07-05 11:37 UTC, drishu commented on modules/oe_showcase_list_pages/README.md
> +  * In "Widget", it is recommended to choose one of the widgets provided by `oe_list_pages`, such as "List pages date", "List pages fulltext" or "List pages multiselect".
not recommended but mandatory

2022-07-05 11:37 UTC, drishu commented on modules/oe_showcase_list_pages/README.md
> +
we should mention that the caches might need to be flushed for the new facet source to appear in the facets page, so once you add a new content type to an existing index, a flush is needed to add facets later.

2022-07-05 11:37 UTC, drishu commented on modules/oe_showcase_list_pages/README.md
> +
I'd add here some json to exemplify

2022-07-05 11:37 UTC, drishu commented on modules/oe_showcase_list_pages/README.md
> +Modules:
Enable modules:

2022-07-05 14:35 UTC, donquixote commented on modules/oe_showcase_list_pages/README.md
> +
Not sure what kind of json to add. Snippets that would be added to "require" and "patches"?
I want to avoid adding explicit version numbers here, so that we don't have to update the README all the time.
Maybe I could just refer to the composer.json in showcase?

2022-07-05 14:36 UTC, donquixote commented on modules/oe_showcase_list_pages/README.md
> +Modules:
Not sure about this. Either we use a verb in both cases or never.
E.g. either "Require Composer packages" and "Install Drupal modules" or just "Composer packages" and "Drupal modules".

2022-07-05 14:49 UTC, donquixote commented on modules/oe_showcase_list_pages/README.md
> +  * It is probably a good idea to have dedicated search indices for list pages and for regular site search.
This section is meant for site builders, who need to figure out what works best for their project.
The sub-points here aim to give some hints about the strategy when planning multiple search indices for a website.

The problem of proper namespacing and reuse of different config entities (search index, facets, fields in a search index) came up when we created this configuration in showcase.

Another way to phrase this:

> Note: In OE Showcase, we decided to use the same search index for all list pages, but use distinct indices for site search or other purposes.

I could give this another shot now but perhaps we should first agree?

2022-07-05 14:52 UTC, donquixote commented on modules/oe_showcase_list_pages/README.md
> +* In the "Fields" tab, add the fields you need:
Well the fields are needed for facets, and then the facets become filters. Except for the "Content type" field which should always be added for multi content type support.

2022-07-05 15:08 UTC, donquixote commented on modules/oe_showcase_list_pages/README.md
> +  * In "Widget", it is recommended to choose one of the widgets provided by `oe_list_pages`, such as "List pages date", "List pages fulltext" or "List pages multiselect".
The other widgets won't work? Good to know.
I just tried and looked into the code, it seems they need to implement `ListPagesWidgetInterface`.

2022-07-05 15:17 UTC, donquixote commented on modules/oe_showcase_list_pages/README.md
> +
I mentioned cache and indexing process.

2022-07-05 15:19 UTC, donquixote commented
> Remove the oe_list_pages patch from the readme, it was merged and released, see https://github.com/openeuropa/oe_list_pages/releases/tag/0.18.0

The patch is still in the "patches" section in composer.json in showcase.
We should remove it there if we want to remove it from the README.

2022-07-05 15:47 UTC, donquixote commented
> > Remove the oe_list_pages patch from the readme, it was merged and released, see https://github.com/openeuropa/oe_list_pages/releases/tag/0.18.0
> 
> The patch is still in the "patches" section in composer.json in showcase. We should remove it there if we want to remove it from the README.

Let's fix this first: https://citnet.tech.ec.europa.eu/CITnet/jira/browse/OEL-1818

2022-07-05 15:52 UTC, donquixote commented on modules/oe_showcase_list_pages/README.md
> +
Let's fix https://citnet.tech.ec.europa.eu/CITnet/jira/browse/OEL-1818 first to get rid of patches.

2022-07-11 07:35 UTC, drishu commented on modules/oe_showcase_list_pages/README.md
> +  * It is probably a good idea to have dedicated search indices for list pages and for regular site search.
this "Note: We recommend to have one shared search index" is ok

2022-07-11 07:40 UTC, drishu commented on modules/oe_showcase_list_pages/README.md
> +
ok

2022-07-11 07:41 UTC, drishu commented on modules/oe_showcase_list_pages/README.md
> +Modules:
Its better now

2022-07-11 07:57 UTC, drishu submitted a review, later dismissed
I don't think we need the conclusions section but lets move on

2022-07-11 16:45 UTC, brummbar submitted a review, later dismissed
Looks good, the only step missing is to mark the search index to be used in list pages. It's a new option that was added in recent versions.

2022-07-11 23:41 UTC, donquixote commented
@brummbar 

> Looks good, the only step missing is to mark the search index to be used in list pages. It's a new option that was added in recent versions.

I added a step for this.
However, the README will now be incorrect until we actually udpate oe_list_pages to 0.18.1.

2022-07-11 23:55 UTC, donquixote commented
@drishu 

> I don't think we need the conclusions section but lets move on

I don't like the name "Conclusions" for this, I could not think of anything better.
The purpose of the section is to lead the reader back to "Instructions for content editors".

While writing I thought it a good idea to have "Instructions for content editors" before the "Instructions for site builders", because this illustrates the purpose and motivation of the module, it is the part that will happen repeatedly after initial configuration, and it is also the first thing people should check if they test-run showcase.
But this reversal is against the chronological order in which things would be done in a new project.

2022-07-13 08:20 UTC, drishu approved these changes

2022-07-13 08:21 UTC, escuriola approved these changes
Approved in behalf of @brummbar

2022-07-13 08:28 UTC, merged