OEL-1553: Person integration
openeuropa/oe_showcase pull request #166
Opened 2022-07-06 09:36 UTC by escuriola

## OPENEUROPA-1553

### Description

Person integration

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2022-07-10 12:51 UTC, brummbar requested changes

2022-07-10 12:51 UTC, brummbar commented on tests/src/ExistingSite/ShowcaseExistingSiteCreatePersonTest.php
> +class ShowcaseExistingSiteCreatePersonTest extends ShowcaseExistingSiteTestBase {
No need to put the prefix ShowcaseExistingSite, we said we would have to drop this from the other tests too.
And no need to write Create either.

```suggestion
class PersonContentTest extends ShowcaseExistingSiteTestBase {
```

2022-07-10 12:51 UTC, brummbar commented on tests/src/ExistingSite/ShowcaseExistingSiteCreatePersonTest.php
> +    $this->drupalLogin($user);
Just move this to the test method.

2022-07-10 12:51 UTC, brummbar commented on tests/src/ExistingSite/ShowcaseExistingSiteCreatePersonTest.php
> +    // Assert editors don't have permissions to create Person items.
This line is wrong. We are not logged in as editors, and editor MUST be able to edit persons. What are we asserting here?

2022-07-10 12:51 UTC, brummbar commented on themes/oe_showcase_theme/oe_showcase_theme.post_update.php
> +function oe_showcase_theme_post_update_00001(&$sandbox) {
Post updates for the profile should go in the profile. Themes don't have post updates.

2022-07-10 12:51 UTC, brummbar commented on tests/src/ExistingSite/ShowcaseExistingSiteCreatePersonTest.php
> + * Class to test Person content type on existing site tests.
We need to improve when we can on existing code and comments. There's no value in most of the text of this comment.
```suggestion
 * Tests the person content type.
```

2022-07-10 12:51 UTC, brummbar commented on oe_showcase.post_update.php
> +function oe_showcase_post_update_00011(): void {
This is missing the assigning of text formats to text fields. As editor I can access all formats now in all person related fields.

2022-07-11 10:44 UTC, escuriola commented on tests/src/ExistingSite/ShowcaseExistingSiteCreatePersonTest.php
> +class ShowcaseExistingSiteCreatePersonTest extends ShowcaseExistingSiteTestBase {
It's a good idea renaming now event and news tests  or should I create a follow up ticket to do?

2022-07-12 08:19 UTC, brummbar requested changes
Two minor remarks but it's good.

2022-07-12 08:19 UTC, brummbar commented on oe_showcase.post_update.php
> +  $field_names_by_text_format = [
It's not by text format anymore.

2022-07-12 08:19 UTC, brummbar commented on oe_showcase.post_update.php
> +  ]);
When we have to change one part inside only, we can first get the visibility config, set our missing value and then set it back with setVisibilityConfig().

2022-07-12 08:39 UTC, brummbar requested changes

2022-07-12 08:39 UTC, brummbar commented on modules/oe_showcase_list_pages/oe_showcase_list_pages.post_update.php
> +function oe_showcase_list_pages_post_update_00001(): void {
I just realised we cannot do this here:
![image](https://user-images.githubusercontent.com/8488617/178446307-1b19206f-62a1-4735-8690-a7c5de57a940.png)
By luck we don't have any dependency to the person in these configs, so no errors are thrown, otherwise this update would have failed.
Let's run this post update also in the profile itself.

2022-07-12 08:39 UTC, brummbar commented on oe_showcase.post_update.php
> + * Install and configure person. Grant permissions to editor.
Since we are moving the other post update content here, let's limit to "Install and configure person".

2022-07-12 08:39 UTC, brummbar commented on oe_showcase.post_update.php
> +    'oe_summary',
I actually don't think we should use full rich text here. Let's do like other fields and use simple_rich_text.

2022-07-14 23:42 UTC, donquixote requested changes

2022-07-14 23:42 UTC, donquixote commented on oe_showcase.post_update.php
> +  }
Now we set these text formats in post_update, but we don't set them through a field config yml?
It means if you install clean from latest version you don't get this config.

2022-07-14 23:42 UTC, donquixote commented on oe_showcase.post_update.php
> +  }
Note:
Interesting asymmetry of methods on the block class: The getter gets the complete visibility settings, but the setter only sets one specific entry.

2022-07-14 23:42 UTC, donquixote commented on oe_showcase.post_update.php
> +  if (isset($visibility['entity_bundle:node']['bundles'])) {
We use a condition here to cover the case that no other visibility settings are configured for node types.
But don't cover the case where the entire block placement is not existing (`$block === NULL`), perhaps because it was renamed.

It is all fine because we are in showcase and so we have a known target.
But still inconsistent.

@drishu Thoughts?

2022-07-15 15:17 UTC, drishu commented on tests/src/ExistingSite/ShowcaseExistingSiteCreatePersonTest.php
> +class ShowcaseExistingSiteCreatePersonTest extends ShowcaseExistingSiteTestBase {
Lets create a small ticket where we harmonize the test names

2022-07-15 15:54 UTC, drishu commented on tests/src/ExistingSite/PersonTest.php
> +    // Assert non editor user has no permissions to create Person items.
rather "Assert users without permission to create Person don't have access."

2022-07-15 15:54 UTC, drishu commented on oe_showcase.post_update.php
> +  if (isset($visibility['entity_bundle:node']['bundles'])) {
Post update is only for existing websites, so oesa for now, and we know oe_showcase_theme_social_share is there.

2022-07-18 07:47 UTC, drishu requested changes
Failed to execute git checkout 'b79a04ce88c46d7ab4ce047695ed7c3b10dfc279' -- && git reset --hard 'b79a04ce88c46d7ab4ce047695ed7c3b10dfc279' -- 

Check drone, I think composer lock needs to be updated

2022-07-18 07:47 UTC, drishu commented on tests/src/ExistingSite/PersonTest.php
> +
This is nice but in the list pages we also need to test the Person

2022-07-26 18:42 UTC, drishu approved these changes, later dismissed

2022-07-26 18:42 UTC, drishu commented on config/install/field.field.node.oe_sc_person.oe_sc_person_additional_info.yml
> +      - rich_text
I changed it form simple_rich_text

2022-07-26 18:42 UTC, drishu commented on modules/oe_showcase_list_pages/oe_showcase_list_pages.post_update.php
> + * Add project and person filters.
Had to make this change, the project filters are not released yet, so technically will be ok, reason is
```
DivisionByZeroError: Division by zero in Drupal\search_api\Task\TaskManager  
  ->processBatch() (line 370 of /test/oe_showcase/build/modules/contrib/searc  
  h_api/src/Task/TaskManager.php).
```

2022-07-27 15:33 UTC, donquixote approved these changes

2022-07-27 15:34 UTC, brummbar approved these changes

2022-07-27 15:34 UTC, merged