OEL-1761: Create administrator role
openeuropa/oe_showcase pull request #170
Opened 2022-07-13 11:05 UTC by escuriola

## OPENEUROPA-1761

### Description

Create new administrator admin role.

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2022-07-14 15:52 UTC, drishu requested changes
Looks good, just one more thing, at a minimum we should assert in AuthorisationTest that a user with this role can access the stuff that only an admin should/could

2022-07-18 07:54 UTC, drishu requested changes

2022-07-18 07:54 UTC, drishu commented on tests/src/ExistingSite/AuthorisationTest.php
> +      '/node/add',
we need more stuff here like the permissions page, the roles page, managing entities like content types, structure blocks, block config, etc.. all the pages we need to have access to when we assert a deployment.

2022-07-18 10:25 UTC, drishu commented on tests/src/ExistingSite/AuthorisationTest.php
> +      'admin/people/roles',
a slash is missing here, but its fine, fix only if next reviewer has more feedback

2022-07-18 10:25 UTC, drishu submitted a review, later dismissed

2022-07-19 13:00 UTC, donquixote requested changes

2022-07-19 13:00 UTC, donquixote commented on tests/src/ExistingSite/AuthorisationTest.php
> +   * Authenticated user cannot access restricted pages.
Currently this comment does not describe what the test does.
We are only testing that the admin role _can_ access these pages, not that authenticated role _cannot_.

### Option 1:
Only change the comment to describe what the method currently does.
```suggestion
   * Tests that the administrator can see restricted administration pages.
```

### Option 2:
Add checks to verify that authenticated and anonymous cannot see these pages.
Modify the comment accordingly:
```suggestion
   * The administrator can see pages that authenticated users or anonymous cannot.
```

### Option 3:
Modify the code to check which roles can access which of the admin pages.
E.g. `/admin` can be seen by 'administrator' and by 4 other roles.
Modify the comment accordingly.
This would require to further modify the methods in `AssertPathAccessTrait`, more than I am comfortable to ask for in this PR.

Imo let's go for option 2.

2022-07-19 13:00 UTC, donquixote commented on tests/src/ExistingSite/AuthorisationTest.php
> +      '/admin',
Just as an observation, there are 4 other roles that can see `'/admin'`:
- 'configure_page_feedback_form', 
- 'manage_contact_forms'
- 'editor'
- 'manage_users'.

Other paths are accessible by fewer roles.

But let's ignore this for now, we might do a follow-up to improve these tests.

2022-07-19 13:00 UTC, donquixote commented on config/install/user.role.administrator.yml
> +permissions: {  }
We should add the entry in oe_showcase.info.yml `config_devel/install`.

2022-07-19 13:00 UTC, donquixote commented on tests/src/ExistingSite/AuthorisationTest.php
> +      'admin/people/roles',
Pls add the slash, it hurts to see :)

2022-07-19 13:00 UTC, donquixote commented on tests/src/ExistingSite/AuthorisationTest.php
> +      '/node/add/oe_showcase_page',
Please sort this list alphabetically.

2022-07-19 13:00 UTC, donquixote commented on tests/src/ExistingSite/AuthorisationTest.php
> +    }
If we go for option 2, we would now check that anonymous and authenticated cannot see these paths.
We can use the `->assertPathsResponseCode()` to avoid repeating the loop, and to have more specific failure messages.

2022-07-19 13:00 UTC, donquixote commented on tests/src/ExistingSite/AuthorisationTest.php
> +   * Authenticated user cannot access restricted pages.
@drishu Disagree?

2022-07-19 13:29 UTC, donquixote commented on tests/src/Traits/AssertPathAccessTrait.php
> +    unset($all_roles['authenticated'], $all_roles['administrator']);
In a follow-up, we could also test that administrator can see these paths.
But let's skip it for now.

2022-07-19 13:49 UTC, drishu commented on tests/src/ExistingSite/AuthorisationTest.php
> +   * Authenticated user cannot access restricted pages.
option 1

2022-07-19 13:49 UTC, drishu commented on config/install/user.role.administrator.yml
> +permissions: {  }
good catch

2022-07-19 14:17 UTC, donquixote commented on tests/src/ExistingSite/AuthorisationTest.php
> +   * Authenticated user cannot access restricted pages.
So.. @drishu seems to be ok with option 1.
In that case, just change the comment.

2022-07-19 14:20 UTC, escuriola commented on tests/src/ExistingSite/AuthorisationTest.php
> +   * Authenticated user cannot access restricted pages.
I chose option 1 for now after reading the chat discussion. We can create a follow-up ticket if you want to improve it @donquixote.

2022-07-19 14:20 UTC, escuriola commented on tests/src/ExistingSite/AuthorisationTest.php
> +      '/admin',
Not implemented right now, as you said, we can create a follow-up if we want to improve the test

2022-07-19 14:21 UTC, escuriola commented on tests/src/ExistingSite/AuthorisationTest.php
> +    }
Not implemented because option 1 is chosen

2022-07-19 14:22 UTC, escuriola commented on tests/src/Traits/AssertPathAccessTrait.php
> +    unset($all_roles['authenticated'], $all_roles['administrator']);
Ok, not implemented.

2022-07-19 14:33 UTC, donquixote commented on oe_showcase.info.yml
> +    - user.role.administrator
Alphabetic order!
```suggestion
    - user.role.administrator
    - user.role.anonymous
```

2022-07-19 14:48 UTC, donquixote approved these changes

2022-07-19 14:49 UTC, donquixote commented
Ok for me now.
The one comment from @drishu I left open. I assume that now we have enough paths, but maybe we want more?
For my taste we should go with what we have now.

2022-07-19 15:50 UTC, drishu approved these changes

2022-07-20 08:50 UTC, merged