OEL-1775: Enable social media follow in basic page.
openeuropa/oe_showcase pull request #171
Opened 2022-07-14 11:38 UTC by escuriola

## OPENEUROPA-[Insert ticket number here]

### Description

[Insert description here]

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2022-07-18 12:41 UTC, drishu requested changes

2022-07-18 12:41 UTC, drishu commented on modules/oe_showcase_page/oe_showcase_page.post_update.php
> +function oe_showcase_page_post_update_00001(&$sandbox) {
```suggestion
function oe_showcase_page_post_update_00001(&$sandbox): void {
```
we dont specify return type only if its mixed, and only as long as we support php smaller than 8

2022-07-19 13:13 UTC, drishu submitted a review, later dismissed

2022-07-20 14:38 UTC, donquixote approved these changes, later dismissed

2022-07-20 14:38 UTC, donquixote commented on modules/oe_showcase_page/oe_showcase_page.post_update.php
> +  $settings['target_bundles']['oe_social_media_follow'] = 'oe_social_media_follow';
We could sort these to avoid noise later on.
But I don't think we need to. Let's ignore.

2022-07-22 09:05 UTC, drishu approved these changes

2022-07-22 12:13 UTC, donquixote approved these changes

2022-07-22 12:14 UTC, merged