OEL-1650: Add Event type.
openeuropa/oe_showcase pull request #177
Opened 2022-08-01 17:58 UTC by drishu

## OEL-1650

### Description

Add Event type.

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2022-08-03 13:39 UTC, drishu commented on config/install/search_api.index.oe_list_pages_index.yml
>    config:
had to move this file here to fix install process, dont like it.. I'd rather have an oe_showcase_content module that the list_pages one can depend on and than put this back.

2022-08-03 13:39 UTC, drishu commented on modules/oe_showcase_list_pages/oe_showcase_list_pages.post_update.php
> +    'facets.facet.oelp_oe_sc_event__location',
these where added for their weight update

2022-08-03 13:39 UTC, drishu commented on oe_showcase.post_update.php
> +    'facets.facet.oelp_oe_sc_event__type',
had to make a judgement call here, can't do it in list_pages because of dependency chain but also didn't want to move/mix the scope of the list_pages update 00001_filters into this one.

2022-08-03 13:39 UTC, drishu commented on tests/src/ExistingSite/EventTest.php
> +    $assert_session->elementContains('css', 'a[target="_blank"]', 'Register');
registration url implementation changed

2022-08-05 14:50 UTC, drishu commented on config/install/search_api.index.oe_list_pages_index.yml
>    config:
we discussed to not put in the extra effort.

2022-08-05 17:10 UTC, brummbar requested changes

2022-08-05 17:10 UTC, brummbar commented on themes/oe_showcase_theme/templates/node/node--oe-sc-event--teaser.html.twig
> +    outline: true,
This is already added in the pattern, so not strictly necessary.

2022-08-05 17:10 UTC, brummbar commented on themes/oe_showcase_theme/templates/node/node--oe-sc-event--oe-w-content-banner.html.twig
> +    outline: true,
See below comment.

2022-08-05 17:10 UTC, brummbar commented on tests/src/ExistingSite/EventTest.php
> +    $this->drupalGet('admin/structure/taxonomy/manage/event_type/add');
Shouldn't we use \Drupal\Tests\oe_showcase\Traits\AssertPathAccessTrait::assertPathsRequireRole(), so that we test all roles at once.

2022-08-05 17:10 UTC, brummbar commented on themes/oe_showcase_theme/templates/node/node--oe-sc-event--teaser.html.twig
> +{% block content %}
Not strictly needed to redefine here a block.

2022-08-05 17:10 UTC, brummbar commented on themes/oe_showcase_theme/templates/node/node--oe-sc-event--teaser.html.twig
> +  ],
```suggestion
  ]|filter(element => element is not empty),
```
Noticed that this is wrong also in whitelabel from the original template. Let's start fixing it in here.

2022-08-05 17:10 UTC, brummbar commented on config/install/field.storage.node.field_event_type.yml
> +field_name: field_event_type
Conflicted about the name, should we keep field_ or change it?

2022-08-05 17:10 UTC, brummbar commented on modules/oe_showcase_list_pages/config/install/facets.facet.oelp_oe_sc_event__type.yml
> +langcode: en
This is rendered as multivalue select, is it correct?

2022-08-05 17:10 UTC, brummbar commented on modules/oe_showcase_list_pages/oe_showcase_list_pages.post_update.php
> -function oe_showcase_list_pages_post_update_00001() {
Uhm this was already present in alpha6, so we shouldn't remove it.

2022-08-08 07:29 UTC, drishu commented on modules/oe_showcase_list_pages/oe_showcase_list_pages.post_update.php
> -function oe_showcase_list_pages_post_update_00001() {
don't think so https://github.com/openeuropa/oe_showcase/tree/1.0.0-alpha6/modules/oe_showcase_list_pages

2022-08-08 07:32 UTC, drishu commented on modules/oe_showcase_list_pages/config/install/facets.facet.oelp_oe_sc_event__type.yml
> +langcode: en
It' not, but we don't have the single select widget yet (was out of scope for this issue), we do have a ticket to create it, so once we have that we will update all filters that need it

2022-08-08 07:32 UTC, drishu commented on config/install/field.storage.node.field_event_type.yml
> +field_name: field_event_type
so was I, the other local tax field I also named field_ so I went for it

2022-08-08 07:58 UTC, drishu commented on themes/oe_showcase_theme/templates/node/node--oe-sc-event--teaser.html.twig
> +{% block content %}
true

2022-08-08 11:33 UTC, brummbar commented on modules/oe_showcase_list_pages/oe_showcase_list_pages.post_update.php
> -function oe_showcase_list_pages_post_update_00001() {
¯\_(ツ)_/¯

2022-08-08 12:16 UTC, merged