Oel 1914
openeuropa/oe_showcase pull request #186
Opened 2022-08-30 15:10 UTC by drishu

## OPENEUROPA-[Insert ticket number here]

### Description

[Insert description here]

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2022-09-01 15:43 UTC, brummbar requested changes
I've noticed one problem with the bcl carousel template. No caption title will be rendered if no caption is entered. We need to check where this should be fixed. If we should make the caption mandatory on our side, or fix the template, or add some states to make it required when other fields are filled.

2022-09-01 15:43 UTC, brummbar commented on config/post_updates/00019_carousel/field.field.node.oe_showcase_page.field_body.yml
> +      contact_form:
Let's keep these entries sorted alphabetically, it looks like carousel is the only one is not in the dropdown.

2022-09-01 15:43 UTC, brummbar commented on modules/oe_showcase_page/tests/src/ExistingSite/PageTest.php
> +    $media_2 = $this->createImageMedia(['name' => 'Second image']);
It's already tested, but why not use an avportal image here.

2022-09-01 15:43 UTC, brummbar commented on modules/oe_showcase_page/tests/src/ExistingSite/PageTest.php
> +      'field_body[8][subform][field_oe_carousel_items][0][subform][field_oe_title][0][value]',
We are never testing that the title is optional.

2022-09-01 15:43 UTC, brummbar commented on modules/oe_showcase_page/tests/src/ExistingSite/PageTest.php
> +    $assert_session->pageTextContains('Carousel item 1');
We should use the pattern assertion here too.

2022-09-02 14:08 UTC, drishu commented on modules/oe_showcase_page/tests/src/ExistingSite/PageTest.php
> +      'field_body[8][subform][field_oe_carousel_items][0][subform][field_oe_title][0][value]',
implemented for the second item

2022-09-05 14:50 UTC, brummbar approved these changes

2022-09-05 14:50 UTC, merged