OEL-1910: Drupal 9.4 support.
openeuropa/oe_showcase pull request #189
Opened 2022-09-27 10:38 UTC by drishu

## OPENEUROPA-[Insert ticket number here]

### Description

[Insert description here]

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2022-09-30 15:23 UTC, drishu reviewed
rest of them are 9.4 comp bumps of our modules

2022-09-30 15:23 UTC, drishu commented on composer.json
> +        "drupal/honeypot": "^2.0.2",
this specific version is a oe_contact_forms requirement

2022-09-30 15:23 UTC, drishu commented on composer.json
> +        "drupal/ctools": "^3.11",
this fixes a a major bug, see the readme

2022-09-30 15:23 UTC, drishu commented on composer.json
> -        "openeuropa/oe_media": "^1.14",
I removed oe_media as its a dependency of oe_content, maybe I should have left the explicit require, not sure, but its not listed as a direct req of our modules

2022-09-30 19:20 UTC, brummbar requested changes

2022-09-30 19:20 UTC, brummbar commented on composer.json
>                  "Incorrect label in taxonomy glossary for terms that start with zero @see https://www.drupal.org/project/drupal/issues/3291520": "patches/3291520-9.3.x.patch"
This we can drop it and use https://www.drupal.org/files/issues/2022-08-01/3291520-12.patch

2022-10-03 11:28 UTC, brummbar approved these changes

2022-10-03 11:30 UTC, merged