OEL-1414: Integrate OE List Page sort.
openeuropa/oe_showcase pull request #195
Opened 2022-10-13 09:34 UTC by drishu

## OPENEUROPA-[Insert ticket number here]

### Description

[Insert description here]

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2022-10-21 13:29 UTC, brummbar requested changes

2022-10-21 13:29 UTC, brummbar commented on modules/oe_showcase_list_pages/src/EventSubscriber/ListPagesSubscriber.php
> +            'oe_sc_event_dates' => 'Date',
Is the sorting direction omitted on purpose in here? Because the code doesn't seem to account for it. It works, but it gets into the url as null.

2022-10-24 08:16 UTC, drishu commented on modules/oe_showcase_list_pages/tests/src/ExistingSiteJavascript/ListPagesTest.php
> +    $role->revokePermission('access toolbar');
Heads up, the maximize window was not cutting it anymore, I've also tried hieding the toolbar via js, same result, element overlap, so I had to do this.

2022-10-24 08:16 UTC, drishu commented on modules/oe_showcase_list_pages/tests/src/ExistingSiteJavascript/ListPagesTest.php
> +    $this->scrollIntoView('#edit-reset');
I've added these extra test cases, and noticed that the order for the budget is actually sorted as string, not as number, can be fixed only when we have a "number" widget in oe_list_pages (as far as I can see)

2022-10-28 11:55 UTC, brummbar approved these changes

2022-10-28 11:55 UTC, merged