OEL-1990: Fix allowed formats in formatted text fields.
openeuropa/oe_showcase pull request #196
Opened 2022-10-14 16:10 UTC by drishu

## OEL-1990

### Description

Fix allowed formats in formatted text fields.

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2022-10-18 09:00 UTC, drishu commented on tests/src/Traits/WysiwygTrait.php
> +    $parent = $this->getParentByAttribute($field, 'class', 'text-format-wrapper');
I've tried all sorts of xpath but it's not finding my element wrapper

2022-10-18 09:03 UTC, drishu commented on tests/src/Traits/TraversingTrait.php
> +      if (!$parent instanceof NodeElement) {
just in case, but from my tests it doesn't happen, instead it would go into an infinite loop where I to use a while loop

2022-11-10 13:36 UTC, brummbar requested changes

2022-11-10 13:36 UTC, brummbar commented on oe_showcase.post_update.php
> +    $field_instance->setThirdPartySetting('allowed_formats', 'allowed_formats', ['rich_text']);
This is not as straightforward as it seems. When you have existing content, this happens:

![image](https://user-images.githubusercontent.com/8488617/200895560-252f030c-31e3-461a-a676-e126ad6c1b37.png)

What we need to follow a similar approach to this PR https://github.com/ec-europa/ewcms/pull/805/files#diff-87cdcb75ea06e72dd3577cd72f428924eba5569fd8f50d86438a0ebc69de450eR4481
Basically:

- the config contains only the allowed values;
- for updated websites, we allow both formats for existing content;
- when an existing content is updated, we add validation to enforce changing to the correct format.

I think we can drop the part with the install task that makes fresh and existing installs in the same state.

2022-11-10 13:36 UTC, brummbar commented on tests/src/Traits/TraversingTrait.php
> +  protected function getParentByAttribute(NodeElement $element, string $attribute, string $value, int $depth = 5) {
I would drop this method, we can use an xpath to get a parent.
`$field->find('xpath', '/ancestor::div[@class and contains(concat(" ", normalize-space(@class), " "), " text-format-wrapper ")]')`

2022-11-10 13:36 UTC, brummbar commented on tests/src/Traits/WysiwygTrait.php
> +  protected function assertFieldHasFormat(NodeElement $field, string $format): void {
So the difference between these two functions is that one asserts that a format is set, while the other asserts the format description, correct?
Unfortunately from the name it's not very clear.
Let's use [oe_editorial](https://github.com/openeuropa/oe_editorial/blob/master/oe_editorial.module#L27) so that we have the link changed to reflect which format we have. Then we can assert on that one.
I would remove these methods for now and just have one method which returns the format used for a field.
Look at what we can reuse from wysiwyg trait in ewpp. Also let's keep out assertions from traits without assert in the name. Better to just return the format.

2022-11-10 13:36 UTC, brummbar commented on tests/src/ExistingSite/PersonTest.php
> +    $this->assertFieldHasWysiwyg($field, 'rich_text');
Basically with the comments below/above this becomes
```suggestion
    $this->assertEquals('rich_text', $this->getWysiwigTextFormat($field));
```

2022-11-15 19:26 UTC, drishu commented on tests/src/Traits/WysiwygTrait.php
> +  protected function assertFieldHasFormat(NodeElement $field, string $format): void {
the ewcms wysiwyg trait doesn't help us here, this is how its done there https://github.com/ec-europa/ewcms/blob/4e6baee6b8cc859ab16e3beaaaf436e44e047b9f/tests/Behat/DrupalContext.php#L2351, found this after you pointed me to the oe_editorial alter

2022-11-15 19:31 UTC, drishu commented on oe_showcase.post_update.php
> +    $field_instance->setThirdPartySetting('allowed_formats', 'allowed_formats', ['rich_text']);
"the config contains only the allowed values" if you mean only rich text without the full_html then I dont like it cuz the update should match the install. Regarding the install task I agreed we dont need it, having the same allowed formats in both install and update takes care of that.

2022-12-08 17:17 UTC, brummbar requested changes

2022-12-08 17:17 UTC, brummbar commented on oe_showcase.profile
> +}
We are missing one scenario which is the text field for timeline items. It's a custom one so we need a hook

```
/**
 * Implements hook_field_widget_WIDGET_TYPE_form_alter().
 */
function oe_showcase_field_widget_timeline_widget_form_alter(&$element, FormStateInterface $form_state, $context) {
  // Bail out if it's a default value widget.
  if ($context['default']) {
    return;
  }

  if (!isset($element['body']['#format'])) {
    return;
  }
  // Force Simple rich text format for timeline body.
  $element['body']['#format'] = 'rich_text';
}
```

2022-12-08 17:17 UTC, brummbar commented on oe_showcase.post_update.php
> + * @see https://github.com/ec-europa/ewcms/blob/develop/post_updates/ewcms_post_update_200.inc#L2096
Let's move this link from here as it generates a bit of noise when running updb.

2022-12-09 17:35 UTC, brummbar approved these changes

2022-12-09 17:35 UTC, merged