OEL-2107: Added styles for gallery modal.
openeuropa/oe_showcase pull request #201
Opened 2022-11-11 09:09 UTC by tibi2303

## OPENEUROPA-[Insert ticket number here]

### Description

[Insert description here]

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2022-11-11 17:37 UTC, brummbar requested changes, later dismissed
I would like to have a few improvements:

- remove a bit of borders, they are a bit everywhere:
![image](https://user-images.githubusercontent.com/8488617/201397018-ecc1bd10-6c39-496b-8c87-471c135663b0.png)
Let's keep them only around.
- I pushed an update to the image style so the ratio is kept in all tabs. I'd like it looks like more like this
![image](https://user-images.githubusercontent.com/8488617/201397142-a0b392ef-f360-4eca-a787-f84c8afaca8b.png)
- let's also add this interaction
https://user-images.githubusercontent.com/8488617/201397222-20077784-bf4d-4062-9075-41fadeabd04a.mov
You can find some of these styles here build/core/themes/seven/css/theme/media-library.css
If you need help to have a live demo tell me.

2022-11-14 14:00 UTC, tibi2303 commented
@brummbar 
<img width="545" alt="image" src="https://user-images.githubusercontent.com/36895476/201678937-46240377-2732-4835-a59e-97bfa089762d.png">


I pushed now the changes, on my side it look like that, the left one has the hover effect.

2022-12-05 07:58 UTC, drishu commented on oe_showcase.post_update.php
> +  ConfigImporter::importSingle('profile', 'oe_showcase', '/config/post_updates/00023_media_library', 'image.style.media_entity_browser_thumbnail');
I know why this time it's `00023_media_library` but I think we should name it `00022_media_library`

2022-12-09 09:33 UTC, drishu approved these changes

2022-12-09 09:35 UTC, merged