OEL-543: Styling components
openeuropa/oe_showcase pull request #21
Opened 2021-10-07 07:16 UTC by escuriola

Jira issue:

https://citnet.tech.ec.europa.eu/CITnet/jira/browse/OEL-543

2021-10-07 15:47 UTC, escuriola commented on modules/oe_showcase_search/oe_showcase_search.module
> +  if ($form['sort_bef_combine']['#context']['#display_id'] === 'showcase_search_page') {
Missing isset to avoid warnings
```suggestion
  if (isset($form['sort_bef_combine']['#context']['#display_id']) &&  $form['sort_bef_combine']['#context']['#display_id'] === 'showcase_search_page') {
```

2021-10-08 09:38 UTC, abel-santos-corral submitted a review, later dismissed
Reviewed. Checked that all changes required at ticket were on place on the form at search page.

2021-10-11 11:28 UTC, drishu requested changes

2021-10-11 11:28 UTC, drishu commented on modules/oe_showcase_search/config/install/core.entity_view_display.node.oe_showcase_search_demo.search_result.yml
> +      trim_length: 500
still a bit long, lets drop to 350

2021-10-11 11:28 UTC, drishu commented on modules/oe_showcase_search/oe_showcase_search.module
> +function oe_showcase_search_form_views_exposed_form_alter(&$form, FormStateInterface $form_state, $form_id) {
We need a reusable solution that we can offer in oe_whitelabel, so:

- since we use BEF lets create a new sort plugin
- in oe_whitelabel_helper add a  src/Plugin\better_exposed_filters\sort\FloatEndSortWidget.php
- this will extend DefaultWidget
- override exposedFormAlter
- add `$form['#attributes']['class'][] = 'float-lg-end';
    $form['#attributes']['class'][] = 'd-md-block';`
- edit the view, use the new BEF plugin and export `drush cde oe_showcase_search`

2021-10-15 14:18 UTC, drishu requested changes

2021-10-15 14:18 UTC, drishu commented on modules/oe_showcase_search/oe_showcase_search.module
> +function oe_showcase_search_form_facets_form_alter(&$form, FormStateInterface $form_state, $form_id) {
the form alter is perfect now like this, but move it back to whitelabel

2021-10-18 18:23 UTC, drishu approved these changes

2021-10-19 06:21 UTC, Maxfire approved these changes

2021-10-19 06:21 UTC, merged