OEL-1574: Enable slim_select.
openeuropa/oe_showcase pull request #210
Opened 2023-01-13 07:49 UTC by drishu

## OEL-1574

### Description

[Insert description here]

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2023-01-19 14:47 UTC, brummbar requested changes

2023-01-19 14:47 UTC, brummbar commented on modules/oe_showcase_list_pages/tests/src/ExistingSiteJavascript/ListPagesTest.php
> +    $slim_select = $field->getParent()->find('css', 'div.ss-main');
I think this should fit in a trait?

2023-01-19 14:47 UTC, brummbar commented on modules/oe_showcase_list_pages/tests/src/ExistingSiteJavascript/ListPagesTest.php
> +    $this->getSession()->wait(1000);
Uhm we should wait until an element is visible, like `.ss-list`.
Then we can wait until the `.ss-values` element contains an entry with the option selected.

2023-01-19 14:48 UTC, drishu commented on modules/oe_showcase_list_pages/tests/src/ExistingSiteJavascript/ListPagesTest.php
> +    $this->getSession()->wait(1000);
you'r right sorry, got lazy and copy pasted

2023-02-03 12:43 UTC, brummbar approved these changes

2023-02-03 12:43 UTC, merged