OEL-2163: Content news required.
openeuropa/oe_showcase pull request #212
Opened 2023-01-17 16:07 UTC by tibi2303

## OPENEUROPA-[Insert ticket number here]

### Description

[Insert description here]

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2023-01-19 08:15 UTC, drishu requested changes

2023-01-19 08:15 UTC, drishu commented on oe_showcase.post_update.php
> +function oe_showcase_post_update_00026(): void {
This is not needed here as we have the oe_starter_content one, we need to rather patch oe_starter_content in composer with a diff, so the new code gets used.

2023-01-19 09:29 UTC, tibi2303 commented on oe_showcase.post_update.php
> +function oe_showcase_post_update_00026(): void {
done.

2023-01-19 14:42 UTC, drishu requested changes

2023-01-19 14:42 UTC, drishu commented on tests/src/ExistingSite/NewsTest.php
>      $this->drupalGet('node/add/oe_sc_news');
I'm 90% sure this line is not needed, drupal should stay on the form when it has errors

2023-01-19 15:06 UTC, drishu submitted a review, later dismissed

2023-02-02 09:41 UTC, tibi2303 commented on tests/src/ExistingSite/NewsTest.php
>      $this->drupalGet('node/add/oe_sc_news');
done.

2023-02-02 15:12 UTC, drishu approved these changes, later dismissed

2023-03-02 16:32 UTC, brummbar requested changes

2023-03-02 16:32 UTC, brummbar commented on oe_showcase.post_update.php
> +function oe_showcase_post_update_00027(): void {
Is this needed? We indeed have the one in starter content.

2023-03-06 08:36 UTC, tibi2303 commented on oe_showcase.post_update.php
> +function oe_showcase_post_update_00027(): void {
removed.

2023-03-06 15:15 UTC, brummbar approved these changes

2023-03-06 15:15 UTC, merged