OEL-2050: Fixed user banner display.
openeuropa/oe_showcase pull request #213
Opened 2023-02-03 16:08 UTC by tibi2303

## OPENEUROPA-[Insert ticket number here]

### Description

[Insert description here]

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2023-02-06 09:57 UTC, drishu requested changes

2023-02-06 09:57 UTC, drishu commented on themes/oe_showcase_theme/templates/user/user--full.html.twig
>    {# @todo Remove the 'mx-n3', 'px-1' once OEL-1226 is fixed. #}
since you removed the classes you can remove also the comment

2023-02-06 09:57 UTC, drishu commented on themes/oe_showcase_theme/templates/user/user--full.html.twig
> +      content: _field_bio|raw,
the raw is not needed here

2023-02-06 09:57 UTC, drishu commented on themes/oe_showcase_theme/templates/user/user--full.html.twig
> +      <div class="pe-md-3-5">{{ content.field_bio|field_value }}</div>
please confirm if you see any difference visually with or without this wrapper

2023-02-07 10:16 UTC, tibi2303 commented on themes/oe_showcase_theme/templates/user/user--full.html.twig
> +      <div class="pe-md-3-5">{{ content.field_bio|field_value }}</div>
<img width="1055" alt="image" src="https://user-images.githubusercontent.com/36895476/217217087-d17e257c-6b5e-4d1b-b7f0-d98647ce6f35.png">
without the wrapper it will overflow the container, this limits the text width

2023-02-07 10:18 UTC, tibi2303 commented on themes/oe_showcase_theme/templates/user/user--full.html.twig
> +      content: _field_bio|raw,
removed

2023-02-07 10:18 UTC, tibi2303 commented on themes/oe_showcase_theme/templates/user/user--full.html.twig
>    {# @todo Remove the 'mx-n3', 'px-1' once OEL-1226 is fixed. #}
removed.

2023-02-08 08:48 UTC, drishu commented on themes/oe_showcase_theme/templates/user/user--full.html.twig
> +      <div class="pe-md-3-5">{{ content.field_bio|field_value }}</div>
So the idea is that without it the text might overflow, and the proper solution is to move it into the content banner block.

2023-02-10 08:33 UTC, drishu approved these changes, later dismissed

2023-02-10 11:14 UTC, drishu approved these changes

2023-03-02 15:33 UTC, merged