OEL-768: Fixed search and sort filters when both are present.
openeuropa/oe_showcase pull request #215
Opened 2023-02-08 12:31 UTC by tibi2303

## OPENEUROPA-[Insert ticket number here]

### Description

[Insert description here]

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2023-02-21 13:02 UTC, drishu requested changes

2023-02-21 13:02 UTC, drishu commented on modules/oe_showcase_search/oe_showcase_search.post_update.php
> + * Update search field preserve.
This description is not clear

2023-02-21 13:02 UTC, drishu commented on modules/oe_showcase_search/tests/src/ExistingSite/IntegrationTest.php
> +    $this->assertSame($search_input->getValue(), 'Imputo');
This is good, but we should make sure and also check that it is still present in the url

2023-02-21 13:02 UTC, drishu commented on modules/oe_showcase_search/tests/src/ExistingSite/IntegrationTest.php
> +
here assert the url with parameters

2023-02-21 16:27 UTC, tibi2303 commented on modules/oe_showcase_search/tests/src/ExistingSite/IntegrationTest.php
> +    $this->assertSame($search_input->getValue(), 'Imputo');
I did, see line 199 and 200

2023-02-21 16:27 UTC, tibi2303 commented on modules/oe_showcase_search/tests/src/ExistingSite/IntegrationTest.php
> +
Done.

2023-02-21 16:28 UTC, tibi2303 commented on modules/oe_showcase_search/oe_showcase_search.post_update.php
> + * Update search field preserve.
Changed the description.

2023-02-22 14:11 UTC, drishu requested changes

2023-02-22 14:11 UTC, drishu commented on modules/oe_showcase_search/tests/src/ExistingSite/IntegrationTest.php
> +
what is the point of these checks?

2023-02-22 14:11 UTC, drishu commented on modules/oe_showcase_search/tests/src/ExistingSite/IntegrationTest.php
> +
after using the search we should check the url and parameters

2023-02-22 14:11 UTC, drishu commented on modules/oe_showcase_search/tests/src/ExistingSite/IntegrationTest.php
> +    $this->assertStringContainsString('sort_bef_combine=created_ASC', $currentURL);
this can be done in one go

2023-02-22 14:39 UTC, tibi2303 commented on modules/oe_showcase_search/tests/src/ExistingSite/IntegrationTest.php
> +
Indeed, i see now that this check is already done, i will remove it - it was simply to check that the search works.

2023-02-22 14:43 UTC, tibi2303 commented on modules/oe_showcase_search/tests/src/ExistingSite/IntegrationTest.php
> +
I see now that this checks were already done before, I will remove them.

2023-02-22 20:48 UTC, tibi2303 commented on modules/oe_showcase_search/tests/src/ExistingSite/IntegrationTest.php
> +
done

2023-02-22 20:48 UTC, tibi2303 commented on modules/oe_showcase_search/tests/src/ExistingSite/IntegrationTest.php
> +    $this->assertStringContainsString('sort_bef_combine=created_ASC', $currentURL);
done.

2023-02-27 14:22 UTC, drishu requested changes

2023-02-27 14:22 UTC, drishu commented on modules/oe_showcase_search/tests/src/ExistingSite/IntegrationTest.php
> +    // Set search text value.
remove this comment

2023-02-27 14:22 UTC, drishu commented on modules/oe_showcase_search/tests/src/ExistingSite/IntegrationTest.php
> +
Add a comment here explaining the scenario we are going to cover

2023-02-27 14:22 UTC, drishu commented on modules/oe_showcase_search/tests/src/ExistingSite/IntegrationTest.php
> +    $this->assertStringContainsString('search_api_fulltext=' . $search_input->getValue(), $this->getUrl());
use an actual static string value instead of `$search_input->getValue()`

2023-02-27 14:22 UTC, drishu commented on modules/oe_showcase_search/tests/src/ExistingSite/IntegrationTest.php
> +    // Assert search results.
remove this comment the function name makes it clear

2023-02-27 14:22 UTC, drishu commented on modules/oe_showcase_search/tests/src/ExistingSite/IntegrationTest.php
> +    // Check url contains search value and sort value.
remove this comment, its clear, and use static string again instead of `$search_input->getValue()`

2023-02-27 14:22 UTC, drishu commented on modules/oe_showcase_search/tests/src/ExistingSite/IntegrationTest.php
> +    // Assert search results.
remove comment

2023-02-28 15:25 UTC, tibi2303 commented on modules/oe_showcase_search/tests/src/ExistingSite/IntegrationTest.php
> +    // Assert search results.
Done.

2023-02-28 15:25 UTC, tibi2303 commented on modules/oe_showcase_search/tests/src/ExistingSite/IntegrationTest.php
> +    // Check url contains search value and sort value.
Done.

2023-02-28 15:25 UTC, tibi2303 commented on modules/oe_showcase_search/tests/src/ExistingSite/IntegrationTest.php
> +    // Assert search results.
Done.

2023-02-28 15:25 UTC, tibi2303 commented on modules/oe_showcase_search/tests/src/ExistingSite/IntegrationTest.php
> +    $this->assertStringContainsString('search_api_fulltext=' . $search_input->getValue(), $this->getUrl());
Done.

2023-02-28 15:25 UTC, tibi2303 commented on modules/oe_showcase_search/tests/src/ExistingSite/IntegrationTest.php
> +
Done.

2023-02-28 15:25 UTC, tibi2303 commented on modules/oe_showcase_search/tests/src/ExistingSite/IntegrationTest.php
> +    // Set search text value.
Done.

2023-03-07 07:58 UTC, drishu commented on modules/oe_showcase_search/tests/src/ExistingSite/IntegrationTest.php
> +
could be better but ok

2023-03-07 08:00 UTC, drishu submitted a review, later dismissed

2023-03-07 11:30 UTC, drishu approved these changes

2023-03-07 15:55 UTC, merged