OEL-541: Block added into showcase search module as a content by defa…
openeuropa/oe_showcase pull request #22
Opened 2021-10-11 10:18 UTC by Maxfire

Fizes:
 - https://citnet.tech.ec.europa.eu/CITnet/jira/browse/OEL-541

2021-10-14 13:29 UTC, drishu requested changes

2021-10-14 13:29 UTC, drishu commented on modules/oe_showcase_navigation/config/install/block.block.whitelabelsearchblock.yml
> +  form:
update the config to the new schema changes

2021-10-14 13:29 UTC, drishu commented on modules/oe_showcase_navigation/config/install/block.block.whitelabelsearchblock.yml
> +langcode: en
not a mistake but I think it makes more sense to put this into the search submodule

2021-10-15 07:51 UTC, drishu requested changes
The anonymous and authenticated user roles need the "Use autocomplete for the Showcase Search search" permission

2021-10-15 12:08 UTC, abel-santos-corral submitted a review, later dismissed

2021-10-15 14:33 UTC, abel-santos-corral approved these changes

2021-10-15 14:34 UTC, drishu approved these changes

2021-10-15 14:34 UTC, merged