OEL-2541: OESA search no results - WIP
openeuropa/oe_showcase pull request #228
Opened 2023-11-09 14:25 UTC by AaronGilMartinez

## OPENEUROPA-2541

### Description

When searching for something in OESA Acceptance and Production the search page is empty.

Please enable the page to show all the content types.

### Change log

- Added: content types to showcase showcase_search_index and same filter than existing oe_list_pages.
- Changed: moved required fields by facets to a module.
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2023-11-20 17:04 UTC, brummbar requested changes

2023-11-20 17:04 UTC, brummbar commented on tests/src/ExistingSite/ProjectTest.php
> -    $assert_session->elementNotExists('css', '.card-body:nth-child(1) .text-muted');
Gosh didn't notice this test. It's horrible, we shouldn't test this way. I'll open a blocker to this ticket.

2023-11-20 17:04 UTC, brummbar commented on modules/oe_showcase_search/tests/src/ExistingSiteJavascript/IntegrationTest.php
> +    // Mark test content for deletion after the test has finished.
Leftover.

2023-11-20 17:04 UTC, brummbar commented on modules/oe_showcase_search/tests/src/ExistingSiteJavascript/IntegrationTest.php
> +    $this->assertNotNull($publication_date);
The `elementExists()` method requires the element to exist, so it won't be null.
Always use that over others like `findField`. E.g. `$assert_session->fieldExists('Event type', $filter_form);`

2023-11-20 17:04 UTC, brummbar commented on config/overrides/node.type.oe_project.yml
> +langcode: en
How come they are in the overrides folder instead of the install folder?

2023-11-20 17:04 UTC, brummbar commented on modules/oe_showcase_fields_base/oe_showcase_fields_base.install
> +function _in_active_config($configName): bool {
1. "Private" functions should start with underscore + module name.
2. Missing type hint
3. Parameters should be snake case.

2023-11-20 17:04 UTC, brummbar commented on modules/oe_showcase_fields_base/oe_showcase_fields_base.install
> +  if (empty($configName)) {
With type hint, this is not needed.

2023-11-20 17:04 UTC, brummbar commented on modules/oe_showcase_fields_base/oe_showcase_fields_base.install
> +  }
We could inline the below function like this:
```
$config = array_filter($config, function (string $config_name) use ($config_factory) {
  return !$config_factory->get($config_name)->isNew();
}

2023-11-20 17:04 UTC, brummbar commented on modules/oe_showcase_fields_base/oe_showcase_fields_base.install
> +function oe_showcase_fields_base_install() {
There's missing stuff here: https://github.com/openeuropa/oe_showcase/blob/1.x/modules/oe_showcase_page/oe_showcase_page.install#L17

2023-11-20 17:04 UTC, brummbar commented on modules/oe_showcase_search/tests/src/ExistingSiteJavascript/IntegrationTest.php
> +    $this->createnode([
`createNode()`

2023-11-20 17:04 UTC, brummbar commented on modules/oe_showcase_search/tests/src/ExistingSiteJavascript/IntegrationTest.php
> +    // Proyect start date filter.
`Project`.

2023-11-20 17:04 UTC, brummbar commented on modules/oe_showcase_search/tests/src/ExistingSiteJavascript/IntegrationTest.php
> +    $this->getSession()->wait(1000);
Use `{block: "start", inline: "nearest", behavior: "instant"}` to do an instant scroll to the element. The wait is too long.

2023-11-20 17:04 UTC, brummbar commented on oe_showcase.post_update.php
> +  ]);
We also need to trigger a reindex here.

2023-11-20 17:04 UTC, brummbar commented on modules/oe_showcase_fields_base/oe_showcase_fields_base.info.yml
> +name: Openeuropa Showcase fields base
Let's call it oe_showcase_fields .

2023-11-24 09:49 UTC, AaronGilMartinez commented on tests/src/ExistingSite/ProjectTest.php
> -    $assert_session->elementNotExists('css', '.card-body:nth-child(1) .text-muted');
Ok

2023-11-24 09:52 UTC, AaronGilMartinez commented on modules/oe_showcase_search/tests/src/ExistingSiteJavascript/IntegrationTest.php
> +    // Mark test content for deletion after the test has finished.
Removed

2023-11-24 10:11 UTC, AaronGilMartinez commented on modules/oe_showcase_search/tests/src/ExistingSiteJavascript/IntegrationTest.php
> +    $this->assertNotNull($publication_date);
Removed `assertNotNull() `and replaced `findField()` with 'fieldExists()'

2023-11-24 10:29 UTC, AaronGilMartinez commented on config/overrides/node.type.oe_project.yml
> +langcode: en
You are right not needed, moved to install.

2023-11-24 10:34 UTC, AaronGilMartinez commented on modules/oe_showcase_fields_base/oe_showcase_fields_base.install
> +function _in_active_config($configName): bool {
Fixed

2023-11-24 10:34 UTC, AaronGilMartinez commented on modules/oe_showcase_fields_base/oe_showcase_fields_base.install
> +  if (empty($configName)) {
Removed

2023-11-24 10:58 UTC, AaronGilMartinez commented on modules/oe_showcase_fields_base/oe_showcase_fields_base.install
> +  }
Replaced

2023-11-24 11:04 UTC, AaronGilMartinez commented on modules/oe_showcase_fields_base/oe_showcase_fields_base.install
> +function oe_showcase_fields_base_install() {
Added

2023-11-24 11:05 UTC, AaronGilMartinez commented on modules/oe_showcase_search/tests/src/ExistingSiteJavascript/IntegrationTest.php
> +    $this->createnode([
Fixed

2023-11-24 11:06 UTC, AaronGilMartinez commented on modules/oe_showcase_search/tests/src/ExistingSiteJavascript/IntegrationTest.php
> +    // Proyect start date filter.
Fixed

2023-11-24 12:56 UTC, AaronGilMartinez commented on modules/oe_showcase_search/tests/src/ExistingSiteJavascript/IntegrationTest.php
> +    $this->getSession()->wait(1000);
Not sure why, but is doing the scroll smoothly even with `behavior: "auto"`
https://developer.mozilla.org/es/docs/Web/API/Element/scrollIntoView
Replaced with `"window.scrollBy({top: document.querySelector('$selector').offsetTop, left: 0, behavior: 'instant'})"`

2023-11-24 13:16 UTC, AaronGilMartinez commented on oe_showcase.post_update.php
> +  ]);
Added

2023-11-24 14:44 UTC, AaronGilMartinez commented on modules/oe_showcase_fields_base/oe_showcase_fields_base.info.yml
> +name: Openeuropa Showcase fields base
Changed

2023-11-28 13:50 UTC, brummbar requested changes

2023-11-28 13:50 UTC, brummbar commented on modules/oe_showcase_fields/oe_showcase_fields.install
> +function oe_showcase_fields_install(bool $is_syncing): void {
Still missing things compared to other hook_install() methods :)

2023-11-28 15:45 UTC, brummbar commented
Another thing to fix: let's not use ever again the name "IntegrationTest" in our tests :)

2023-11-29 13:39 UTC, drishu requested changes

2023-11-29 13:39 UTC, drishu commented on config/install/node.type.oe_sc_publication.yml
> +langcode: en
what are all these content type config exported for? cant be for the list page defaults, it's not related to this ticket

2023-11-29 13:39 UTC, drishu commented on modules/oe_showcase_fields/oe_showcase_fields.install
> +
remove this newline

2023-11-29 13:39 UTC, drishu commented on modules/oe_showcase_fields/oe_showcase_fields.install
> +  // Configuration service.
remove these comments,  no clarifications needed

2023-11-29 13:39 UTC, drishu commented on modules/oe_showcase_list_pages/tests/src/ExistingSiteJavascript/ListPagesTest.php
> +        Vocabulary::load('publication_type'),
its best practice that you would do the load outsite the loop, as it does not depend on it

2023-11-29 13:39 UTC, drishu commented on modules/oe_showcase_search/config/install/facets.facet.oe_sc_publication__type.yml
> +    settings: {  }
I don't see a decision in the ticket about which filters should be added, I would have expected a content type filter instead all these dates, can you point me to the decision

2023-11-29 13:39 UTC, drishu commented on modules/oe_showcase_search/tests/src/ExistingSite/IntegrationTest.php
> +    $this->indexItems('showcase_search_index');
is this necessary for drone?

2023-11-29 13:39 UTC, drishu commented on modules/oe_showcase_search/tests/src/ExistingSite/IntegrationTest.php
> +    // Index content.
remove this comment

2023-11-29 13:39 UTC, drishu commented on modules/oe_showcase_search/tests/src/ExistingSite/IntegrationTest.php
> +    // Create oe_list_page.
remove this comment

2023-11-29 13:39 UTC, drishu commented on modules/oe_showcase_search/tests/src/ExistingSite/IntegrationTest.php
> +    // Define content types.
remove this comment

2023-11-29 13:39 UTC, drishu commented on modules/oe_showcase_search/tests/src/ExistingSiteJavascript/IntegrationTest.php
> +    // Create some News test nodes.
remove this comment

2023-11-29 13:39 UTC, drishu commented on modules/oe_showcase_search/tests/src/ExistingSiteJavascript/IntegrationTest.php
> +    // Index content.
remove this comment

2023-11-29 13:39 UTC, drishu commented on modules/oe_showcase_search/tests/src/ExistingSiteJavascript/IntegrationTest.php
> +    // Project status filter.
the formulation is not the best, for these types of comments, when you take an action rather say what the action is about, ex
// Filter by Project status closed.

same below

2023-11-30 14:07 UTC, AaronGilMartinez commented on modules/oe_showcase_fields/oe_showcase_fields.install
> +function oe_showcase_fields_install(bool $is_syncing): void {
Fixed

2023-11-30 14:12 UTC, AaronGilMartinez commented on config/install/node.type.oe_sc_publication.yml
> +langcode: en
Not related to the search but having some random order in list pages like: https://drone.fpfis.eu/openeuropa/oe_showcase/2214/11

2023-11-30 14:13 UTC, AaronGilMartinez commented on modules/oe_showcase_fields/oe_showcase_fields.install
> +
Done

2023-11-30 14:13 UTC, AaronGilMartinez commented on modules/oe_showcase_fields/oe_showcase_fields.install
> +  // Configuration service.
Done

2023-11-30 14:19 UTC, AaronGilMartinez commented on modules/oe_showcase_list_pages/tests/src/ExistingSiteJavascript/ListPagesTest.php
> +        Vocabulary::load('publication_type'),
Moved

2023-11-30 14:22 UTC, AaronGilMartinez commented on modules/oe_showcase_search/config/install/facets.facet.oe_sc_publication__type.yml
> +    settings: {  }
Here: https://citnet.tech.ec.europa.eu/CITnet/jira/browse/OEL-2541?focusedId=6457492&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-6457492

2023-11-30 14:24 UTC, AaronGilMartinez commented on modules/oe_showcase_search/tests/src/ExistingSite/IntegrationTest.php
> +    $this->indexItems('showcase_search_index');
Yes, having some strange behavior with elements not being indexed in update https://drone.fpfis.eu/openeuropa/oe_showcase/2215/22

2023-11-30 14:26 UTC, AaronGilMartinez commented on modules/oe_showcase_search/tests/src/ExistingSite/IntegrationTest.php
> +    // Index content.
Done

2023-11-30 14:27 UTC, AaronGilMartinez commented on modules/oe_showcase_search/tests/src/ExistingSite/IntegrationTest.php
> +    // Create oe_list_page.
Done

2023-11-30 14:27 UTC, AaronGilMartinez commented on modules/oe_showcase_search/tests/src/ExistingSite/IntegrationTest.php
> +    // Define content types.
Done

2023-11-30 14:30 UTC, AaronGilMartinez commented on modules/oe_showcase_search/tests/src/ExistingSiteJavascript/IntegrationTest.php
> +    // Create some News test nodes.
Done

2023-11-30 14:30 UTC, AaronGilMartinez commented on modules/oe_showcase_search/tests/src/ExistingSiteJavascript/IntegrationTest.php
> +    // Index content.
Done

2023-11-30 14:46 UTC, AaronGilMartinez commented on modules/oe_showcase_search/tests/src/ExistingSiteJavascript/IntegrationTest.php
> +    // Project status filter.
I've reformulated filters comments

2023-11-30 15:42 UTC, drishu approved these changes

2023-12-01 09:33 UTC, brummbar approved these changes

2023-12-01 09:33 UTC, merged