OEL-2598: Add optional categories to news items.
openeuropa/oe_showcase pull request #232
Opened 2023-12-01 10:25 UTC by AaronGilMartinez

2023-12-22 14:52 UTC, brummbar requested changes
Missing list pages integration.
Fields should be put inside the oe_showcase_fields module.

2023-12-22 14:52 UTC, brummbar commented on tests/src/ExistingSite/NewsTest.php
> +    $this->assertPathsRequireRole([
Please check how this has been done in https://github.com/openeuropa/oe_showcase/pull/202.

2023-12-22 14:52 UTC, brummbar commented on tests/src/ExistingSite/NewsTest.php
> +    }
Please follow https://github.com/openeuropa/oe_showcase/pull/202/files#diff-3b4fc7927c226f71dbc0f511f9c6c951714e1b0f1109cc563db388445b65191aR33 .

2024-01-08 08:35 UTC, AaronGilMartinez commented on tests/src/ExistingSite/NewsTest.php
> +    $this->assertPathsRequireRole([
Moved

2024-01-08 08:35 UTC, AaronGilMartinez commented on tests/src/ExistingSite/NewsTest.php
> +    }
Done

2024-01-08 10:58 UTC, AaronGilMartinez commented
> Missing list pages integration. Fields should be put inside the oe_showcase_fields module.

Added filter for news list page and moved field to module

2024-02-20 17:53 UTC, brummbar requested changes
Just this small remark :D

2024-02-20 17:53 UTC, brummbar commented on modules/oe_showcase_fields/oe_showcase_fields.post_update.php
> + * Add News type to News.
:D

2024-02-21 18:07 UTC, brummbar approved these changes

2024-02-21 18:07 UTC, merged