OEL-2710: Add editor to simple rich text format.
openeuropa/oe_showcase pull request #233
Opened 2023-12-19 17:51 UTC by AaronGilMartinez

## OPENEUROPA-[Insert ticket number here]

### Description

[Insert description here]

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2024-01-29 09:44 UTC, drishu requested changes

2024-01-29 09:44 UTC, drishu commented on config/install/filter.format.simple_rich_text.yml
> +  oe_oembed_filter:
the supported tags dont include images so this should not work but it because of the order of the plugins; also the requirements didnt ask for this so please remove

2024-01-29 09:44 UTC, drishu commented on config/install/filter.format.simple_rich_text.yml
> +      allowed_html: '<a href hreflang> <em> <strong> <ul> <li> <ol> <blockquote>'
the requirement asked not to change the supported tags

2024-01-29 09:44 UTC, drishu commented on config/post_updates/00033_editor_simple_rich_text/editor.editor.simple_rich_text.yml
> +          name: Lists
keep to existing supported tags

2024-01-29 09:44 UTC, drishu commented on config/post_updates/00033_editor_simple_rich_text/filter.format.simple_rich_text.yml
> +      allowed_html: '<a href hreflang> <em> <strong> <ul> <li> <ol> <blockquote>'
after fixing the installed config remember to fix also these update ones

2024-01-29 09:44 UTC, drishu commented on tests/src/ExistingSiteJavascript/EventTest.php
> +    $this->drupalGet('admin/structure/taxonomy/manage/event_type/overview');
the previous code did a lot, why did we change this ?

2024-01-29 09:44 UTC, drishu commented on tests/src/ExistingSiteJavascript/EventTest.php
> -    $assert_session->statusCodeEquals(403);
why remove ?

2024-01-29 09:44 UTC, drishu commented on tests/src/ExistingSiteJavascript/NewsTest.php
> +    $this->assertEquals('simple_rich_text', $this->getWysiwigTextFormat($introduction));
Lets improve these text editor tests by adding some allowed markup and some not allowed markup

2024-01-29 09:44 UTC, drishu commented on tests/src/ExistingSiteJavascript/ProjectTest.php
> -    $field = $page->findField('Summary');
we remove it but we didnt put anything in its place

2024-02-02 14:07 UTC, AaronGilMartinez commented on config/install/filter.format.simple_rich_text.yml
> +      allowed_html: '<a href hreflang> <em> <strong> <ul> <li> <ol> <blockquote>'
Removed

2024-02-02 14:07 UTC, AaronGilMartinez commented on config/install/filter.format.simple_rich_text.yml
> +  oe_oembed_filter:
Removed

2024-02-02 14:07 UTC, AaronGilMartinez commented on config/post_updates/00033_editor_simple_rich_text/editor.editor.simple_rich_text.yml
> +          name: Lists
Aligned

2024-02-02 14:07 UTC, AaronGilMartinez commented on config/post_updates/00033_editor_simple_rich_text/filter.format.simple_rich_text.yml
> +      allowed_html: '<a href hreflang> <em> <strong> <ul> <li> <ol> <blockquote>'
changes applied on both, install and update

2024-02-02 14:07 UTC, AaronGilMartinez commented on tests/src/ExistingSiteJavascript/ProjectTest.php
> -    $field = $page->findField('Summary');
Just reordered the assertions, with Javascript tests requires to scroll to the section, the removed code its above.

2024-02-02 14:07 UTC, AaronGilMartinez commented on tests/src/ExistingSiteJavascript/EventTest.php
> -    $assert_session->statusCodeEquals(403);
Status code can't be asserted with JSWebAssert. Couldn't find a way to check it for JS tests.

2024-02-02 14:07 UTC, AaronGilMartinez commented on tests/src/ExistingSiteJavascript/EventTest.php
> +    $this->drupalGet('admin/structure/taxonomy/manage/event_type/overview');
The trait checks status code and couldn't find a way to do that in JS tests. An option to keep the code would be try to find common assertions for both types Webassert/JSWebassert and modifying the trait.

2024-02-02 14:09 UTC, AaronGilMartinez commented on tests/src/ExistingSiteJavascript/NewsTest.php
> +    $this->assertEquals('simple_rich_text', $this->getWysiwigTextFormat($introduction));
Added some HTML to the content and checked what is rendered and what is not in this test. Not sure if we could add a trait to check this across different test, not only for the simple_rich_text also for the rich text.

2024-02-07 07:57 UTC, drishu commented on config/install/filter.format.simple_rich_text.yml
> +  oe_oembed_filter:
you forgot to remove the oe_oembed dependency

2024-02-07 08:38 UTC, drishu commented on tests/src/ExistingSiteJavascript/NewsTest.php
> +    $this->assertEquals('simple_rich_text', $this->getWysiwigTextFormat($introduction));
Your intuition is right, I did mean everywhere this text editor is used not just here. But I think it would be more efficient to have a separate test for the editor, and then we already test the presence.
Since time on the ticket is scarce, lets create a ticket for testing all editors.

2024-02-07 08:53 UTC, drishu commented on tests/src/ExistingSiteJavascript/EventTest.php
> -    $assert_session->statusCodeEquals(403);
its used in ContactFormTest and it seems to be green

2024-02-07 08:54 UTC, drishu commented on tests/src/ExistingSiteJavascript/EventTest.php
> +    $this->drupalGet('admin/structure/taxonomy/manage/event_type/overview');
its used in ContactFormTest and seems to be green

2024-02-12 10:51 UTC, AaronGilMartinez commented on config/install/filter.format.simple_rich_text.yml
> +  oe_oembed_filter:
Done

2024-02-12 10:52 UTC, AaronGilMartinez commented on tests/src/ExistingSiteJavascript/EventTest.php
> +    $this->drupalGet('admin/structure/taxonomy/manage/event_type/overview');
As we saw ContactFormTest is using Functional tests and there is no quick way to get the status.

2024-02-12 10:52 UTC, AaronGilMartinez commented on tests/src/ExistingSiteJavascript/EventTest.php
> -    $assert_session->statusCodeEquals(403);
As we saw ContactFormTest is using Functional tests and there is no quick way to get the status.

2024-02-12 10:52 UTC, AaronGilMartinez commented on tests/src/ExistingSiteJavascript/NewsTest.php
> +    $this->assertEquals('simple_rich_text', $this->getWysiwigTextFormat($introduction));
Created this https://citnet.tech.ec.europa.eu/CITnet/jira/browse/OEL-2821

2024-02-12 16:05 UTC, drishu submitted a review, later dismissed

2024-02-19 17:28 UTC, brummbar requested changes

2024-02-19 17:28 UTC, brummbar commented on tests/src/ExistingSiteJavascript/ProjectTest.php
> +    $page->find('css', 'input[value="Remove"]')->press();
Not sure about this. Why this change? Inputs are still considered buttons.

2024-02-23 15:53 UTC, AaronGilMartinez commented on tests/src/ExistingSiteJavascript/ProjectTest.php
> +    $page->find('css', 'input[value="Remove"]')->press();
The pressButton method looks for button tags
![image](https://github.com/openeuropa/oe_showcase/assets/7264392/b32f3db1-6e91-47bf-8b02-7aa5c2ae3e4e)

With JS enabled those are Ajax and are replaced with inputs
![image](https://github.com/openeuropa/oe_showcase/assets/7264392/04e38621-b928-43a9-8884-c5e2c84617f2)

Not sure if there is another way to target them

2024-04-21 07:37 UTC, drishu approved these changes, later dismissed

2024-04-25 08:33 UTC, brummbar approved these changes

2024-04-25 08:33 UTC, merged