Oel 2756: Fix page teaser rendering.
openeuropa/oe_showcase pull request #234
Opened 2023-12-22 14:46 UTC by AaronGilMartinez

## OPENEUROPA-[Insert ticket number here]

### Description

[Insert description here]

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2024-01-12 18:35 UTC, brummbar requested changes

2024-01-12 18:35 UTC, brummbar commented on themes/oe_showcase_theme/templates/node/node--oe-showcase-page--teaser.html.twig
> +    node.getCreatedTime|date("d F Y"),
Please take a look at the other date formats.

2024-01-16 08:12 UTC, AaronGilMartinez commented on themes/oe_showcase_theme/templates/node/node--oe-showcase-page--teaser.html.twig
> +    node.getCreatedTime|date("d F Y"),
I applied same format than other dates but no specific date format for this one. Do you mean to create one?

2024-01-31 08:51 UTC, drishu requested changes

2024-01-31 08:51 UTC, drishu commented on themes/oe_showcase_theme/templates/node/node--oe-showcase-page--teaser.html.twig
> +    node.getCreatedTime|date("d F Y"),
yes, its best if we put these into config so they can be easly managed

2024-01-31 08:51 UTC, drishu commented on modules/oe_showcase_search/tests/src/ExistingSite/IntegrationTest.php
> +   * Asserts search result created date from items.
this description does not match what the function is doing

2024-01-31 08:51 UTC, drishu commented on modules/oe_showcase_search/tests/src/ExistingSite/IntegrationTest.php
> +    // First page are oe_showcase_page elements.
remove this comment, its redundant

2024-01-31 08:51 UTC, drishu commented on modules/oe_showcase_search/tests/src/ExistingSite/IntegrationTest.php
> +    // Fourth page are oe_showcase_search_demo elements.
remove comment

2024-02-02 17:25 UTC, AaronGilMartinez commented on modules/oe_showcase_search/tests/src/ExistingSite/IntegrationTest.php
> +    // Fourth page are oe_showcase_search_demo elements.
Done

2024-02-02 17:25 UTC, AaronGilMartinez commented on modules/oe_showcase_search/tests/src/ExistingSite/IntegrationTest.php
> +    // First page are oe_showcase_page elements.
Done

2024-02-02 17:25 UTC, AaronGilMartinez commented on modules/oe_showcase_search/tests/src/ExistingSite/IntegrationTest.php
> +   * Asserts search result created date from items.
Changed

2024-02-07 09:26 UTC, drishu requested changes
also rebase pls

2024-02-07 09:26 UTC, drishu commented on themes/oe_showcase_theme/templates/node/node--search-result.html.twig
> +    node.getCreatedTime|date("d F Y"),
you forgot to change this one

2024-02-12 08:33 UTC, AaronGilMartinez commented on themes/oe_showcase_theme/templates/node/node--search-result.html.twig
> +    node.getCreatedTime|date("d F Y"),
Added

2024-02-12 09:55 UTC, drishu approved these changes

2024-04-18 06:47 UTC, drishu approved these changes

2024-04-23 16:21 UTC, brummbar approved these changes

2024-04-23 16:21 UTC, merged