OEL-2755: Disable the /node page.
openeuropa/oe_showcase pull request #235
Opened 2024-01-10 12:06 UTC by AaronGilMartinez

## OPENEUROPA-[Insert ticket number here]

### Description

[Insert description here]

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2024-01-12 19:38 UTC, brummbar requested changes

2024-01-12 19:38 UTC, brummbar commented on oe_showcase.post_update.php
> +  ConfigImporter::importSingle(
Since we are just disabling the view, we can simply load it and disable it.

2024-01-12 19:38 UTC, brummbar commented on tests/src/ExistingSite/ProjectTest.php
> -    $assert_session->elementExists('css', '.views-row:nth-child(1) .text-muted');
Did you find what this test was supposed to cover?

2024-01-16 08:29 UTC, AaronGilMartinez commented on tests/src/ExistingSite/ProjectTest.php
> -    $assert_session->elementExists('css', '.views-row:nth-child(1) .text-muted');
I think it was there to test some information displayed in the teaser, or the teaser itself. Checking the file historic, it seems that in the past the test to check how project looked in lists were here. Using node view or creating a specific view only for tests.

2024-01-30 16:04 UTC, drishu submitted a review, later dismissed

2024-01-30 16:04 UTC, drishu commented on tests/src/ExistingSite/ProjectTest.php
> -    $assert_session->elementNotExists('css', '.views-row:nth-child(1) .text-muted');
think its fine to remove, stuff like this needs to be handled differently

2024-02-08 07:23 UTC, drishu approved these changes

2024-02-14 17:58 UTC, brummbar approved these changes

2024-02-14 17:58 UTC, merged