OEL-2794: Update components to run on Drupal 10.2.x
openeuropa/oe_showcase pull request #237
Opened 2024-01-30 15:17 UTC by AaronGilMartinez

## OPENEUROPA-[Insert ticket number here]

### Description

[Insert description here]

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2024-02-01 08:02 UTC, drishu requested changes
We can also safely drop version 9 from all core_version_requirement

2024-02-01 08:02 UTC, drishu commented on composer.json
> +        "drupal/core-recommended": "^10.2",
try with ^10 and run composer update for these packages with the dependencies flag, it should install the latest 10.2

also I think the php requirement should be a minimum of php 8.1

you can remove oe_starter_content and oe_content_extra from the "repositories" section while we are here, they where added to packagist

2024-02-01 08:02 UTC, drishu commented on tests/src/ExistingSiteJavascript/ShowcaseExistingSiteJavascriptTestBase.php
> +
remove

2024-02-01 08:02 UTC, drishu commented on .drone.yml
> +      - ./vendor/bin/drush en -y media_avportal_mock oe_media_oembed_mock js_testing_ajax_request_test
intresting but I dont see the usage, can you explain to me a bit?

2024-02-01 08:02 UTC, drishu commented on modules/oe_showcase_list_pages/tests/src/ExistingSiteJavascript/ListPagesTest.php
> +  protected function sortByOption(string $option): void {
the name of the function does not reflect what it does, this function selects an option, so selectSortByOption

2024-02-05 10:35 UTC, AaronGilMartinez commented on modules/oe_showcase_list_pages/tests/src/ExistingSiteJavascript/ListPagesTest.php
> +  protected function sortByOption(string $option): void {
Renamed

2024-02-05 10:35 UTC, AaronGilMartinez commented on tests/src/ExistingSiteJavascript/ShowcaseExistingSiteJavascriptTestBase.php
> +
done

2024-02-05 10:35 UTC, AaronGilMartinez commented on composer.json
> +        "drupal/core-recommended": "^10.2",
done

2024-02-05 11:52 UTC, AaronGilMartinez commented on .drone.yml
> +      - ./vendor/bin/drush en -y media_avportal_mock oe_media_oembed_mock js_testing_ajax_request_test
The core Javascript tests base class (core/tests/Drupal/FunctionalJavascriptTests/WebDriverTestBase.php) uses that module to track Ajax requests, with Drupal 10.2 there are changes and new checks on the function assertWaitOnAjaxRequest (drupal-site/web/core/tests/Drupal/FunctionalJavascriptTests/JSWebAssert.php) and if there is no Ajax request the test fails.
Our Javascript tests extends the provided by weitzman/drupal-test-site so the module is not installed and some test fail.

2024-02-12 15:01 UTC, drishu submitted a review, later dismissed

2024-02-13 14:38 UTC, drishu approved these changes

2024-02-13 14:39 UTC, drishu submitted a review, later dismissed

2024-02-13 14:39 UTC, drishu commented on composer.json
> +                "Simple decimals fail to pass validation @see https://www.drupal.org/project/drupal/issues/2230909": "https://www.drupal.org/files/issues/2023-12-21/2230909-309.patch"
think we should use the stable oe_content version and drop this line

2024-03-07 08:25 UTC, AaronGilMartinez commented on composer.json
> +                "Simple decimals fail to pass validation @see https://www.drupal.org/project/drupal/issues/2230909": "https://www.drupal.org/files/issues/2023-12-21/2230909-309.patch"
Removed and updated

2024-03-07 12:58 UTC, brummbar approved these changes

2024-03-07 12:58 UTC, merged