OEL-2616: The selection of gender is insulting for users who could not be identifying as CIS female/male.
openeuropa/oe_showcase pull request #240
Opened 2024-02-23 15:11 UTC by AaronGilMartinez

…t be identifying as CIS female/male.

## OPENEUROPA-[Insert ticket number here]

### Description

[Insert description here]

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2024-02-23 15:11 UTC, AaronGilMartinez commented on modules/oe_showcase_user_profile/oe_showcase_user_profile.install
> -    'human-sex' => 'http://publications.europa.eu/resource/dataset/human-sex',
@todo Check if the hook update has to remove this

2024-02-26 10:59 UTC, AaronGilMartinez commented on modules/oe_showcase_user_profile/oe_showcase_user_profile.install
> -    'human-sex' => 'http://publications.europa.eu/resource/dataset/human-sex',
The graph is used by  oe_person in oe_content, keeping it.

2024-02-28 16:06 UTC, brummbar commented on modules/oe_showcase_user_profile/oe_showcase_user_profile.install
> -    'human-sex' => 'http://publications.europa.eu/resource/dataset/human-sex',
It's ok to leave the graph.

2024-02-28 16:08 UTC, brummbar requested changes

2024-02-28 16:08 UTC, brummbar commented on modules/oe_showcase_user_profile/tests/src/ExistingSite/IntegrationTest.php
> +    $fields = array_filter($user->getFieldDefinitions(), function ($field) {
Why this? It's enough to test that we don't have a gender field anymore.

2024-02-28 16:08 UTC, brummbar commented on modules/oe_showcase_user_profile/oe_showcase_user_profile.post_update.php
> +  $graph = [
We can leave the graph, it's fine.

2024-02-29 07:18 UTC, AaronGilMartinez commented on modules/oe_showcase_user_profile/tests/src/ExistingSite/IntegrationTest.php
> +    $fields = array_filter($user->getFieldDefinitions(), function ($field) {
Wanted to avoid checking something that is not there, and try to check the total fields that should be there. The field definition variable its to make sure it has been deleted not hidden.

2024-02-29 07:18 UTC, AaronGilMartinez commented on modules/oe_showcase_user_profile/oe_showcase_user_profile.post_update.php
> +  $graph = [
Ok

2024-02-29 17:45 UTC, brummbar requested changes

2024-02-29 17:45 UTC, brummbar commented on modules/oe_showcase_user_profile/tests/src/ExistingSite/IntegrationTest.php
> +    $fields = array_filter($user->getFieldDefinitions(), function ($field) {
It's ok if it would be hidden. If you really want to check if the entity bundle doesn't have the field, you can add a one liner at the end to check programmatically that field X does not exists.

2024-03-01 11:18 UTC, AaronGilMartinez commented on modules/oe_showcase_user_profile/tests/src/ExistingSite/IntegrationTest.php
> +    $fields = array_filter($user->getFieldDefinitions(), function ($field) {
Added the field check

2024-03-12 15:55 UTC, brummbar approved these changes

2024-03-12 15:55 UTC, merged