OEL-2846: Check emails sent in contact form tests
openeuropa/oe_showcase pull request #245
Opened 2024-03-19 16:43 UTC by AaronGilMartinez

## OPENEUROPA-[Insert ticket number here]

### Description

[Insert description here]

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2024-04-12 05:42 UTC, drishu requested changes, later dismissed

2024-04-12 05:42 UTC, drishu commented on modules/oe_showcase_contact_forms/oe_showcase_contact_forms.module
> +  // This function removes extra spaces in recipient adresses added by contact
```suggestion
  // This function removes extra spaces in recipient addresses added by contact
```

2024-04-12 05:42 UTC, drishu commented on modules/oe_showcase_contact_forms/oe_showcase_contact_forms.module
> +  $adresses = [];
```suggestion
  $addresses = [];
```

2024-04-12 05:42 UTC, drishu commented on modules/oe_showcase_contact_forms/oe_showcase_contact_forms.module
> +  // @see oe_showcase/build/core/modules/contact/src/MailHandler.php
oe_showcase/build/core/... is not good, please use a fully qualified class name and ::method name attached, and a short explanation that lets me know what exactly MailHandler does and maybe why to attach the space. And please also look if there is an issue to fix it, and attach it here.

About the explanation, I honestly dont see where in that class the issue is, I didnt look deep into it but I rather expect it to be where the recipient email is set.

2024-04-12 05:42 UTC, drishu commented on modules/oe_showcase_contact_forms/oe_showcase_contact_forms.post_update.php
> + * OE Showcase List pages post updates.
a copy paste error "List pages"

2024-04-12 05:42 UTC, drishu commented on modules/oe_showcase_contact_forms/tests/src/ExistingSite/ContactFormTest.php
> +    // Configured recipients + Topic address.
I dont see anything related to "Topic address."

2024-04-12 05:42 UTC, drishu commented on modules/oe_showcase_contact_forms/tests/src/ExistingSite/ContactFormTest.php
> +use Drupal\symfony_mailer\Email;
phpstorm is indicating to me that Symfony\Component\Mime\Email is provided

2024-04-12 05:42 UTC, drishu commented on modules/oe_showcase_contact_forms/tests/src/ExistingSite/ContactFormTest.php
> +    $this->assertMailTexts([
I dont like this very much, both are texts in the email body, so should be tested together, you can pass the dynamic strings as an array to a single function that tests the content of  the email body.

2024-04-12 05:42 UTC, drishu commented on modules/oe_showcase_contact_forms/tests/src/ExistingSite/ContactFormTest.php
> +      $this->assertStringContainsString($expected, $crawler->text());
assertStringContainsString easily give false positives, so it is important what you pass to it, I see we getHtmlBody, we could add the wrapping tags, even better would be to define a mail template in a string and use sprintf to add in parameters. Lets discuss.

2024-04-19 08:01 UTC, AaronGilMartinez commented on modules/oe_showcase_contact_forms/oe_showcase_contact_forms.module
> +  // This function removes extra spaces in recipient adresses added by contact
Changed

2024-04-19 08:01 UTC, AaronGilMartinez commented on modules/oe_showcase_contact_forms/oe_showcase_contact_forms.module
> +  $adresses = [];
Changed

2024-04-19 08:01 UTC, AaronGilMartinez commented on modules/oe_showcase_contact_forms/oe_showcase_contact_forms.post_update.php
> + * OE Showcase List pages post updates.
Fixed

2024-04-19 08:01 UTC, AaronGilMartinez commented on modules/oe_showcase_contact_forms/tests/src/ExistingSite/ContactFormTest.php
> +use Drupal\symfony_mailer\Email;
Same than https://github.com/openeuropa/oe_subscriptions/pull/31#discussion_r1568365472

2024-04-19 08:01 UTC, AaronGilMartinez commented on modules/oe_showcase_contact_forms/tests/src/ExistingSite/ContactFormTest.php
> +    // Configured recipients + Topic address.
Added

2024-04-19 08:01 UTC, AaronGilMartinez commented on modules/oe_showcase_contact_forms/tests/src/ExistingSite/ContactFormTest.php
> +    $this->assertMailTexts([
Moved to the assertMailTexts()

2024-04-19 08:01 UTC, AaronGilMartinez commented on modules/oe_showcase_contact_forms/tests/src/ExistingSite/ContactFormTest.php
> +      $this->assertStringContainsString($expected, $crawler->text());
Added assertion with template with placeholders.

2024-04-19 08:01 UTC, AaronGilMartinez commented on modules/oe_showcase_contact_forms/oe_showcase_contact_forms.module
> +  // @see oe_showcase/build/core/modules/contact/src/MailHandler.php
Changed explanation and added fully cualified names

2024-04-24 15:24 UTC, brummbar approved these changes

2024-04-24 15:31 UTC, brummbar commented
We will have two followups in order to be able to turn on the Symfony Mailer override for contact forms.

2024-04-24 15:55 UTC, merged