OEL-2929: Add an optional title, description and image on the listing page.
openeuropa/oe_showcase pull request #248
Opened 2024-04-25 09:41 UTC by AaronGilMartinez

## OPENEUROPA-[Insert ticket number here]

### Description

[Insert description here]

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2024-04-26 15:00 UTC, brummbar requested changes

2024-04-26 15:00 UTC, brummbar commented on config/install/core.entity_form_display.node.oe_list_page.default.yml
> +    type: oe_featured_media_autocomplete
We can use the other widget here, so it's easier to pick images.

2024-04-26 15:00 UTC, brummbar commented on config/install/field.field.node.oe_list_page.oe_summary.yml
> +    - rich_text
This should be simple rich text.

2024-04-26 15:00 UTC, brummbar commented on modules/oe_showcase_list_pages/tests/src/ExistingSiteJavascript/ListPagesTest.php
> +    $this->assertResultsTitle(12);
It's not a title anymore, it's a count.

2024-04-26 15:00 UTC, brummbar commented on modules/oe_showcase_list_pages/tests/src/ExistingSiteJavascript/ListPagesTest.php
> +      $media = Media::create([
We have a media creation trait.

2024-04-26 15:00 UTC, brummbar commented on modules/oe_showcase_list_pages/tests/src/ExistingSiteJavascript/ListPagesTest.php
> +  protected function assertPageBanner(string $expected_title, string $expected_summary = '', array $expected_image = []) {
Why not ContentBannerAssert?

2024-04-30 08:20 UTC, AaronGilMartinez commented on modules/oe_showcase_list_pages/tests/src/ExistingSiteJavascript/ListPagesTest.php
> +  protected function assertPageBanner(string $expected_title, string $expected_summary = '', array $expected_image = []) {
The function name can be more descriptive indeed, we should use lowerCamelCase and assert functions should start with 'assert' prefix like: assertContentBanner

2024-04-30 08:21 UTC, AaronGilMartinez commented on modules/oe_showcase_list_pages/tests/src/ExistingSiteJavascript/ListPagesTest.php
> +      $media = Media::create([
We can reuse it, we have some other content types where we create media instead of using the trait I think would be a good idea to apply to all of them

2024-04-30 08:21 UTC, AaronGilMartinez commented on modules/oe_showcase_list_pages/tests/src/ExistingSiteJavascript/ListPagesTest.php
> +    $this->assertResultsTitle(12);
True

2024-04-30 14:32 UTC, AaronGilMartinez commented on modules/oe_showcase_list_pages/tests/src/ExistingSiteJavascript/ListPagesTest.php
> +      $media = Media::create([
Adding it only for list pages until confirmation

2024-04-30 14:56 UTC, AaronGilMartinez commented on config/install/field.field.node.oe_list_page.oe_summary.yml
> +    - rich_text
Changed

2024-04-30 15:14 UTC, AaronGilMartinez commented on modules/oe_showcase_list_pages/tests/src/ExistingSiteJavascript/ListPagesTest.php
> +  protected function assertPageBanner(string $expected_title, string $expected_summary = '', array $expected_image = []) {
Missunderstood, replacing with ContentBannerAssert() and assertPattern()

2024-04-30 18:05 UTC, AaronGilMartinez commented on config/install/core.entity_form_display.node.oe_list_page.default.yml
> +    type: oe_featured_media_autocomplete
Added entity browser like in publications

2024-05-02 14:36 UTC, brummbar approved these changes

2024-05-02 14:36 UTC, merged