OEL-2606: Add a link back to the glossary page in breadcrumb
openeuropa/oe_showcase pull request #253
Opened 2024-05-31 10:20 UTC by AaronGilMartinez

## OPENEUROPA-[Insert ticket number here]

### Description

[Insert description here]

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2024-05-31 14:09 UTC, drishu requested changes

2024-05-31 14:09 UTC, drishu commented on modules/oe_showcase_glossary/config/install/pathauto.pattern.glossary_term_url_alias_pattern.yml
> +langcode: en
add this to the config_devel in info.yml

2024-05-31 14:09 UTC, drishu commented on modules/oe_showcase_glossary/tests/src/ExistingSite/GlossaryTest.php
> +    // Test pager in 'a' character, to check aditional URL parameters like
```suggestion
    // Test pager in 'a' character, to check additional URL parameters like
```

2024-05-31 14:59 UTC, AaronGilMartinez commented on modules/oe_showcase_glossary/config/install/pathauto.pattern.glossary_term_url_alias_pattern.yml
> +langcode: en
Added

2024-05-31 15:00 UTC, AaronGilMartinez commented on modules/oe_showcase_glossary/tests/src/ExistingSite/GlossaryTest.php
> +    // Test pager in 'a' character, to check aditional URL parameters like
Fixed

2024-06-02 13:38 UTC, drishu approved these changes, later dismissed

2024-06-04 17:41 UTC, brummbar requested changes

2024-06-04 17:41 UTC, brummbar commented on modules/oe_showcase_glossary/tests/src/ExistingSite/GlossaryTest.php
> +    $crawler = new Crawler($this->getSession()->getPage()->getContent());
Don't use the crawler here. Use the assert session.

2024-06-05 07:02 UTC, AaronGilMartinez commented on modules/oe_showcase_glossary/tests/src/ExistingSite/GlossaryTest.php
> +    $crawler = new Crawler($this->getSession()->getPage()->getContent());
Replaced

2024-06-05 15:25 UTC, drishu submitted a review, later dismissed

2024-06-05 15:33 UTC, brummbar requested changes

2024-06-05 15:33 UTC, brummbar commented on modules/oe_showcase_glossary/tests/src/ExistingSite/GlossaryTest.php
> +    $this->assertCount(count($expected_segments), $breadcrumbs_items);
assertSameSize()

2024-06-05 15:49 UTC, brummbar approved these changes

2024-06-06 10:35 UTC, drishu approved these changes

2024-06-06 11:41 UTC, merged