OEL-2994: Bug fixing on glossary page.
openeuropa/oe_showcase pull request #254
Opened 2024-06-06 12:50 UTC by tibi2303

## OPENEUROPA-[Insert ticket number here]

### Description

[Insert description here]

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2024-06-07 08:05 UTC, AaronGilMartinez requested changes
Small remark for OEL-2610

2024-06-07 08:05 UTC, AaronGilMartinez commented on themes/oe_showcase_theme/assets/css/oe_showcase_theme.css
> +  margin-bottom: -.75rem; /* Remove default margin for .card-text - mb-2-5 if empty */
Not sure about this, we are applying an style to an optional element:
1. The card adds the margin bottom no matter if there is content or not.
2. Negative margin for the child, if the field is empty won't be present and the margin will be different.

2024-06-07 08:05 UTC, AaronGilMartinez commented on themes/oe_showcase_theme/assets/css/oe_showcase_theme.css
> +  margin-bottom: -.75rem; /* Remove default margin for .card-text - mb-2-5 if empty */
![image](https://github.com/openeuropa/oe_showcase/assets/7264392/12617c45-ec51-4655-af0f-b1c8d998573c)

2024-06-07 10:51 UTC, AaronGilMartinez approved these changes

2024-06-10 19:00 UTC, drishu approved these changes

2024-07-01 16:14 UTC, merged