OEL-2606: Add hook update to enable glossary terms automatic alias.
openeuropa/oe_showcase pull request #255
Opened 2024-06-06 16:56 UTC by AaronGilMartinez

## OPENEUROPA-[Insert ticket number here]

### Description

[Insert description here]

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2024-06-11 06:31 UTC, drishu requested changes

2024-06-11 06:31 UTC, drishu commented on modules/oe_showcase_glossary/oe_showcase_glossary.post_update.php
> +    $term->path->pathauto = TRUE;
my editor indicates path is protected, lets try something like `$term->set('path', ['pathauto' => TRUE]);`

2024-06-11 09:49 UTC, AaronGilMartinez commented on modules/oe_showcase_glossary/oe_showcase_glossary.post_update.php
> +    $term->path->pathauto = TRUE;
Indeed, its better

2024-06-12 05:25 UTC, drishu approved these changes

2024-06-12 13:46 UTC, intelektron approved these changes

2024-07-01 17:07 UTC, merged