OEL-600: Move from runner module dependencies.
openeuropa/oe_showcase pull request #26
Opened 2021-10-14 14:15 UTC by escuriola

- https://citnet.tech.ec.europa.eu/CITnet/jira/browse/OEL-600

2021-10-18 15:54 UTC, abel-santos-corral requested changes

2021-10-18 15:54 UTC, abel-santos-corral commented on oe_showcase.info.yml
>    - block_content
Are we using the block content to create custom blocks? Is this necessary here or can be removed?

2021-10-18 15:54 UTC, abel-santos-corral commented on runner.yml.dist
>      - "./vendor/bin/drush -y config-set system.performance css.preprocess 0"
Please, add a folder (or check if after OEL-542 is already present, do a git rebase) of congig and export the configs of the system.performance and leave this things configured.

2021-10-25 10:17 UTC, drishu commented on runner.yml.dist
>      - "./vendor/bin/drush -y config-set system.performance css.preprocess 0"
these are definitely dev settings and should stay in runner

2021-10-25 10:20 UTC, drishu approved these changes

2021-10-25 10:58 UTC, abel-santos-corral approved these changes
Approved

2021-10-25 12:46 UTC, merged