OEL-3057: Update to Drupal 10.3
openeuropa/oe_showcase pull request #261
Opened 2024-07-16 13:55 UTC by AaronGilMartinez

2024-07-16 15:47 UTC, drishu requested changes

2024-07-16 15:47 UTC, drishu commented on composer.lock
> -            "version": "3.4.0",
seems that a lot was updated, maybe unnecessary, I think you'll have better results with composer update drupal/core-recommended drupal/core-composer-scaffold drupal/core-dev -W

2024-07-17 06:46 UTC, AaronGilMartinez commented on composer.lock
> -            "version": "3.4.0",
Changed, updated core, media_avportal and datetime_testing

2024-07-17 09:55 UTC, drishu approved these changes

2024-07-17 11:07 UTC, merged