OEL-3124: Add url alias patterns to content types.
openeuropa/oe_showcase pull request #263
Opened 2024-07-28 13:15 UTC by drishu

## OPENEUROPA-[Insert ticket number here]

### Description

[Insert description here]

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2024-07-31 09:01 UTC, drishu commented on modules/oe_showcase_subscriptions/tests/src/ExistingSite/EventSubscriptionTest.php
> +        'url' => $event->toUrl()->setOption('alias', TRUE)->setAbsolute()->toString(),
setting alias to TRUE to get unaliased links is not confusing at all :)

2024-07-31 17:01 UTC, AaronGilMartinez requested changes

2024-07-31 17:01 UTC, AaronGilMartinez commented on oe_showcase.post_update.php
> +  ]);
Missing hook_update to regenerate content aliases like: https://github.com/openeuropa/oe_showcase/blob/18c2e6b68ec2284b6425d780a92e14338d22defe/modules/oe_showcase_glossary/oe_showcase_glossary.post_update.php#L13-L52

2024-07-31 17:01 UTC, AaronGilMartinez commented on oe_showcase.post_update.php
> +  ]);
Current pattern alias for project and page doesn't match with requirements, both need update.
See table in https://citnet.tech.ec.europa.eu/CITnet/jira/browse/OEL-2596

2024-07-31 17:02 UTC, AaronGilMartinez commented on modules/oe_showcase_subscriptions/tests/src/ExistingSite/EventSubscriptionTest.php
> +        'url' => $event->toUrl()->setOption('alias', TRUE)->setAbsolute()->toString(),
Another option would be 'path_processing' => FALSE

2024-08-01 14:56 UTC, drishu commented on modules/oe_showcase_subscriptions/tests/src/ExistingSite/EventSubscriptionTest.php
> +        'url' => $event->toUrl()->setOption('alias', TRUE)->setAbsolute()->toString(),
I'm not certain about your comment, I checked core and found instances of how I did it, but not on how you suggested. I am aware of the option but dont know if all possible plugins should be shut down.

2024-08-01 15:05 UTC, drishu commented on oe_showcase.post_update.php
> +  ]);
good find, thx. I didn't add the pages to the update, as I dont think we should touch those old pages (News, Events, etc I think is ok, as they have listing pages and can be found like that).

2024-08-02 08:46 UTC, AaronGilMartinez requested changes

2024-08-02 08:46 UTC, AaronGilMartinez commented on oe_showcase.post_update.php
> +  ]);
About pages I would add them, why not?
List pages will need to be updated, pattern is there, but existing content isn't using alias pattern.

2024-08-02 08:46 UTC, AaronGilMartinez commented on modules/oe_showcase_subscriptions/tests/src/ExistingSite/EventSubscriptionTest.php
> +        'url' => $event->toUrl()->setOption('alias', TRUE)->setAbsolute()->toString(),
To complement information, I found this option in \Drupal\Core\Routing\UrlGenerator
I though was interesting to mention

2024-08-02 18:13 UTC, drishu commented on modules/oe_showcase_subscriptions/tests/src/ExistingSite/EventSubscriptionTest.php
> +        'url' => $event->toUrl()->setOption('alias', TRUE)->setAbsolute()->toString(),
I'm aware, but there is not usage like that in core, if we check /Drupal/Core/Entity/Controller/EntityViewController.php we see this option in use

2024-08-05 10:52 UTC, AaronGilMartinez submitted a review, later dismissed

2024-08-07 11:04 UTC, AaronGilMartinez requested changes

2024-08-07 11:07 UTC, AaronGilMartinez approved these changes

2024-08-07 11:07 UTC, AaronGilMartinez commented on oe_showcase.post_update.php
> +    $node->search_api_skip_tracking = TRUE;
I though was needed for home too, but its a change of the content and shouldn't be skipped, even with warning.

2024-08-07 14:48 UTC, brummbar approved these changes

2024-08-09 13:12 UTC, merged