OEL-3158: Reposition eu-footer items
openeuropa/oe_showcase pull request #264
Opened 2024-08-05 07:22 UTC by drishu

## OEL-3158

### Description

Reposition eu-footer items with openeuropa/oe_corporate_blocks version 4.19.0 and above

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

2024-08-07 06:42 UTC, AaronGilMartinez requested changes

2024-08-07 06:42 UTC, AaronGilMartinez commented on composer.json
> +                "Move the Legal section to the top right position in the EU footer": "https://github.com/openeuropa/oe_whitelabel/compare/1.x...contribution/UCPKN-3181.diff"
This brings the fix from contribution (oe_whitelabel) but oe_corporate_blocks is locked at 4.18.
I think would be would good to update it to see footer link changes in oe_showcase.

If you do, theme configuration page will crash due missing schema.

2024-08-07 14:24 UTC, AaronGilMartinez approved these changes, later dismissed

2024-08-07 19:39 UTC, brummbar approved these changes, later dismissed

2024-08-09 16:20 UTC, brummbar approved these changes

2024-08-09 16:20 UTC, merged