OEL-579: BCL 0.9.0 with all components upgraded.
openeuropa/oe_showcase pull request #27
Opened 2021-10-15 14:00 UTC by escuriola

https://citnet.tech.ec.europa.eu/CITnet/jira/browse/OEL-579

2021-10-21 09:55 UTC, drishu requested changes

2021-10-21 09:55 UTC, drishu commented on modules/oe_showcase_search/templates/node--search-result.html.twig
>    {% for key,item in content.field_category %}
let's see if we can prep a variant of the card pattern inside whitelabel that offers these configurations and parsing out of the box

2021-10-26 16:43 UTC, escuriola commented on modules/oe_showcase_search/templates/node--search-result.html.twig
>    {% for key,item in content.field_category %}
Not done yet.

2021-10-27 07:29 UTC, escuriola commented on modules/oe_showcase_search/templates/node--search-result.html.twig
>    {% for key,item in content.field_category %}
Now it's done.

2021-10-28 15:18 UTC, abel-santos-corral approved these changes

2021-10-29 06:48 UTC, abel-santos-corral approved these changes

2021-10-29 06:59 UTC, timpevi approved these changes

2021-10-29 06:59 UTC, drishu approved these changes

2021-10-29 07:00 UTC, merged