OEL-3168: Send subscriptions emails after update hooks run
openeuropa/oe_showcase pull request #270
Opened 2024-09-09 09:49 UTC by AaronGilMartinez

## OPENEUROPA-[Insert ticket number here]

### Description

[Insert description here]

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2024-09-16 14:43 UTC, donquixote commented on modules/oe_showcase_subscriptions/oe_showcase_subscriptions.module
> +function oe_showcase_subscriptions_node_postsave(NodeInterface $node) {
I can see how this would work.
But we can achieve the same with hook_node_update() + hook_module_implements_alter() to make it run last(ish), without a patch.
The idea of a separate hook is not bad, but relying on the patch introduces fragility which we could avoid.

2024-09-16 16:25 UTC, donquixote commented on modules/oe_showcase_subscriptions/tests/src/ExistingSite/EventSubscriptionTest.php
> +        'url' => $event->toUrl()->setAbsolute()->toString(),
Could we use an explicit literal string here?
The alias should be always 'event-update-2' at this point, based on the title update from earlier.
Using the explicit string makes the test more predictable.

2024-09-16 21:24 UTC, donquixote commented on modules/oe_showcase_subscriptions/tests/src/ExistingSite/EventSubscriptionTest.php
> +        'url' => $event->toUrl()->setAbsolute()->toString(),
Not so sure about this anymore.
On the first test run and even on further repeated successful runs the url alias seems to be stable.
Do we need to consider scenarios where it is not?

2024-09-16 21:55 UTC, donquixote commented on modules/oe_showcase_subscriptions/oe_showcase_subscriptions.module
> +function oe_showcase_subscriptions_node_postsave(NodeInterface $node) {
I tried this, it's a dead end.
hook_entity_update() runs after hook_node_update(), and hook_module_implements_alter() cannot change that.
So we either use hook_node_postsave() with the patch, or we use hook_entity_update() and check type = node.

My conclusion is we should keep postsave.

2024-09-16 22:01 UTC, donquixote commented on modules/oe_showcase_subscriptions/tests/src/ExistingSite/EventSubscriptionTest.php
> +    \Drupal::service('path_alias.manager')->cacheClear('node/' . $event->id());
The reason why this cache clear is needed:
The url in the email is correct.
But the url from `$event->toUrl()->setAbsolute()->toString()` is the old one from before saving.
The alias storage and persistent cache already has the correct alias, but the cache property `AliasManager::$lookupMap` still has the old value.

If we work with explicit literal aliases in the assertions, this cacheClear() call can be dropped - TBD.

2024-09-16 22:09 UTC, donquixote commented on modules/oe_showcase_subscriptions/tests/src/ExistingSite/EventSubscriptionTest.php
> +        'url' => $event->toUrl()->setAbsolute()->toString(),
I have two commits that bring you the literal strings and remove the clear cache.
I cannot push for some reason..
Ping me and we can look at it together.

2024-09-18 08:07 UTC, drishu requested changes

2024-09-18 08:07 UTC, drishu commented on modules/oe_showcase_subscriptions/tests/src/ExistingSite/EventSubscriptionTest.php
> +    $make_url = fn (string $path): string => $localized_base_url . $path;
- making a function just for a concatanation is confusing,
- drone is red

2024-09-18 08:07 UTC, drishu commented on modules/oe_showcase_subscriptions/oe_showcase_subscriptions.module
> +function oe_showcase_subscriptions_node_postsave(NodeInterface $node) {
yes, unfortunately there is no hook after entity_update so we have to use this

2024-09-19 15:38 UTC, AaronGilMartinez commented on modules/oe_showcase_subscriptions/tests/src/ExistingSite/EventSubscriptionTest.php
> +    $make_url = fn (string $path): string => $localized_base_url . $path;
@donquixote did changes and drone green

2024-09-20 07:55 UTC, drishu approved these changes

2024-09-25 10:47 UTC, merged