OEL-3424: Added h1 tags on search and homepage.
openeuropa/oe_showcase pull request #277
Opened 2024-10-15 00:34 UTC by tibi2303

2024-10-23 10:11 UTC, drishu requested changes

2024-10-23 10:11 UTC, drishu commented on themes/oe_showcase_theme/oe_showcase_theme.theme
> +function oe_showcase_theme_preprocess_page(array &$variables): void {
since the ticket asked for "We don't use the default block" then this is ok, only one problem, if I visit the front page I dont see any h1

2024-10-23 10:11 UTC, drishu commented on modules/oe_showcase_search/tests/src/ExistingSiteJavascript/SearchFiltersTest.php
> +    $search_title = $assert_session->elementExists('css', 'h1.visually-hidden');
$search_title is not used

2024-10-23 10:11 UTC, drishu commented on themes/oe_showcase_theme/templates/node/node--search-result.html.twig
> +  title_tag: 'h2',
composer lock has 1.16.0 for oebt but I still see h2 in the results list

2024-10-23 10:11 UTC, drishu commented on tests/src/ExistingSite/FrontPageHeadingTest.php
> +    $config_factory->set('page.front', '/node/1')->save();
I tried without, works

2024-10-23 10:11 UTC, drishu commented on tests/src/ExistingSite/FrontPageHeadingTest.php
> +    $this->assertFrontPageH1();
you dont need a separate method as there wont be any repetition

2024-10-23 10:11 UTC, drishu commented on tests/src/ExistingSite/FrontPageHeadingTest.php
> +    $this->assertNotNull($h1);
these lines do the same thing twice

2024-10-23 10:11 UTC, drishu commented on tests/src/ExistingSite/FrontPageHeadingTest.php
> +class FrontPageHeadingTest extends ShowcaseExistingSiteTestBase {
```suggestion
class FrontPageTest extends ShowcaseExistingSiteTestBase {
```
lets name the class more generic, we might add more stuff in the future, the method name can stay the same

2024-10-23 17:04 UTC, tibi2303 commented on themes/oe_showcase_theme/oe_showcase_theme.theme
> +function oe_showcase_theme_preprocess_page(array &$variables): void {
yeah, on the dev env the front is a redirect... is not actually front.. if you dump the var in this function you will see is_front -> false.

2024-10-23 17:49 UTC, tibi2303 commented on themes/oe_showcase_theme/templates/node/node--search-result.html.twig
> +  title_tag: 'h2',
that's for the main cards in the listing, not for the main heading, they were h1...

2024-10-23 18:12 UTC, tibi2303 commented on tests/src/ExistingSite/FrontPageHeadingTest.php
> +    $config_factory->set('page.front', '/node/1')->save();
on drone it fails.. tested on a new env and it's failing idk..

2024-10-23 18:33 UTC, tibi2303 commented on tests/src/ExistingSite/FrontPageHeadingTest.php
> +class FrontPageHeadingTest extends ShowcaseExistingSiteTestBase {
done.

2024-10-23 18:33 UTC, tibi2303 commented on tests/src/ExistingSite/FrontPageHeadingTest.php
> +    $this->assertNotNull($h1);
done.

2024-10-23 18:33 UTC, tibi2303 commented on tests/src/ExistingSite/FrontPageHeadingTest.php
> +    $this->assertFrontPageH1();
done.

2024-10-23 18:33 UTC, tibi2303 commented on modules/oe_showcase_search/tests/src/ExistingSiteJavascript/SearchFiltersTest.php
> +    $search_title = $assert_session->elementExists('css', 'h1.visually-hidden');
done.

2024-10-24 15:33 UTC, drishu requested changes
the reason the update fails in drone is because you alter configuration for fresh install but dont provide an update path for existing installations

2024-10-24 15:33 UTC, drishu commented on modules/oe_showcase_default_content/content/node/f63f9269-b08b-47dc-ad12-5fa53a026a54.yml
> +      pathauto: 1
this is not needed

2024-10-24 15:33 UTC, drishu commented on tests/src/ExistingSite/FrontPageTest.php
> + * Class to test the presence of H1 on the front page.
update also he class comment

2024-10-24 15:33 UTC, drishu commented on themes/oe_showcase_theme/templates/node/node--search-result.html.twig
> +  title_tag: 'h2',
no, I mean the card titles are still h1

2024-10-24 15:33 UTC, drishu commented on config/install/system.site.yml
> +  front: /node/5
normally when working in projects you would set system.site on prod and ignore this config in dev, but here we have a different situation, we need this file, but we can't hardcode node IDs. The issue is that the url alias here needs to be normalized, so lets add another task in oe_showcase_install_tasks_alter and normalize like its done in SiteInformationForm::validateForm(), like this, every install this will be normalized

2024-10-28 09:28 UTC, drishu commented on config/install/system.site.yml
> +  front: /node/5
seems oe_showcase_install_tasks_alter runs before config install

2024-10-28 13:29 UTC, drishu approved these changes

2024-11-05 12:34 UTC, merged