OEL-307: Integrate User Profile feature
openeuropa/oe_showcase pull request #28
Opened 2021-10-20 12:55 UTC by cmarcmar

## OEL-307

### Description
Integrate User Profile feature.

### Change log

- Added:
  - legal
  - purge_users
  - user_field_anonymize
  - user_fields_visibility
  - search API user profile backend
  - views.view.showcase_users

2021-11-18 12:52 UTC, drishu requested changes
Pls also export legal configuration

2021-11-18 12:52 UTC, drishu commented on modules/oe_showcase_user_profile/README.md
> +# OpenEuropa Showcase user profile
```suggestion
# OpenEuropa Showcase User Profile
```

2021-11-18 12:52 UTC, drishu commented on modules/oe_showcase_user_profile/README.md
> +The scope of this module is to demo the OpenEuropa user profile feature.
```suggestion
The scope of this module is to showcase the OpenEuropa User Profile feature.
```

2021-11-18 12:52 UTC, drishu commented on oe_showcase.info.yml
> +  - menu_ui
don't add _ui modules, we can enable those when needed in local envs

2021-11-18 12:52 UTC, drishu commented on modules/oe_showcase_user_profile/oe_showcase_user_profile.info.yml
> +  - drupal:user_fields_visibility
order alphabetically

2021-11-18 12:52 UTC, drishu commented on modules/oe_showcase_user_profile/oe_showcase_user_profile.info.yml
> +name: OpenEuropa Showcase user profile
```suggestion
name: OpenEuropa Showcase User Profile
```

2021-11-18 12:52 UTC, drishu commented on modules/oe_showcase_user_profile/oe_showcase_user_profile.info.yml
> +description: 'Demo user profile'
a bit more descriptive here

2021-11-18 12:52 UTC, drishu commented on modules/oe_showcase_user_profile/config/install/search_api.index.showcase_users_index.yml
> +uuid: 778d3ea5-bb3e-4dba-8511-ab2cf1f21704
remove

2021-11-18 12:52 UTC, drishu commented on modules/oe_showcase_user_profile/config/install/search_api.server.showcase_users_server.yml
> +uuid: 00765697-7b62-466d-a6ac-b10426a5be93
remove

2021-11-18 12:52 UTC, drishu commented on modules/oe_showcase_user_profile/config/install/views.view.showcase_users.yml
> +uuid: 802d501f-1c9f-492d-a262-4b7e9db17510
remove

2021-11-18 12:52 UTC, drishu commented on modules/oe_showcase_user_profile/config/install/user_field_anonymize.configuration.yml
> +restrict_to_roles:
These options are not selected in the admin page, try re-exporting, the settings form changed since

2021-11-22 15:12 UTC, cmarcmar commented on oe_showcase.info.yml
> +  - menu_ui
Fixed in OEL-481: https://github.com/openeuropa/oe_showcase/pull/39/commits/60c0d26bd74bc851cf0278f6a6c9c9d8f8079c4e

2021-11-22 15:12 UTC, cmarcmar commented on modules/oe_showcase_user_profile/oe_showcase_user_profile.info.yml
> +  - drupal:user_fields_visibility
Fixed in OEL-481: https://github.com/openeuropa/oe_showcase/pull/39/commits/60c0d26bd74bc851cf0278f6a6c9c9d8f8079c4e

2021-11-22 15:13 UTC, cmarcmar commented on modules/oe_showcase_user_profile/config/install/search_api.index.showcase_users_index.yml
> +uuid: 778d3ea5-bb3e-4dba-8511-ab2cf1f21704
Fixed in OEL-481: https://github.com/openeuropa/oe_showcase/pull/39/commits/7bff9d99e562b6b7d39d2ec18d903d0e16020c56

2021-11-22 15:13 UTC, cmarcmar commented on modules/oe_showcase_user_profile/config/install/search_api.server.showcase_users_server.yml
> +uuid: 00765697-7b62-466d-a6ac-b10426a5be93
Fixed in OEL-481: https://github.com/openeuropa/oe_showcase/pull/39/commits/7bff9d99e562b6b7d39d2ec18d903d0e16020c56

2021-11-22 15:13 UTC, cmarcmar commented on modules/oe_showcase_user_profile/config/install/views.view.showcase_users.yml
> +uuid: 802d501f-1c9f-492d-a262-4b7e9db17510
Fixed in OEL-481: https://github.com/openeuropa/oe_showcase/pull/39/commits/7bff9d99e562b6b7d39d2ec18d903d0e16020c56

2021-11-22 15:55 UTC, cmarcmar commented on modules/oe_showcase_user_profile/config/install/user_field_anonymize.configuration.yml
> +restrict_to_roles:
As discussed with @drishu on teams, we leave this as it is for now.

2021-11-24 14:52 UTC, drishu approved these changes

2021-11-24 14:53 UTC, escuriola approved these changes

2021-11-24 14:54 UTC, abel-santos-corral approved these changes

2021-11-24 15:00 UTC, merged