OEL-593: [oe_showcase] News submodule
openeuropa/oe_showcase pull request #29
Opened 2021-10-20 13:28 UTC by abel-santos-corral

## OPENEUROPA-[OEL-593]

### Description

Create the News submodule, add content type News, new role Editor-

### Change log

- Added: 
new subfolder oe_showcase_news at modules folder. Add there all the config, files and so.

2021-10-27 08:26 UTC, escuriola commented on modules/oe_showcase_news/oe_showcase_news.info.yml
> +name: OpenEuropa Library News
```suggestion
name: OpenEuropa Showcase News
```

2021-10-27 08:26 UTC, escuriola commented on modules/oe_showcase_news/oe_showcase_news.info.yml
> +
add ckeditor dependency

2021-10-27 08:27 UTC, escuriola commented on modules/oe_showcase_news/oe_showcase_news.info.yml
> +name: OpenEuropa Library News
In order to displayed oe_showcase submodules sorted together.

2021-10-29 13:29 UTC, drishu requested changes
Let's also move block.block.pagetitle.yml to the root config folder and add this new content type to it

2021-10-29 13:29 UTC, drishu commented on modules/oe_showcase_news/config/optional/language.content_settings.node.oe_news_simple.yml
> +language_alterable: true
```suggestion
language_alterable: false
```

2021-10-29 13:29 UTC, drishu commented on modules/oe_showcase_news/config/install/field.field.node.oe_news_simple.field_news_content.yml
> +required: true
```suggestion
required: false
```

2021-10-29 13:29 UTC, drishu commented on modules/oe_showcase_news/config/install/field.field.node.oe_news_simple.field_news_image.yml
> +translatable: true
```suggestion
translatable: false
```

2021-10-29 13:29 UTC, drishu commented on modules/oe_showcase_news/config/install/field.field.node.oe_news_simple.field_news_image.yml
> +default_value: {  }
can we add a default value, so we have less images to manage

2021-10-29 13:29 UTC, drishu commented on modules/oe_showcase_news/config/install/field.field.node.oe_news_simple.field_news_publication_date.yml
> +required: true
it makes no sense to have both default value and required configuration
```suggestion
required: false
```

2021-10-29 13:29 UTC, drishu commented on modules/oe_showcase_news/config/install/core.entity_view_display.node.oe_news_simple.default.yml
> +    label: above
lets not show labels for now

2021-10-29 13:29 UTC, drishu commented on modules/oe_showcase_news/config/install/core.entity_view_display.node.oe_news_simple.default.yml
> +    label: above
lets not show labels for now

2021-10-29 13:29 UTC, drishu commented on modules/oe_showcase_news/config/install/core.entity_view_display.node.oe_news_simple.default.yml
> +    label: above
this one we keep for now

2021-10-29 13:29 UTC, drishu commented on modules/oe_showcase_news/config/install/core.entity_view_display.node.oe_news_simple.default.yml
> +    weight: 2
for now lets have this field as last

2021-10-29 13:29 UTC, drishu commented on modules/oe_showcase_news/config/install/core.entity_view_display.node.oe_news_simple.search_result.yml
> +    label: above
hidden

2021-10-29 13:29 UTC, drishu commented on modules/oe_showcase_news/config/install/core.entity_view_display.node.oe_news_simple.search_result.yml
> +    label: above
hidden

2021-10-29 13:29 UTC, drishu commented on modules/oe_showcase_news/config/install/core.entity_view_display.node.oe_news_simple.search_result.yml
> +      format_type: news_full_time_format
```suggestion
      format_type: html_date
```
use this one till we have design

2021-10-29 13:29 UTC, drishu commented on modules/oe_showcase_news/config/install/core.entity_view_display.node.oe_news_simple.default.yml
> +      format_type: news_full_time_format
use short till we have design 
```suggestion
      format_type: short
```

2021-10-29 13:29 UTC, drishu commented on modules/oe_showcase_news/config/install/core.date_format.news_full_time_format.yml
> +id: news_full_time_format
granularity is something you set in the field config, not in the display config, I'm saying this because that's that the ticket asked for.
Doing a new date format is not a bad thing but since we dont have a design we don't know what it will be, so **remove** this

2021-10-29 13:29 UTC, drishu commented on modules/oe_showcase_news/config/install/core.base_field_override.node.oe_news_simple.menu_link.yml
> +langcode: en
what is this for ?

2021-10-29 13:29 UTC, drishu commented on modules/oe_showcase_news/config/install/core.base_field_override.node.oe_news_simple.path.yml
> +status: true
do we need this?, shouldn't we export pathauto settings rather ?

2021-10-29 13:29 UTC, drishu commented on modules/oe_showcase_news/config/install/core.base_field_override.node.oe_news_simple.title.yml
> +status: true
why do we need this ?

2021-11-09 14:48 UTC, drishu requested changes

2021-11-09 14:48 UTC, drishu commented on modules/oe_showcase_news/oe_showcase_news.info.yml
> +  - drupal:views
order these alphabetically

2021-11-09 14:48 UTC, drishu commented on modules/oe_showcase_news/oe_showcase_news.info.yml
> +themes:
remove this

2021-11-09 15:15 UTC, drishu approved these changes

2021-11-09 15:17 UTC, GilNovacomm approved these changes
Approved.

2021-11-09 15:24 UTC, merged