OEL-520: Add page integration test
openeuropa/oe_showcase pull request #30
Opened 2021-10-20 14:46 UTC by GilNovacomm

[OEL-520](https://citnet.tech.ec.europa.eu/CITnet/jira/browse/OEL-520)

### Changes

Config changes:
- Allow `oe_showcase_page.field_body` to reference `oe_document` paragraphs.
- No longer allow `oe_showcase_page.field_body` to reference `oe_timeline` paragraphs.
  This reverts part of OEL-998, see modules/oe_showcase_page/config/install/field.field.node.oe_showcase_page.field_body.yml

New functional test:
- Create new oe_showcase_page node through the UI (node/add/*).
- Set all or most of the fields, and add various example paragraphs in field_body.
- Visit node page, and verify that all values are displayed.

### Merge notes
When merging, ideally we should have separate commits for the config changes and the new test.
As this is not easily possible through the UI, please include the "Changes" part from the PR text in the merge commit message.

2021-12-14 07:53 UTC, drishu requested changes
After rebase please check if any new paragraphs are available.

2021-12-14 07:53 UTC, drishu commented on composer.json
> +        "openeuropa/oe_whitelabel": "1.0.0-alpha1"
```suggestion
        "openeuropa/oe_whitelabel": "1.0.0-alpha2"
```

2021-12-14 07:53 UTC, drishu commented on composer.json
> +            "drupal/core": {
the issue seems to be in ctools, the newer version of that has the fix, so maybe try to upgrade ctools instead of patching

2021-12-14 07:53 UTC, drishu commented on tests/src/Functional/ShowcasePageTest.php
> +class ShowcasePageTest extends BrowserTestBase {
no need for the showcase as there wont be any other page tests then this
```suggestion
class PageTest extends BrowserTestBase {
```

2021-12-14 07:53 UTC, drishu commented on tests/src/Functional/ShowcasePageTest.php
> + * Ensure OE Showcase Pages are created.
Lets be more descriptive as to what is going on in this test
```suggestion
 * Page content creation.
```

2021-12-14 07:53 UTC, drishu commented on tests/src/Functional/ShowcasePageTest.php
> +    'ctools',
you don't need to specify modules that are dependencies of other modules

2021-12-14 07:53 UTC, drishu commented on tests/src/Functional/ShowcasePageTest.php
> +  protected $adminUser;
what is the reasoning behind putting the user entity into a class attribute ?

2021-12-14 07:53 UTC, drishu commented on tests/src/Functional/ShowcasePageTest.php
> +    'access toolbar',
you don't need access to the toolbar, pls use only the ones you need

2021-12-14 07:53 UTC, drishu commented on tests/src/Functional/ShowcasePageTest.php
> +  protected $strictConfigSchema = FALSE;
This happens because of config conflict, so lets create a ticket where we address this issue and remove this one done

2021-12-14 07:53 UTC, drishu commented on tests/src/Functional/ShowcasePageTest.php
> +  protected $node;
this doesn't need to be a class attribute

2021-12-14 07:53 UTC, drishu commented on tests/src/Functional/ShowcasePageTest.php
> +  protected $document;
this doesn't need to be a class attribute

2021-12-14 07:53 UTC, drishu commented on tests/src/Traits/AuthenticationTrait.php
> +  protected function enableForcedLogin(): void {
lets not write unused code

2021-12-14 07:53 UTC, drishu commented on tests/src/Traits/AuthenticationTrait.php
> +    \Drupal::configFactory()->getEditable('cas.settings')->set('forced_login.enabled', FALSE)->save();
if we will be using this in future tests we might create a trait but for now, its not even worth a function because its just one line of code, just add it where you use it

2021-12-14 07:53 UTC, drishu commented on tests/src/Functional/ShowcasePageTest.php
> +    $this->adminUser = $this->drupalCreateUser($this->userPermissions, NULL, TRUE);
```suggestion
  $this->drupalLogin($this->drupalCreateUser([
    'create oe_showcase_page content',
    ..
  ], NULL, TRUE));
```

2021-12-14 07:53 UTC, drishu commented on tests/src/Functional/ShowcasePageTest.php
> +    $node = Node::create($settings);
```suggestion
    $node = Node::create([
      'title' => 'Demo showcase page',
      'type' => 'oe_showcase_page',
      ..
    ]);
```

2021-12-14 07:53 UTC, drishu commented on tests/src/Functional/ShowcasePageTest.php
> +    $pdf_file = file_save_data(file_get_contents(__DIR__ . '/fixtures/example_1.pdf'), 'public://example_1.pdf');
this bit right here deserves its own function because this code refers to creating assets and is not about asserting page, create a helper function and if it will be used in other tests then we can create a trait or base class.

2021-12-14 07:53 UTC, drishu commented on tests/src/Functional/ShowcasePageTest.php
> +    $this->assertNotEmpty($this->node, 'Node found in database.');
this brings no value, if the node is empty for some reason (I dont see why it would be since we controle that scope) the asserts below would fail.

2021-12-14 07:53 UTC, drishu commented on tests/src/Functional/ShowcasePageTest.php
> +    $this->assertEquals(
you can just to pageTextContains instead of all these below, you just assert the content, you don't need the crawler to traverse html structure

2021-12-14 07:53 UTC, drishu commented on tests/src/Functional/ShowcasePageTest.php
> +    $crawler->filter('div.accordion > div.accordion-item')->each(
stay away from loops, it makes the test more fragile, often code that should fail wont, because you loop through what is instead of what should be

2021-12-14 17:52 UTC, GilNovacomm commented on tests/src/Functional/ShowcasePageTest.php
> +    $this->assertEquals(
I've used the crawler to assure the content is actually where it is supposed to be instead of just confirming they exists.
I've removed, maybe we should use this on oe_whitelabel only?

2021-12-15 14:26 UTC, GilNovacomm commented on composer.json
> +            "drupal/core": {
I've updated Ctools to the latest DEV, then the file_link module complains of the same issue. There is a patch still underwork (https://www.drupal.org/project/file_link/issues/3147517) to fix it.
Unfortunately the patch is still necessary.

2022-01-25 09:26 UTC, donquixote commented on composer.json
> +         },
Seems like this should be in a separate issue, or not?

2022-01-25 09:30 UTC, donquixote commented
For the fixtures: Can we move the pdf to `tests/fixtures/` instead of `tests/src/ExistingSite/fixtures/` ?

2022-01-26 00:38 UTC, donquixote requested changes
Hi! Overall not bad, but I think we need to discuss a bit about what exactly we want to test here.
Is it enough to have just one method with create (via API calls) then edit + view? Or should we have more? Not sure. Perhaps good enough for a start? See also my comment in teams group channel.

2022-01-26 00:38 UTC, donquixote commented on composer.json
> +            "Drupal\\Tests\\oe_showcase_page\\": "./tests/src/"
This looks wrong to me:
1. Determine if really necessary. If you remove it, what happens?
2. The directory would have to be `modules/oe_showcase_page/tests/src/`, not `tests/src/`.

2022-01-26 00:38 UTC, donquixote commented on modules/oe_showcase_page/tests/src/ExistingSite/PageTest.php
> +  public function testCreateShowCasePage() {
Seems like a mismatch of method name vs doc description.
Was the description copied from elsewhere?

It seems this method does the following:
- Create a oe_showcase_page node and a document media using an API method.
- Use the edit form to fill in some values.
- Visit the node page to verify that all the modified field values are displayed.

So it seems this is mostly about edit + view, not so much about the creation process.
For the creation process we would instead visit the node/add/oe_showcase_page form and fill in the values there, instead of creating via the API.

2022-01-26 00:38 UTC, donquixote commented on modules/oe_showcase_page/tests/src/ExistingSite/PageTest.php
> +    $pdf_file = file_save_data(file_get_contents(__DIR__ . '/fixtures/example_1.pdf'), 'public://example_1.pdf');
`file_save_data()` is marked as deprecated.
We should use an injected service.

2022-01-26 00:38 UTC, donquixote commented on modules/oe_showcase_page/tests/src/ExistingSite/PageTest.php
> +    // // Assert Rich Text Body.
Duplicate `//` :)

2022-01-26 00:38 UTC, donquixote commented on modules/oe_showcase_page/config/install/field.field.node.oe_showcase_page.field_body.yml
> +    - paragraphs.paragraphs_type.oe_document
Strange, why is this part of this pull request?
I thought we only want to add a test?

(same for other config noise)

2022-01-26 00:38 UTC, donquixote commented on modules/oe_showcase_page/tests/src/ExistingSite/PageTest.php
> +    $this->markEntityTypeForCleanup('file');
Why?

2022-01-26 00:38 UTC, donquixote commented on modules/oe_showcase_page/tests/src/ExistingSite/PageTest.php
> +    $this->markEntityTypeForCleanup('file');
Hmm I understand now what this does.
But having it in this position has no effect whatsoever, because all the entities are already created.
The entities _are_ cleaned up after the test, but the reason is not what you think:
- The test user is cleaned up because `UserCreationTrait` calls `$this->markEntityForCleanup($user);` which registers the user for cleanup.
- `node_user_predelete()` deletes all content from this user.
- some other entities are deleted as a side effect, e.g. path aliases.

If we change the node author id to 1 (admin), then the node will remain in the database.

If we want to rely on this `markEntityTypeForCleanup()`, we need to call it at the beginning before creating any entities.

2022-01-26 00:41 UTC, donquixote commented on tests/src/Functional/ShowcasePageTest.php
> +    'access toolbar',
True.
Also the "create " perms seem to be currently not used in the test, because we create those entities via API calls.

2022-01-26 00:48 UTC, donquixote commented on modules/oe_showcase_page/tests/src/ExistingSite/PageTest.php
> +  public function assetTestPdfFile(): File {
Better method name might be createPdfFileEntity() ?
Also in the comment refer to "file entity" to distinguish from the media entity.

2022-01-26 00:52 UTC, donquixote commented on modules/oe_showcase_page/tests/src/ExistingSite/PageTest.php
> +    return $pdf_file;
Btw, I noticed that the pdf files are not being cleaned up :)
The build/sites/default/files dir fills up with leftover pdfs.

2022-02-01 08:52 UTC, GilNovacomm commented on modules/oe_showcase_page/config/install/field.field.node.oe_showcase_page.field_body.yml
> +    - paragraphs.paragraphs_type.oe_document
Hey Andreas, it seems that the paragraph document config was not kept in previous rebases or during the merge in 1.x. The feature is already merged and there's no other remaining PR for showcase page we'll need to correct this config on this PR.

2022-02-03 12:20 UTC, drishu submitted a review, later dismissed

2022-02-03 12:25 UTC, donquixote submitted a review, later dismissed

2022-02-03 15:46 UTC, drishu approved these changes

2022-02-03 15:50 UTC, donquixote approved these changes

2022-02-03 15:53 UTC, merged