OEL-603: Create OpenEuropa Event
openeuropa/oe_showcase pull request #33
Opened 2021-10-26 11:01 UTC by GilNovacomm

## OEL-603

### Description

Initial development of the OE Showcase event.

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2021-10-27 08:29 UTC, escuriola commented on modules/oe_showcase_event/oe_showcase_event.info.yml
> +
add ckeditor dependency

2021-10-27 14:03 UTC, abel-santos-corral commented on modules/oe_showcase_event/README.md
> +# OpenEuropa Showcase Page
Rename this.

2021-10-27 14:14 UTC, abel-santos-corral commented on modules/oe_showcase_event/oe_showcase_event.install
> +function oe_showcase_event_install($is_syncing) {
Add the ": void" in the function.

2021-11-04 07:44 UTC, abel-santos-corral requested changes
@GilNovacomm please, configure a default image as we did per News content type.

2021-11-04 07:44 UTC, abel-santos-corral commented on modules/oe_showcase_event/config/install/field.storage.node.field_oe_showcase_event_url.yml
> +translatable: true
```suggestion
translatable: false
```

2021-11-04 07:44 UTC, abel-santos-corral commented on modules/oe_showcase_event/config/install/field.storage.node.field_oe_showcase_event_registra.yml
> +translatable: true
```suggestion
translatable: false
```

2021-11-04 07:44 UTC, abel-santos-corral commented on modules/oe_showcase_event/config/install/field.storage.node.field_oe_showcase_event_document.yml
> +translatable: true
```suggestion
translatable: false
```

2021-11-04 07:44 UTC, abel-santos-corral commented on modules/oe_showcase_event/config/install/field.storage.node.field_oe_showcase_event_date.yml
> +translatable: true
```suggestion
translatable: false
```

2021-11-04 07:44 UTC, abel-santos-corral commented on modules/oe_showcase_event/config/install/field.field.node.oe_showcase_event.field_oe_showcase_event_url.yml
> +translatable: true
```suggestion
translatable: false
```

2021-11-04 07:44 UTC, abel-santos-corral commented on modules/oe_showcase_event/config/install/field.field.node.oe_showcase_event.field_oe_showcase_event_location.yml
> +translatable: true
```suggestion
translatable: false
```

2021-11-04 07:44 UTC, abel-santos-corral commented on modules/oe_showcase_event/config/install/field.field.node.oe_showcase_event.field_oe_showcase_event_image.yml
> +translatable: true
```suggestion
translatable: false
```

2021-11-04 07:44 UTC, abel-santos-corral commented on modules/oe_showcase_event/config/install/field.field.node.oe_showcase_event.field_oe_showcase_event_document.yml
> +translatable: true
```suggestion
translatable: false
```

2021-11-04 07:44 UTC, abel-santos-corral commented on modules/oe_showcase_event/config/install/field.field.node.oe_showcase_event.field_oe_showcase_event_date.yml
> +translatable: true
```suggestion
translatable: false
```

2021-11-04 07:44 UTC, abel-santos-corral commented on modules/oe_showcase_event/config/install/core.entity_view_display.node.oe_showcase_event.default.yml
> +    label: above
```suggestion
    label: hidden
```

2021-11-04 07:44 UTC, abel-santos-corral commented on modules/oe_showcase_event/config/install/core.entity_view_display.node.oe_showcase_event.default.yml
> +    label: above
```suggestion
    label: hidden
```

2021-11-04 07:44 UTC, abel-santos-corral commented on modules/oe_showcase_event/config/install/core.entity_view_display.node.oe_showcase_event.search_result.yml
> +    label: above
```suggestion
    label: hidden
```

2021-11-04 07:44 UTC, abel-santos-corral commented on modules/oe_showcase_event/config/install/core.entity_view_display.node.oe_showcase_event.search_result.yml
> +    label: above
```suggestion
    label: hidden
```

2021-11-04 07:44 UTC, abel-santos-corral commented on modules/oe_showcase_event/config/install/core.entity_view_display.node.oe_showcase_event.teaser.yml
> +    label: above
```suggestion
    label: hidden
```

2021-11-04 07:44 UTC, abel-santos-corral commented on modules/oe_showcase_event/config/install/core.entity_view_display.node.oe_showcase_event.teaser.yml
> +    label: above
```suggestion
    label: hidden
```

2021-11-04 07:44 UTC, abel-santos-corral commented on modules/oe_showcase_event/config/install/core.entity_view_display.node.oe_showcase_event.search_result.yml
> +      format_type: medium
```suggestion
      format_type: html_date
```

2021-11-04 07:44 UTC, abel-santos-corral commented on modules/oe_showcase_event/config/install/core.entity_view_display.node.oe_showcase_event.default.yml
> +      format_type: medium
```suggestion
      format_type: short
```

2021-11-09 15:46 UTC, drishu requested changes

2021-11-09 15:46 UTC, drishu commented on modules/oe_showcase_event/config/install/field.field.node.oe_showcase_event.field_oe_showcase_event_registra.yml
> +translatable: false
Links can have translations for sure

2021-11-09 15:46 UTC, drishu commented on modules/oe_showcase_event/config/install/field.storage.node.field_oe_showcase_event_image.yml
> +translatable: true
false

2021-11-09 15:46 UTC, drishu commented on modules/oe_showcase_event/config/install/field.storage.node.field_oe_showcase_event_type.yml
> +translatable: true
false

2021-11-09 15:46 UTC, drishu commented on modules/oe_showcase_event/oe_showcase_event.info.yml
> +  - rdf_skos:rdf_skos
order alphabetically

2021-11-09 15:46 UTC, drishu commented on modules/oe_showcase_event/oe_showcase_event.module
> +  $plugins['target']['default_value'] = '_blank';
why do we need this ?

2021-11-09 15:46 UTC, drishu commented on modules/oe_showcase_event/config/install/field.field.node.oe_showcase_event.field_oe_showcase_event_image.yml
> +default_value: {  }
a default image would be good to not set any images for the exported items

2021-11-09 15:53 UTC, GilNovacomm commented on modules/oe_showcase_event/oe_showcase_event.module
> +  $plugins['target']['default_value'] = '_blank';
To set _blank as default value, though it is possible to set on the field configuration it is a known bug on the link attributes module.

2023-10-13 12:32 UTC, brummbar commented
Closing as outdated.

2023-10-13 12:32 UTC, closed without merging