OEL-702: Create Events default content
openeuropa/oe_showcase pull request #34
Opened 2021-10-26 19:08 UTC by GilNovacomm

## OEL-702

### Description

Create default content for OE Showcase Event
### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2021-10-27 14:58 UTC, abel-santos-corral requested changes

2021-10-27 14:58 UTC, abel-santos-corral commented on modules/oe_showcase_event/oe_showcase_event.info.yml
> +    - block.block.pagetitle
This has to be moved to the default_content module (this is the last module activated. There has more sense

2021-10-27 14:58 UTC, abel-santos-corral commented on modules/oe_showcase_page/config/install/block.block.pagetitle.yml
>    'entity_bundle:node':
Please, Gil, move this block to the default content, and there it will be used by all the future content types and the ones we have. So then whatever module is created is not messing with this. We concentrate all in default_content module of oe_showcase.

2021-10-28 07:43 UTC, GilNovacomm commented on modules/oe_showcase_event/oe_showcase_event.info.yml
> +    - block.block.pagetitle
Hey Abel, how about instead we create a Title block per content type? This way instead of concentrating all in the same block (which could make it hard to update when a feature is uninstalled) we give more flexibility to the user to decide which feature title they would like shown, also when uninstalling that particular feature it's block would also get removed.

2021-11-04 08:08 UTC, abel-santos-corral approved these changes
Changes had been done. Ready for QA.

2023-10-13 12:32 UTC, closed without merging

2023-10-13 12:32 UTC, brummbar commented
Closing as outdated.