OEL-594: [oe_showcase] views
openeuropa/oe_showcase pull request #35
Opened 2021-10-27 07:40 UTC by abel-santos-corral

## OPENEUROPA-[OEL-594]

### Description

View for news.

2021-12-15 09:04 UTC, drishu requested changes

2021-12-15 09:04 UTC, drishu commented on modules/oe_showcase_default_content/oe_showcase_default_content.info.yml
> +    # OE Showcase Search
All these that are not News related seem out of place, either rebase the epic or drop the commits that adds this (if you add a new commit that removes this then you will have a conflict when trying to merge or worse, the epic PR will try to remove these)

2021-12-15 09:04 UTC, drishu commented on modules/oe_showcase_default_content/oe_showcase_default_content.info.yml
> +    - 0708ba1e-f163-4758-a201-e5c087079b1b
to many, we already demo the pagging in the search page, lets add just 5 items, all with same image

2021-12-15 09:04 UTC, drishu commented on modules/oe_showcase_news/config/install/block.block.showcase_facets_form.yml
> +  live_total: true
false

2021-12-15 09:04 UTC, drishu commented on modules/oe_showcase_news/config/install/block.block.showcase_facets_form.yml
> +  id: 'facets_form:search_api:views_page__showcase_search__showcase_search_page'
the id seems odd, shouldn't this be for the news view ?

2021-12-15 09:04 UTC, drishu commented on modules/oe_showcase_news/config/install/block.block.showcase_facets_form.yml
> +    id: request_path
I think the entire file has no place here

2021-12-15 09:04 UTC, drishu commented on modules/oe_showcase_news/config/install/core.entity_view_display.node.oe_news_simple.search_result.yml
> +    type: text_trimmed
why don't we like the summary ?

2021-12-15 09:04 UTC, drishu commented on modules/oe_showcase_search/config/install/block.block.showcase_facets_form.yml
> +  live_total: true
false

2021-12-15 09:04 UTC, drishu commented on modules/oe_showcase_news/oe_showcase_news.info.yml
> +    - block.block.showcase_facets_form
you should remove this

2021-12-15 09:04 UTC, drishu commented on modules/oe_showcase_news/templates/node--oe-news-simple.html.twig
> +{% set badges = [] %}
this template is outdated, update the news epic, and copy what was done in the search template

2021-12-15 09:04 UTC, drishu commented on modules/oe_showcase_news/templates/node--oe-news-simple.html.twig
> +{#
the template suggestion used is false, this is applying also the the node view, it should only apply to search results

2021-12-15 11:34 UTC, GilNovacomm commented on modules/oe_showcase_default_content/oe_showcase_default_content.info.yml
> +    - 0708ba1e-f163-4758-a201-e5c087079b1b
These content related changes were done on OEL-596. I've updated this branch and removed the excess default content. 594 will be rebased to contain these changes.

2021-12-15 11:35 UTC, GilNovacomm commented on modules/oe_showcase_news/config/install/block.block.showcase_facets_form.yml
> +  live_total: true
This file will be removed it is not part of news.

2021-12-15 11:36 UTC, GilNovacomm commented on modules/oe_showcase_news/config/install/block.block.showcase_facets_form.yml
> +  id: 'facets_form:search_api:views_page__showcase_search__showcase_search_page'
This file should not have been added to news. I'll remove it

2021-12-15 11:40 UTC, GilNovacomm commented on modules/oe_showcase_news/oe_showcase_news.info.yml
> +    - block.block.showcase_facets_form
removed: block.block.showcase_facets_form

2021-12-15 12:06 UTC, GilNovacomm commented on modules/oe_showcase_news/templates/node--oe-news-simple.html.twig
> +{#
Agreed updated it to be used only with search results.

2023-10-13 12:32 UTC, brummbar commented
Closing as outdated.

2023-10-13 12:32 UTC, closed without merging