OEL-484: Add User Profile fields
openeuropa/oe_showcase pull request #36
Opened 2021-10-28 13:31 UTC by cmarcmar

## OEL-484

### Description

Add User Profile fields and mock content.

### Change log

- Added:
  -  oe_authentication_user_fields
  -  mock content

2021-11-18 13:27 UTC, drishu requested changes
I can't see much in the users listing page, anyway, this should be revisited after 307 merge and rebase

2021-11-18 13:27 UTC, drishu commented on modules/oe_showcase_default_content/oe_showcase_default_content.info.yml
> +    - 0bcf6fce-80fe-4634-bd38-b58cc7ff6cfb
Use just one image, make it a default for the field (easier to manage)

2021-11-24 08:54 UTC, cmarcmar commented on modules/oe_showcase_default_content/oe_showcase_default_content.info.yml
> +    - 0bcf6fce-80fe-4634-bd38-b58cc7ff6cfb
As discuss we will keep it as it is for now since the dev is already done and there is not much time left in the issue.

2021-12-06 14:51 UTC, drishu requested changes

2021-12-06 14:51 UTC, drishu commented on modules/oe_showcase_user_profile/config/install/field.field.user.user.field_bio.yml
> +translatable: false
true

2021-12-06 14:51 UTC, drishu commented on modules/oe_showcase_user_profile/config/install/field.field.user.user.field_current_position.yml
> +translatable: false
true

2021-12-06 14:51 UTC, drishu commented on modules/oe_showcase_user_profile/config/install/field.storage.user.field_date_of_birth.yml
> +translatable: true
false

2021-12-06 14:51 UTC, drishu commented on modules/oe_showcase_user_profile/config/install/field.storage.user.field_gender.yml
> +translatable: true
false

2021-12-06 14:51 UTC, drishu commented on modules/oe_showcase_user_profile/config/install/field.storage.user.field_nationality.yml
> +translatable: true
false

2021-12-06 14:51 UTC, drishu commented on modules/oe_showcase_user_profile/config/install/field.storage.user.field_working_languages.yml
> +translatable: true
false

2021-12-06 14:51 UTC, drishu commented on modules/oe_showcase_user_profile/config/install/field.field.user.user.field_city_country.yml
> +translatable: false
true

2021-12-06 14:51 UTC, drishu commented on modules/oe_showcase_user_profile/tests/src/Functional/IntegrationTest.php
> +    $page->fillField('edit-field-date-of-birth-0-value-date', '2000-10-10');
we assume front facing here so lets use human readable labels here instead of machine names or ids

2021-12-06 14:51 UTC, drishu commented on modules/oe_showcase_user_profile/tests/src/Functional/IntegrationTest.php
> +    $page->fillField('Current position', 'Example position');
we are missing the skos fields

2021-12-06 14:51 UTC, drishu commented on modules/oe_showcase_user_profile/tests/src/Functional/IntegrationTest.php
> +
we also have a user listing, add a test that access the page and asserts the user fields there (the ones that should display, also the sort (for this you will need 2 users

2021-12-06 14:51 UTC, drishu commented on modules/oe_showcase_user_profile/tests/src/Functional/IntegrationTest.php
> +  protected $strictConfigSchema = FALSE;
it fails without this ? what's the message ?

2021-12-06 14:51 UTC, drishu commented on modules/oe_showcase_user_profile/tests/src/Functional/IntegrationTest.php
> +
Whitespace found at end of line

2021-12-06 14:51 UTC, drishu commented on oe_showcase.info.yml
> +    - user_field_anonymize.configuration
user_field_anonymize.settings

2021-12-06 14:51 UTC, drishu commented on oe_showcase.info.yml
> +    - user.settings
how about the boy-scout rule and add also the other config elements from that folder

2021-12-06 14:51 UTC, drishu commented on modules/oe_showcase_user_profile/tests/src/Functional/IntegrationTest.php
> + * Simple test to ensure the user fields are created and visible.
```suggestion
 * Tests the User Profile feature integration.
```

2021-12-06 14:51 UTC, drishu commented on modules/oe_showcase_user_profile/tests/src/Functional/IntegrationTest.php
> +    'system',
sort these

2021-12-06 14:51 UTC, drishu commented on modules/oe_showcase_user_profile/tests/src/Functional/IntegrationTest.php
> +    $this->drupalLogin($user);
"Button with id|name|label|value "Log in" not found."
I'm guessing your missing something in phpunit.xml.dist

2021-12-06 14:52 UTC, drishu requested changes

2021-12-06 14:52 UTC, drishu commented on composer.json
> +               "https://www.drupal.org/project/drupal/issues/3139335": "https://www.drupal.org/files/issues/2021-02-05/3139335-4.patch"
why is this here ?

2021-12-07 13:35 UTC, GilNovacomm commented on modules/oe_showcase_user_profile/tests/src/Functional/IntegrationTest.php
> +  protected $strictConfigSchema = FALSE;
It fails due to easy_breadcrumb settings:

1) Drupal\Tests\oe_showcase_user_profile\Functional\IntegrationTest::testIntegration
Drupal\Core\Config\Schema\SchemaIncompleteException: Schema errors for easy_breadcrumb.settings with the following errors: easy_breadcrumb.settings:segment_display_limit missing schema

2021-12-22 10:49 UTC, drishu requested changes

2021-12-22 10:49 UTC, drishu commented on modules/oe_showcase_user_profile/config/install/field.storage.user.field_working_languages.yml
> +translatable: true
I see the thumb up but I don't see the change

2021-12-22 10:49 UTC, drishu commented on modules/oe_showcase_user_profile/config/install/field.field.user.user.field_profile_image.yml
> +translatable: false
```suggestion
translatable: true
```

2021-12-22 10:49 UTC, drishu commented on composer.json
> +        "drupal/field_group": "^3.2",
remove this for now

2021-12-22 10:49 UTC, drishu commented on modules/oe_showcase_user_profile/config/install/core.entity_form_display.user.user.default.yml
> +  field_group:
don't do things that belong to the edit form theming ticket here

2021-12-22 10:49 UTC, drishu commented on modules/oe_showcase_user_profile/config/install/core.entity_view_display.user.user.default.yml
> +  field_group:
remove anything field group related

2021-12-22 10:49 UTC, drishu commented on modules/oe_showcase_user_profile/config/install/core.entity_form_display.user.user.default.yml
> +    type: skos_concept_entity_reference_autocomplete
```suggestion
    type: skos_concept_entity_reference_options_select
```

2021-12-22 10:49 UTC, drishu commented on modules/oe_showcase_user_profile/config/install/core.entity_form_display.user.user.default.yml
> +    type: skos_concept_entity_reference_autocomplete
```suggestion
    type: skos_concept_entity_reference_options_select
```

2021-12-22 10:49 UTC, drishu commented on modules/oe_showcase_user_profile/config/install/core.entity_form_display.user.user.default.yml
> +    type: skos_concept_entity_reference_autocomplete
```suggestion
    type: skos_concept_entity_reference_options_select
```

2021-12-22 10:49 UTC, drishu commented on modules/oe_showcase_user_profile/oe_showcase_user_profile.info.yml
> +  - drupal:field_group
nothing group related for now

2021-12-22 10:49 UTC, drishu commented on modules/oe_showcase_user_profile/oe_showcase_user_profile.install
> -function oe_showcase_user_profile_install() {
why do we remove this ?

2021-12-22 10:49 UTC, drishu commented on modules/oe_showcase_user_profile/tests/src/Functional/IntegrationTest.php
> +    $page->pressButton('Create new account');
fields are missing

2022-01-05 12:44 UTC, GilNovacomm commented on modules/oe_showcase_user_profile/oe_showcase_user_profile.install
> -function oe_showcase_user_profile_install() {
Its has not been removed it was updated:
`function oe_showcase_user_profile_install($is_syncing): `
https://www.drupal.org/node/3098920

2022-01-21 08:48 UTC, abel-santos-corral commented on modules/oe_showcase_user_profile/config/install/field.field.user.user.field_bio.yml
> +translatable: true
```suggestion
translatable: false
```

2022-01-21 08:48 UTC, abel-santos-corral commented on modules/oe_showcase_user_profile/config/install/field.field.user.user.field_city_country.yml
> +translatable: true
```suggestion
translatable: false
```

2022-01-21 08:48 UTC, abel-santos-corral commented on modules/oe_showcase_user_profile/config/install/field.field.user.user.field_current_position.yml
> +translatable: true
```suggestion
translatable: false
```

2022-01-21 13:35 UTC, Maxfire approved these changes

2022-01-24 13:30 UTC, drishu commented on modules/oe_showcase_user_profile/config/install/field.field.user.user.field_bio.yml
> +translatable: true
this is a multilanguage profile the field instance needs to be translatable

2022-01-24 13:32 UTC, abel-santos-corral approved these changes

2022-01-25 14:51 UTC, merged