OEL-606: OpenEuropa Event Search
openeuropa/oe_showcase pull request #37
Opened 2021-10-29 08:03 UTC by GilNovacomm

## OPENEUROPA-[OEL-606]

### Description

OpenEuropa Event Search

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2021-11-10 15:16 UTC, drishu requested changes
To many files and nodes, add default values and less nodes, 5 are enough

2021-11-10 15:16 UTC, drishu commented on modules/oe_showcase_event/config/install/views.view.showcase_events.yml
> +                combine_rewrite: "Event date Asc|Date asc\r\nEvent date Desc|Date desc\r\nTitle Asc|A-Z\r\nTitle Desc|Z-A"
its clear that its about event, remove "Event" occurrences from the string

2021-11-10 15:16 UTC, drishu commented on modules/oe_showcase_event/oe_showcase_event.info.yml
> +  - drupal:views
modules like views are enabled by the profile already, skip what is enabled already and order the list alphabetically

2021-11-10 15:16 UTC, drishu commented on modules/oe_showcase_event/oe_showcase_event.install
> +  // Remove content type and its nodes.
remove the uninstall, will never be used

2021-11-10 15:16 UTC, drishu commented on modules/oe_showcase_event/oe_showcase_event.module
> +  $plugins['target']['default_value'] = '_blank';
remove this, the options need to be exported not hardcoded

2021-11-10 15:16 UTC, drishu commented on modules/oe_showcase_event/oe_showcase_event.module
> +    if (isset($form['facets']['country'][0]['country']['#options'])) {
there shouldn't be fixes in this repository, if there is any problem report it in a ticket and lets analyse

2021-11-10 15:16 UTC, drishu commented on modules/oe_showcase_event/templates/node--oe-showcase-event--search-result.html.twig
> +{% if content.field_oe_showcase_event_image[0] is defined and content.field_oe_showcase_event_image[0]['#markup'] is not empty %}
there is a new version now:

1. create a PR for updating the epic
2. implement solution from https://github.com/openeuropa/oe_showcase/blob/1.x/modules/oe_showcase_search/templates/node--search-result.html.twig

2021-11-10 15:16 UTC, drishu commented on modules/oe_showcase_event/config/install/facets.facet.city.yml
> +langcode: en
the city facet should only appear when the country one is selected

2021-11-12 10:38 UTC, GilNovacomm commented on modules/oe_showcase_event/oe_showcase_event.module
> +  $plugins['target']['default_value'] = '_blank';
I've removed. But note that as I've mentioned before, it is not possible to set a default value for the target so when a user creates a new event they will have to intentionally set target as blank otherwise the external event link will  navigate them away from the site.

2021-11-12 15:46 UTC, GilNovacomm commented on modules/oe_showcase_event/config/install/facets.facet.city.yml
> +langcode: en
It is already set. It has the same issue as in dates, the hide feature of facets-form is not working. I've opened a ticket for this and will update on Jira.

2021-11-12 17:19 UTC, GilNovacomm commented on modules/oe_showcase_event/config/install/views.view.showcase_events.yml
> +                combine_rewrite: "Event date Asc|Date asc\r\nEvent date Desc|Date desc\r\nTitle Asc|A-Z\r\nTitle Desc|Z-A"
I've removed all the files introduced with Events and since its not possible to set a default value for the file field I've set an existing pdf file on the default contents.

2023-10-13 12:32 UTC, brummbar commented
Closing as outdated.

2023-10-13 12:32 UTC, closed without merging