OEL-302: Create default content for oe_showcase_page
openeuropa/oe_showcase pull request #4
Opened 2021-08-30 13:14 UTC by escuriola

## OPENEUROPA-OEL-306

### Description

Added required features to allow to store default content for showcase library.

### Change log

- Added: default content for oe_showcase_page module
- Changed:
- Deprecated:
- Removed: 
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2021-09-28 14:00 UTC, abel-santos-corral requested changes
Added comments at the PR regarding the menus label must be equal to title. Some authoring info could be hidden, and Block title could be added. To be checked.

2021-09-28 14:00 UTC, abel-santos-corral commented on modules/oe_showcase_page/oe_showcase_page.info.yml
> +    # - editor.editor.full_html
If not used, better eliminate it.

2021-09-29 07:20 UTC, drishu commented
> Added comments at the PR regarding the menus label must be equal to title.
Yes
> Some authoring info could be hidden,
No, not yet, we don't have specs for that, we will see in the review demo
> and Block title could be added. To be checked.
which block ?

2021-09-29 07:27 UTC, abel-santos-corral commented
@drishu the block would be Page title block. So when visiting an OE page, to see the title. For now, even for search content type, when visiting a node, the title is not shown.

2021-09-29 07:59 UTC, drishu commented
> @drishu the block would be Page title block. So when visiting an OE page, to see the title. For now, even for search content type, when visiting a node, the title is not shown.

Agreed

2021-09-29 11:05 UTC, drishu reviewed
- Place the title for the Page content type, but not for <front>
- Lets use OpenEuropa instead of Openeuropa or Open Europa everywhere
- Remove the body from the homepage
- For the content type lets hide the labels of the fields
- Use below for the homepage body:
`<div class="paragraph paragraph--type--oe-rich-text paragraph--view-mode--default">
            <p>&nbsp;</p>

<p style="text-align:center;">This profile is aimed to provide developers with a series of examples on how the Open Europa Library features are built and configured.&nbsp;Exposing these features,&nbsp;the building of new sites will be easy to get the necessary components to achieve every site's goals.</p>

<p>&nbsp;</p>

<p>&nbsp;</p>


      </div>`

2021-10-01 09:34 UTC, drishu submitted a review, later dismissed

2021-10-01 10:12 UTC, drishu approved these changes

2021-10-01 10:19 UTC, GilNovacomm approved these changes
Approved.

2021-10-01 10:22 UTC, abel-santos-corral approved these changes

2021-10-01 10:23 UTC, merged