OEL-1000: Improve config management.
openeuropa/oe_showcase pull request #49
Opened 2022-01-14 15:51 UTC by drishu

## OEL-1000

### Description

Improve config management.

### Change log

- Added:
  - composer readme
- Changed:
  - Moved block config into feature modules optional folder
  - Updated whitelabel and oe_content

2022-03-07 19:33 UTC, donquixote commented on config/install/system.site.yml
> +uuid: dd934e6d-edf1-45b0-9ba3-e09d166c0875
@drishu This is from the older version of the PR. But why do we even have a uuid here?

2022-03-07 19:33 UTC, donquixote commented on modules/oe_showcase_navigation/config/optional/easy_breadcrumb.settings.yml
> +include_invalid_paths: false
@drishu This is from the older version of the PR.
Was this intended?

2022-03-07 19:34 UTC, donquixote commented on oe_showcase.info.yml
> -    - block.block.whitelabelsearchblock
@drishu These entries should have been removed in OEL-1192, where the blocks were moved to oe_whitelabel.

2022-03-07 19:35 UTC, donquixote commented on modules/oe_showcase_navigation/config/optional/block.block.breadcrumbs.yml
> +visibility: {  }
@drishu All of these blocks are now in oe_whitelabel, since OEL-1192.
Do we still need them here? I suspect not.

2022-03-07 19:37 UTC, donquixote requested changes
@drishu After OEL-1192, where most blocks were moved to oe_whitelabel, it is questionable if the changes in this PR still make sense.

With the rebase, the "move blocks from A to B" became a "Restore blocks in B", because the blocks had previously been removed.

Other changes in this PR need explanation.

2022-03-08 06:51 UTC, drishu commented on config/install/system.site.yml
> +uuid: dd934e6d-edf1-45b0-9ba3-e09d166c0875
It's exported like that by config_devel, Let's remove this file and worst case set the site name in the runner

2022-03-08 06:53 UTC, drishu commented on modules/oe_showcase_navigation/config/optional/easy_breadcrumb.settings.yml
> +include_invalid_paths: false
no, was exported like that, not sure the impact, check the breadcrumb in the submenu pages.

2022-03-08 06:53 UTC, drishu commented on oe_showcase.info.yml
> -    - block.block.whitelabelsearchblock
yes, this is a old PR

2022-03-08 06:54 UTC, drishu commented on modules/oe_showcase_navigation/config/optional/block.block.breadcrumbs.yml
> +visibility: {  }
nope

2022-03-11 07:49 UTC, drishu reviewed
ok for me, pls approve on my behalf @donquixote

2022-03-11 14:26 UTC, donquixote approved these changes, later dismissed

2022-03-17 19:55 UTC, drishu reviewed
Funny to see to how little changes this branch has boiled down to after so many rebases.
Changed look ok to me, please approve on my behalf @donquixote

2022-03-17 19:57 UTC, donquixote approved these changes

2022-03-17 19:59 UTC, donquixote commented
> Funny to see to how little changes this branch has boiled down to after so many rebases. Changed look ok to me, please approve on my behalf @donquixote

Less is more :)

2022-03-18 13:17 UTC, GilNovacomm approved these changes
Tested and all is well. Approved

2022-03-18 13:33 UTC, merged