OEL-254 Create Search server and index for oe_showcase
openeuropa/oe_showcase pull request #5
Opened 2021-08-31 15:05 UTC by GilNovacomm

2021-09-01 13:15 UTC, Maxfire requested changes
Only CS issues I tested the func and checked the code and looks great, thank you Gilmar.

2021-09-01 13:15 UTC, Maxfire commented on modules/oe_showcase_search/tests/src/Functional/ShowcaseSearchAssets.php
> +use Drupal\Core\Url;
Unused use statement

2021-09-01 13:15 UTC, Maxfire commented on modules/oe_showcase_search/tests/src/Functional/ShowcaseSearchAssets.php
> +    'oe_showcase_default_content'
A comma should follow the last multiline array item.

2021-09-01 13:15 UTC, Maxfire commented on modules/oe_showcase_search/tests/src/Functional/ShowcaseSearchAssets.php
> +
Whitespace found at end of lines 32, 44, 60, 81

2021-09-01 13:15 UTC, Maxfire commented on modules/oe_showcase_search/tests/src/Functional/ShowcaseSearchAssets.php
> +  public function testInstallAndDefaultSetupWorking(): void  {
Expected 1 space before opening brace.

2021-09-01 13:15 UTC, Maxfire commented on modules/oe_showcase_search/tests/src/Functional/ShowcaseSearchAssets.php
> +  public function testFields(): void  {
Expected 1 space before opening brace.

2021-09-01 13:15 UTC, Maxfire commented on modules/oe_showcase_search/tests/src/Functional/ShowcaseSearchAssets.php
> +   */
the previous comment is not indented correctly.

2021-09-01 13:15 UTC, Maxfire commented on modules/oe_showcase_search/tests/src/Functional/ShowcaseSearchAssets.php
> +  public function testIndexedContent(): void  {
Expected 1 space before opening brace.

2021-09-01 13:15 UTC, Maxfire commented on modules/oe_showcase_search/tests/src/Functional/ShowcaseSearchAssets.php
> +    // Set index
full stop needed.

2021-09-06 13:19 UTC, drishu requested changes
be sure not to commit conflicts, allways revisit the PR and go through the code, fix anything you see

2021-09-06 13:19 UTC, drishu commented on behat.yml.dist
>          - "%paths.base%/tests/features"
use this one

2021-09-06 13:19 UTC, drishu commented on docker-compose.yml
> +  selenium:
we need selenium only in behat, not now

2021-09-06 13:19 UTC, drishu commented on modules/oe_showcase_search/tests/src/Functional/SearchIndexTest.php
> +<?php
not sure we need this test, we should only add behat tests once we have something facing users, asserting user stories, but we can keep it for now.

2021-09-06 13:19 UTC, drishu commented on modules/oe_showcase_search/tests/src/Functional/ShowcaseSearchAssets.php
> +<?php
remove this one, see SearchIndexTest.php

2021-09-06 13:19 UTC, drishu commented on phpunit.xml.dist
>      <env name="MINK_DRIVER_ARGS_WEBDRIVER" value='["${selenium.browser}", null, "${selenium.host}:${selenium.port}/wd/hub"]'/>
not needed

2021-09-06 13:19 UTC, drishu commented on phpunit.xml.dist
> +      <directory>./modules/**/tests/</directory>
use this one

2021-09-06 13:43 UTC, GilNovacomm commented on modules/oe_showcase_search/tests/src/Functional/ShowcaseSearchAssets.php
> +<?php
Not sure how this test got duplicated on SearchIndex. I'll remove it.

2021-09-06 14:11 UTC, drishu approved these changes

2021-09-06 14:17 UTC, escuriola approved these changes

2021-09-06 14:23 UTC, Maxfire approved these changes
Blind approved. :+1:

2021-09-06 14:24 UTC, merged