OEL-1098: Theme the user profile page
openeuropa/oe_showcase pull request #58
Opened 2022-02-07 20:34 UTC by donquixote

[OEL-1098](https://citnet.tech.ec.europa.eu/CITnet/jira/browse/OEL-1098)

### Description

[Insert description here]

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

2022-02-09 11:22 UTC, drishu requested changes

2022-02-09 11:22 UTC, drishu commented on modules/oe_showcase_user_profile/templates/user--full.html.twig
> +      content.group_professional_information.field_current_position|field_value,
if you agree lets use the field_value filter also in the teaser (now that we have it)

2022-02-09 11:22 UTC, drishu commented on modules/oe_showcase_user_profile/oe_showcase_user_profile.module
> +  // Set an image value object for the header banner pattern.
no need for the comment, lets comment code only if ambiguous

2022-02-09 11:22 UTC, drishu commented on modules/oe_showcase_user_profile/oe_showcase_user_profile.module
> +  $image_element = $variables['elements']['field_profile_image'][0] ?? NULL;
Lets rather bail out early to not execute any additional code if not needed.
instead of checking if certain keys in the render array are present it would be useful and more elegant to use the user object that we have available in the $variables and then make use of the field API
```suggestion
  $user = $variables['user'];

  if ($user->get('field_profile_image')->isEmpty()) {
    return;
  }
```

2022-02-09 11:22 UTC, drishu commented on modules/oe_showcase_user_profile/oe_showcase_user_profile.module
> +  if ($image_element !== NULL) {
no need, we check and bail out if not set earlier

2022-02-09 11:22 UTC, drishu commented on modules/oe_showcase_user_profile/oe_showcase_user_profile.module
> +  $variables['pattern_image'] = NULL;
no need, if there is an image then we have will guarantee a value

2022-02-09 11:22 UTC, drishu commented on modules/oe_showcase_user_profile/oe_showcase_user_profile.module
> +    $image_item = $image_element['#item'] ?? NULL;
```suggestion
    $image_item = $user->get('field_profile_image')->get(0);
```

2022-02-09 11:22 UTC, drishu commented on modules/oe_showcase_user_profile/oe_showcase_user_profile.module
> +    if ($image_item instanceof ImageItem) {
bail out again, this will make the code more readable
```suggestion
    if (!$image_item instanceof ImageItem) {
    return;
  }
```

2022-02-09 11:22 UTC, drishu commented on modules/oe_showcase_user_profile/oe_showcase_user_profile.module
> +}
since the $variables['elements']['field_profile_image'] will not be printed on page we should add the needed cache directly to variables
you can get the file entity
```
  $cacheability = CacheableMetadata::createFromRenderArray($variables['elements']['field_profile_image'][0]);
  $cacheability->applyTo($variables);
```
best after the is empty check I think

2022-02-09 11:22 UTC, drishu commented on composer.json
> +        "openeuropa/oe_whitelabel": "0.1.202202080830"
for now do as in 1.x, we'll rebase the epic at a later point

2022-02-09 11:43 UTC, donquixote commented on modules/oe_showcase_user_profile/oe_showcase_user_profile.module
> +  $image_element = $variables['elements']['field_profile_image'][0] ?? NULL;
ok, in that case we should remove the image in field ui

2022-02-09 22:44 UTC, donquixote commented on modules/oe_showcase_user_profile/oe_showcase_user_profile.module
> +}
But `$variables` is not a render array.

2022-02-10 14:56 UTC, donquixote commented on modules/oe_showcase_user_profile/oe_showcase_user_profile.module
> +}
Actually your code is correct. `$variables` is not a render array, but still this is the supported way of doing it. 

In ThemeManager::render():
```php
      foreach ($info['preprocess functions'] as $preprocessor_function) {
        if (function_exists($preprocessor_function)) {
          $preprocessor_function($variables, $hook, $info);
        }
      }
      // Allow theme preprocess functions to set $variables['#attached'] and
      // $variables['#cache'] and use them like the corresponding element
      // properties on render arrays. In Drupal 8, this is the (only) officially
      // supported method of attaching bubbleable metadata from preprocess
      // functions. Assets attached here should be associated with the template
      // that we are preprocessing variables for.
      $preprocess_bubbleable = [];
      foreach (['#attached', '#cache'] as $key) {
        if (isset($variables[$key])) {
          $preprocess_bubbleable[$key] = $variables[$key];
        }
      }
```

2022-02-22 22:55 UTC, donquixote commented on modules/oe_showcase_user_profile/templates/user--full.html.twig
> +      content.group_professional_information.field_current_position|field_value,
I like the idea, but I think we should do it in a separate issue.
We might have to review more things about the teaser, e.g. the usage of the search variant for the card pattern.

2022-02-24 09:23 UTC, drishu requested changes

2022-02-24 09:23 UTC, drishu commented on modules/oe_showcase_user_profile/templates/user--full.html.twig
> +    attributes: create_attribute().addClass('mb-4'),
Normally this would go into its own block and be printed in the appropriate region right after the main tag, but since we don't invest in that in v1 lets fix the left padding by adding `ps-0`

2022-02-24 09:23 UTC, drishu commented on modules/oe_showcase_user_profile/templates/user--full.html.twig
> +    group_personal_information: 'Personal information',
reusing html blocks should be done via macros not loops. Lets do a macro of the entire section, something like:
```
{% macro description_list_section(group, content, .. %}
  <section class="my-3">
  ..
{% endmacro %}

description_list_section(group1, content,... 
description_list_section(group2, content,... 
```
but name it and define it whatever way you like, the principle is important here

2022-02-24 09:23 UTC, drishu commented on composer.json
> +        "drupal/twig_field_value": "^2.0",
this is also a dependency in whitelabel and will stay that way, we can skip it;
Also, some block config changed in whitelabel and now the tabs are duplicated, we have to adapt, not just merge code in,.. we need to rename the local_tasks block to `block.block.oe_whitelabel_local_tasks.yml` and move it to the `config/optional` folder.

2022-02-24 09:23 UTC, drishu commented on modules/oe_showcase_user_profile/oe_showcase_user_profile.module
> +  }
we have these modules about restricting access to profile data but this is overwriting that, lets add this check
```suggestion
  $field = $user->get('field_profile_image');
  $image_item = $field->get(0);
  if (!$image_item instanceof ImageItem || !$field->access()) {
    // No profile image found.
    return;
  }
```
Also, the anonymous user is denied access by default, so without this check `$variables['elements']['field_profile_image'][0]` will not be set and visiting a users profile with anonymous will throw an error.

2022-02-24 16:49 UTC, donquixote commented on composer.json
> +        "drupal/twig_field_value": "^2.0",
Arguments are being made that if we use a dependency directly, we should make it explicit.
There are code review tools that complain if e.g. we use a class from a package that is only implicitly required.

However, arguments can also be made for the opposite, if we assume the implicit dependency will always be there.

Personally I don't like to "assume", but I am also not always consistent about it.

So I am ok to remove it, if that avoids discussion.

2022-02-24 16:49 UTC, donquixote commented on composer.json
> +        "drupal/twig_field_value": "^2.0",
Arguments are being made that if we use a dependency directly, we should make it explicit.
There are code review tools that complain if e.g. we use a class from a package that is only implicitly required.

However, arguments can also be made for the opposite, if we assume the implicit dependency will always be there.

Personally I don't like to "assume", but I am also not always consistent about it.

So I am ok to remove it, if that avoids discussion.

2022-02-24 16:57 UTC, donquixote commented on modules/oe_showcase_user_profile/oe_showcase_user_profile.module
> +  }
Then could we check `['field_profile_image'][0]` instead of the `$field->access()` check?
If no access is given, will `['field_profile_image'][0]` be empty?

As a note, I very much dislike that we have to deal with these details in site-specific code.
There are much better ways to do this.

2022-02-25 00:13 UTC, donquixote commented on modules/oe_showcase_user_profile/templates/user--full.html.twig
> +    group_personal_information: 'Personal information',
Thanks for the hint! I checked the article about macros, and happily find that there is no risk of polluting a global namespace. So, I will do it.

2022-02-25 00:46 UTC, donquixote commented on modules/oe_showcase_user_profile/templates/user--full.html.twig
> +    attributes: create_attribute().addClass('mb-4'),
This is a bug in bootstrap itself:
https://github.com/twbs/bootstrap/discussions/35807#discussioncomment-2134560
https://github.com/twbs/bootstrap/issues/35282
I posted about this in teams already, in front-end channel.

Fixes already exist in main branch of bootstrap:
https://github.com/twbs/bootstrap/pull/35825 and some prior commits.

We should upgrade bootstrap, or patch it. Then this will go away.
We should also remove the `<div class="row">` around the `{% include ..card.. %}` in `bcl-content-banner.html.twig`. It has no place here.

2022-02-25 01:28 UTC, donquixote commented on modules/oe_showcase_user_profile/templates/user--full.html.twig
> +    attributes: create_attribute().addClass('mb-4'),
New issue: https://citnet.tech.ec.europa.eu/CITnet/jira/browse/OEL-1226
This will fix the problem.
Let's ignore this here.

2022-02-28 16:31 UTC, drishu commented on modules/oe_showcase_user_profile/templates/user--full.html.twig
> +    attributes: create_attribute().addClass('mb-4'),
The way we should do it is either:

1. add a fix and a comment saying "@todo: Remove once OEL-1226 is implemented.", or
2. leave a comment saying "Issue will be fixed by OEL-1226"

In this specific content I'd go with 1.

2022-02-28 20:53 UTC, donquixote commented on modules/oe_showcase_user_profile/templates/user--full.html.twig
> +    attributes: create_attribute().addClass('mb-4'),
Even with the `px-0` (which is more correct than `ps-0`), this still looks wrong on mobile.
This must be fixed in bcl.
But ok, I am adding the solution 2 for now.

2022-02-28 20:57 UTC, donquixote commented on modules/oe_showcase_user_profile/templates/user--full.html.twig
> +    attributes: create_attribute().addClass('mb-4'),
Btw @drishu we can't add comments inside an array, only above it.

2022-03-01 08:34 UTC, drishu requested changes
<img width="682" alt="Screenshot 2022-03-01 at 10 28 15" src="https://user-images.githubusercontent.com/11507647/156132938-b702206d-505a-4aa3-bcfa-72c7655d32a6.png">
we need to rename config/install/block.block.tabs.yml to config/optional/block.block.oe_whitelabel_local_tasks.yml of course using the 'oe_whitelabel_local_tasks' id so we don't have duplicate tabs;

Also we now have the contact forms enabled so
<img width="682" alt="Screenshot 2022-03-01 at 10 28 37" src="https://user-images.githubusercontent.com/11507647/156133663-c820c2d5-7303-407c-aeb1-71f08e28e34a.png">
we need to have the 'contact_default_status' disabled

2022-03-01 08:34 UTC, drishu commented on modules/oe_showcase_user_profile/templates/user--full.html.twig
> +{% spaceless %}
use apply spaceless, see:
https://www.drupal.org/docs/develop/coding-standards/twig-coding-standards#whitespace
since we support 9.2 and above now

2022-03-01 08:54 UTC, drishu commented on modules/oe_showcase_user_profile/config/install/core.entity_view_display.user.user.full.yml
> +      format_type: html_date
lets use the d F Y format, custom for now until OEL-1224 is resolved

2022-03-01 14:28 UTC, donquixote commented
> we need to rename config/install/block.block.tabs.yml to config/optional/block.block.oe_whitelabel_local_tasks.yml of course using the 'oe_whitelabel_local_tasks' id so we don't have duplicate tabs;

is `/optional/` the correct place, or rather `/overrides/`?

> Also we now have the contact forms enabled so we need to have the 'contact_default_status' disabled

2022-03-02 07:12 UTC, drishu requested changes

2022-03-02 07:12 UTC, drishu commented on modules/oe_showcase_user_profile/config/install/core.entity_view_display.user.user.default.yml
> +      date_format: 'd F Y'
why change it here ? this will have no effect on the user profile page, it should have been changed in the file I requested [core.entity_view_display.user.user.full.yml](https://github.com/openeuropa/oe_showcase/pull/58/files#diff-bafdf476599083808722b2695fc2431537893d02488893b4e8a116a7e24c7ae6)

2022-03-02 07:12 UTC, drishu commented on config/install/contact.settings.yml
> +user_default_enabled: false
leave only this one `user_default_enabled: false` we don't need to export the rest of it, leave those to default values

2022-03-02 08:18 UTC, donquixote commented on config/install/contact.settings.yml
> +user_default_enabled: false
I had not considered this as an option. Good idea.

2022-03-02 08:19 UTC, donquixote commented on modules/oe_showcase_user_profile/config/install/core.entity_view_display.user.user.default.yml
> +      date_format: 'd F Y'
Good catch. Sorry.

2022-03-02 08:35 UTC, drishu submitted a review, later dismissed

2022-03-07 18:50 UTC, drishu approved these changes

2022-03-07 20:09 UTC, escuriola approved these changes

2022-03-07 20:56 UTC, merged