OEL-1132: OE Contact Forms integration
openeuropa/oe_showcase pull request #60
Opened 2022-02-10 17:08 UTC by Maxfire

## OPENEUROPA-1132

### Description
Contact form module added, form created, config exported, tests added.

2022-02-11 18:06 UTC, brummbar commented on tests/src/ExistingSite/ContactFormTest.php
> +    $page->fillField('title[0][value]', 'Example contact form page');
Quick note: please use labels and not paths, if possible. Use paths only for difficult nested elements that are repeated through the page (like when there are 3 fields "title").

2022-02-15 08:57 UTC, GilNovacomm commented on modules/oe_showcase_contact_forms/config/install/field.storage.paragraph.field_contact_block.yml
> +field_name: field_contact_block
We've been using machine names for fields without field_ maybe we should also do this here to be consistent with other modules.

2022-02-15 08:57 UTC, GilNovacomm commented on tests/src/ExistingSite/ContactFormTest.php
> +
add statement at the beginning of the test to mark the created entities to be deleted:
 // Mark test content for deletion after the test has finished.
    $this->markEntityTypeForCleanup('node');
    $this->markEntityTypeForCleanup('paragraph');

2022-02-15 09:50 UTC, GilNovacomm submitted a review, later dismissed
Ready for QA.

2022-02-15 09:56 UTC, GilNovacomm reviewed
Ready for QA

2022-02-16 08:05 UTC, drishu commented on modules/oe_showcase_contact_forms/config/install/field.storage.paragraph.field_contact_block.yml
> +field_name: field_contact_block
that rule applies to oe components but its not needed in showcase

2022-02-16 09:38 UTC, drishu requested changes

2022-02-16 09:38 UTC, drishu commented on modules/oe_showcase_contact_forms/oe_showcase_contact_forms.info.yml
> +description: Provides a demo for the contact form.
```suggestion
description: Provides a demo for the contact form feature.
```

2022-02-16 09:38 UTC, drishu commented on modules/oe_showcase_contact_forms/config/install/contact.form.example_contact_form.yml
> +      oe_country_residence: '0'
```suggestion
      oe_country_residence: oe_country_residence
```

2022-02-16 09:38 UTC, drishu commented on modules/oe_showcase_contact_forms/config/install/contact.form.example_contact_form.yml
> +      oe_telephone: '0'
```suggestion
      oe_telephone: oe_telephone
```

2022-02-16 09:38 UTC, drishu commented on tests/src/ExistingSite/ContactFormTest.php
> +<?php
Pls move this file into oe_showcase_contact_forms

2022-02-16 09:38 UTC, drishu commented on tests/src/ExistingSite/ContactFormTest.php
> +class ContactFormTest extends ShowcaseExistingSiteTestBase {
```suggestion
class IntegrationTest extends ShowcaseExistingSiteTestBase {
```

IntegrationTest becasue we are testing the integration of the modules into showcase

2022-02-16 09:38 UTC, drishu commented on tests/src/ExistingSite/ContactFormTest.php
> +    $assert_session->elementTextContains('css', '.alert-content', 'Example contact form page has been created.');
remove this, these texts can change in time, rather go to the page and assert the labels are present

2022-02-16 09:38 UTC, drishu commented on tests/src/ExistingSite/ContactFormTest.php
> +    $page->fillField('Message', 'Example Message text');
in config I asked for the phone and countries to be enabled, so we will fill also those in here (so your user will also need the 'View published SKOS Concept entities' permission)

2022-02-16 09:38 UTC, drishu commented on tests/src/ExistingSite/ContactFormTest.php
> +    // Submit the form.
remove all useless comments, please add comments only where code is harder to understand or ambiguous

2022-02-16 09:38 UTC, drishu commented on tests/src/ExistingSite/ContactFormTest.php
> +    $assert_session->pageTextContains('Alpaca');
assert also the thank you message, not just the submission values;
and also assert the phone and country values here

2022-02-16 09:48 UTC, Maxfire commented on tests/src/ExistingSite/ContactFormTest.php
> +    $assert_session->pageTextContains('Alpaca');
Thank you message is not being asserted as I explained on OEL-1133, I could check the alert-success instead, but that is a change I proposed and is waiting to be merged on OEL-1178, so it needs to keep it as is for now.

2022-02-16 10:45 UTC, drishu commented on tests/src/ExistingSite/ContactFormTest.php
> +    $assert_session->pageTextContains('Alpaca');
"as I explained on OEL-1133" can you paste in a link pls

2022-02-16 10:47 UTC, Maxfire commented on tests/src/ExistingSite/ContactFormTest.php
> +    $assert_session->pageTextContains('Alpaca');
https://citnet.tech.ec.europa.eu/CITnet/jira/browse/OEL-1133 2nd comment from top

2022-02-16 11:07 UTC, drishu requested changes

2022-02-16 11:07 UTC, drishu commented on modules/oe_showcase_contact_forms/tests/src/ExistingSite/IntegrationTest.php
> +    $assert_session->pageTextContains('345345345');
assert belgium
```
$assert_session->pageTextContains('Belgium');
```

2022-02-16 11:17 UTC, drishu approved these changes

2022-02-16 12:15 UTC, GilNovacomm approved these changes

2022-02-16 12:16 UTC, merged