OEL-1158: [BE][oe_showcase] - webtools paragraphs
openeuropa/oe_showcase pull request #64
Opened 2022-02-16 13:48 UTC by abel-santos-corral

## OPENEUROPA-[https://citnet.tech.ec.europa.eu/CITnet/jira/browse/OEL-1158]

### Description

The objective of this task is to enable the paragraphs using webtools, add those paragraphs in the OE Page and then add some examples.

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2022-02-17 08:54 UTC, drishu requested changes

2022-02-17 08:54 UTC, drishu commented on composer.json
> +        "drupal/devel": "^4.1",
if you really need this put it in require dev, I doubt that this is a profile dependency

2022-02-17 08:54 UTC, drishu commented on modules/oe_showcase_page/oe_showcase_page.info.yml
> +  - oe_paragraphs:oe_paragraphs_chart
add all these newly enabled modules also to the oe_showcase.info.yml file

2022-02-17 08:54 UTC, drishu commented on modules/oe_showcase_default_content/content/file/0e8be6ce-cf6b-4e7a-8990-3628cda4459a.yml
> +_meta:
why do you need these files ?

2022-02-21 13:27 UTC, abel-santos-corral commented on composer.json
> +        "drupal/devel": "^4.1",
I have to eliminate it, brute of me. I left it intentionally to do a QA on the reviewer ;-)

2022-02-21 14:35 UTC, abel-santos-corral commented on modules/oe_showcase_default_content/content/file/0e8be6ce-cf6b-4e7a-8990-3628cda4459a.yml
> +_meta:
We need these files for the menu link entries. We generate the files (e.g 0e8be6ce-cf6b-4e7a-8990-3628cda4459a.yml) and then we have the link in the node. So those two elements work together to render later a link in the Main Administration menu. In this case we are introducing a menu link for a new page with webtools paragraphs.

2022-02-22 09:02 UTC, abel-santos-corral commented on modules/oe_showcase_default_content/content/file/0e8be6ce-cf6b-4e7a-8990-3628cda4459a.yml
> +_meta:
In first I thought I needed that file, but later I tryed to deploy without it and it worked fine whithout the file, so I deleted it.

2022-02-23 12:33 UTC, drishu submitted a review, later dismissed

2022-02-23 12:55 UTC, escuriola approved these changes, later dismissed

2022-03-04 13:10 UTC, Maxfire approved these changes, later dismissed

2022-03-04 13:51 UTC, drishu commented on modules/oe_showcase_default_content/content/file/0e8be6ce-cf6b-4e7a-8990-3628cda4459a.yml
> +_meta:
we tested and it actually is needed for the thumbnail in media admin page

2022-03-07 08:19 UTC, drishu approved these changes

2022-03-07 08:20 UTC, escuriola approved these changes

2022-03-07 08:21 UTC, merged