OEL-1133: Dependency updated to whitelabel contact forms submodule.
openeuropa/oe_showcase pull request #66
Opened 2022-02-18 11:55 UTC by Maxfire

## OPENEUROPA-1133

### Description

Info.yml updated to enable a dependency with the oe_whitelabel_contact_forms submodule.

2022-02-18 12:10 UTC, Maxfire commented
Failing because requires https://github.com/openeuropa/oe_whitelabel/pull/73#pullrequestreview-886905313 to be merged 1st so that the module oe_whitelabel_contact_forms exists.

2022-02-18 16:22 UTC, drishu requested changes

2022-02-18 16:22 UTC, drishu commented on composer.json
> +        "php": ">=7.4",
for oe_contact_forms can we use the branch "dev-OEL-..", after it gets merged we can use a dev release till the official one

2022-02-21 07:01 UTC, Maxfire commented on composer.json
> +        "php": ">=7.4",
JFYI I did add master on oe_contact_forms cauyse OEL-1134 was merged.

2022-02-21 07:16 UTC, drishu requested changes

2022-02-21 07:16 UTC, drishu commented on composer.json
> +                "OEL-1133-theming branch": "https://github.com/openeuropa/oe_whitelabel/compare/0.1.202202080830...OEL-1133-theming.diff"
```suggestion
                "contact forms theming": "https://github.com/openeuropa/oe_whitelabel/compare/0.1.202202080830...OEL-1133-theming.patch"
```

2022-02-21 07:38 UTC, Maxfire commented on composer.json
> +                "OEL-1133-theming branch": "https://github.com/openeuropa/oe_whitelabel/compare/0.1.202202080830...OEL-1133-theming.diff"
We have to use .diff temporally to avoid error on drone.

2022-02-21 07:58 UTC, drishu submitted a review, later dismissed

2022-02-21 08:16 UTC, abel-santos-corral submitted a review, later dismissed

2022-02-21 08:39 UTC, abel-santos-corral approved these changes

2022-02-21 08:41 UTC, drishu approved these changes

2022-02-21 08:41 UTC, merged