OEL-1018: [oe_showcase] Integrate the news content type
openeuropa/oe_showcase pull request #67
Opened 2022-02-21 09:45 UTC by Maxfire

## OPENEUROPA-1018

### Description

Integration between oe_whitelabel_news and oe_starter_content_news.

2022-02-21 14:32 UTC, brummbar requested changes

2022-02-21 14:32 UTC, brummbar commented on config/install/filter.format.rich_text.yml
> +    status: false
How come this is false?

2022-02-21 14:32 UTC, brummbar commented on tests/src/ExistingSite/ShowcaseExistingSiteCreateNewsTest.php
> +    // Don't have permissions to create a News.
Who? :)

2022-02-21 14:32 UTC, brummbar commented on tests/src/ExistingSite/ShowcaseExistingSiteCreateNewsTest.php
> +    // Assert we have enough permissions.
This could be removed, doesn't add much value.

2022-02-21 14:32 UTC, brummbar commented on tests/src/ExistingSite/ShowcaseExistingSiteCreateNewsTest.php
> +    $assert_session->pageTextNotContains('This field has been disabled because you do not have sufficient permissions to edit it.');
Here instead you could add that we are checking that editors have access to the text formats.

2022-02-21 17:23 UTC, brummbar approved these changes

2022-02-22 10:43 UTC, drishu approved these changes

2022-02-22 10:44 UTC, merged