Oel 1027
openeuropa/oe_showcase pull request #68
Opened 2022-02-21 11:10 UTC by GilNovacomm

## OPENEUROPA-OEL-1027

### Description

[Insert description here]

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2022-02-21 16:07 UTC, drishu requested changes

2022-02-21 16:07 UTC, drishu commented on config/install/filter.format.rich_text.yml
> +    status: false
looks strange

2022-02-21 16:07 UTC, drishu commented on tests/src/ExistingSite/ShowcaseExistingSiteCreateEventTest.php
> +    // Assert we have enough permissions.
its clear, no need

2022-02-23 15:47 UTC, drishu requested changes

2022-02-23 15:47 UTC, drishu commented on composer.json
> +        "drupal/twig_field_value": "^2.0",
twig_field_value is in the oe_whitelabel's require section, so it would be picked up by composer and you dont need to add it then here, now since below patch against 1026 contains this it wont get picked up by composer so we can leave it like this for now, but once 1026 is merged we'll have to remove this, and the patch and use a dev release 0.1.202202... so on

2022-02-25 18:44 UTC, brummbar approved these changes
Good for now.

2022-02-28 09:01 UTC, abel-santos-corral approved these changes

2022-02-28 09:23 UTC, drishu approved these changes

2022-02-28 09:24 UTC, merged