OEL-256: Add Facets Form and Facets Summary to Showcase Search
openeuropa/oe_showcase pull request #7
Opened 2021-09-02 16:30 UTC by GilNovacomm

## OPENEUROPA-[Insert ticket number here]

### Description

[Insert description here]

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2021-09-03 09:03 UTC, Maxfire approved these changes
checked tests and func and it worked, only needs rebasing and solve conflicts
Greetings.

2021-09-03 09:12 UTC, Maxfire requested changes
rebase it, solve conflicts and push it again, the rest is tested.
Greetings.

2021-09-10 11:36 UTC, cmarcmar submitted a review, later dismissed

2021-09-10 12:23 UTC, drishu requested changes
Lets place the summary and facets form blocks for now, as it makes more sense

2021-09-10 12:23 UTC, drishu commented on modules/oe_showcase_search/config/install/facets.facet.category.yml
> +    show_numbers: false
enable term label by id

2021-09-10 12:23 UTC, drishu commented on modules/oe_showcase_search/oe_showcase_search.info.yml
> +  - facets_form_date_range:facets_form_date_range
above might be dependency of this, check and remove

2021-09-10 12:39 UTC, GilNovacomm commented on modules/oe_showcase_search/oe_showcase_search.info.yml
> +  - facets_form_date_range:facets_form_date_range
Done

2021-09-13 11:50 UTC, drishu approved these changes

2021-09-13 11:54 UTC, Maxfire approved these changes
approved :+1:

2021-09-13 11:58 UTC, merged