OEL-1168 [oe_showcase] Multilingual submodule
openeuropa/oe_showcase pull request #74
Opened 2022-03-01 14:13 UTC by GilNovacomm

## OPENEUROPA-[Insert ticket number here]

### Description

Create oe_showcase_multilingual.
Place and export configuration for the Language switcher block.
Enabled oe_showcase_multilingual on oe_showcase.info.
Create tests.

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2022-03-02 08:39 UTC, abel-santos-corral requested changes
Please, check the next:

- Check why there are other blocks at config/install, as requested at ticket, only multilingual is expected.
- Remove the comments from test, code is self explanatory.

2022-03-02 08:39 UTC, abel-santos-corral commented on modules/oe_showcase_multilingual/oe_showcase_multilingual.info.yml
> +core_version_requirement: ^8.9 || ^9.1
Please, check the minimum version if it's still correct. The OE Bootstrap Theme (used at OE Whitelabel) is fixed to 9.2, so this is valid? Check at https://github.com/openeuropa/oe_bootstrap_theme/blob/1.x/composer.json

2022-03-03 14:39 UTC, GilNovacomm commented on modules/oe_showcase_multilingual/oe_showcase_multilingual.info.yml
> +core_version_requirement: ^8.9 || ^9.1
Francesco agrees we have to bump up the minimal version requirements.

2022-03-04 06:54 UTC, abel-santos-corral submitted a review, later dismissed

2022-03-04 12:27 UTC, drishu requested changes

2022-03-04 12:27 UTC, drishu commented on modules/oe_showcase_multilingual/config/optional/block.block.openeuropa_content_language_switcher.yml
> +weight: -6
<img width="332" alt="Screenshot 2022-03-04 at 14 11 00" src="https://user-images.githubusercontent.com/11507647/156761270-7d1e3ffb-f892-4a7d-bd12-9e4d765a0b3c.png">
should be below title

2022-03-04 12:27 UTC, drishu commented on modules/oe_showcase_multilingual/config/optional/block.block.openeuropa_content_language_switcher.yml
> +      oe_news: oe_news
events is missing

2022-03-04 12:27 UTC, drishu commented on modules/oe_showcase_multilingual/tests/src/ExistingSiteJavascript/MultilingualTest.php
> +   * Create a page node and test language switcher block.
don't say what it does, say what its for, so not "take an orange, take a knife, remove shell" but rather "Test peeling an orange"

2022-03-04 12:27 UTC, drishu commented on modules/oe_showcase_multilingual/tests/src/ExistingSiteJavascript/MultilingualTest.php
> +    $this->getSession()->wait(10000);
```suggestion
    $this->assertSession()->waitForElementVisible('css', '#languageModal');
```
the idea was to wait for the modal to be visible right ?

2022-03-04 12:27 UTC, drishu commented on modules/oe_showcase_multilingual/config/optional/block.block.openeuropa_content_language_switcher.yml
> +  label_display: visible
no need, make it hidden

2022-03-07 17:08 UTC, drishu requested changes

2022-03-07 17:08 UTC, drishu commented on modules/oe_showcase_multilingual/tests/src/ExistingSiteJavascript/MultilingualTest.php
> +    $this->getSession()->wait(10000);
here also waitForElementVisible pls

2022-03-07 17:08 UTC, drishu commented on modules/oe_showcase_multilingual/oe_showcase_multilingual.info.yml
> +  - openeuropa:oe_multilingual
if you agree I would like us to also enable config_translation

2022-03-08 07:42 UTC, drishu approved these changes

2022-03-08 07:47 UTC, Maxfire approved these changes

2022-03-08 07:50 UTC, merged