OEL-255: Create Showcase Search View
openeuropa/oe_showcase pull request #8
Opened 2021-09-07 12:24 UTC by GilNovacomm

## OPENEUROPA-[Insert ticket number here]

### Description

[Insert description here]

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2021-09-07 14:48 UTC, cmarcmar commented on behat.yml.dist
> +    progress: ~
Empty line at the end of the file needs to be added.

2021-09-08 14:31 UTC, cmarcmar approved these changes, later dismissed

2021-09-09 11:23 UTC, drishu requested changes
I'm thinking its a good idea to separate content from functionality so lets move the content folder into oe_showcase_default_content (lets see if we can keep the ids in the info file, if not, move those also)

2021-09-09 11:23 UTC, drishu commented on behat.yml.dist
> +        - "%paths.base%/modules/oe_showcase_search/tests/features"
remove this

2021-09-09 11:23 UTC, drishu commented on behat.yml.dist
>          - Drupal\DrupalExtension\Context\DrupalContext
Lets add some pages (and elements if needed) from the behat test here (see example https://github.com/openeuropa/oe_theme/blob/3.x/behat.yml.dist#L23 )

2021-09-09 11:23 UTC, drishu commented on composer.json
> +        "npm-asset/jquery-ui-touch-punch": "^0.2.3",
why do we need touch punch ?

2021-09-09 11:23 UTC, drishu commented on modules/oe_showcase_search/tests/features/showcase_search_sorting.feature
> +@api
move this into the root, all modules will be enabled so no use in doing this here

2021-09-09 11:23 UTC, drishu commented on modules/oe_showcase_search/tests/features/showcase_search_sorting.feature
> +    When I visit "admin/structure/block/add/views_exposed_filter_block%3Ashowcase_search-showcase_search_page/bartik?region=content"
use page alias, see my comment in behat.yml.dist

2021-09-09 11:23 UTC, drishu commented on modules/oe_showcase_search/tests/features/showcase_search_sorting.feature
> +    Then I should see "Abico Diam Jugis"
add a couple more pages, same for every time you filter

2021-09-09 11:23 UTC, drishu commented on modules/oe_showcase_search/tests/features/showcase_search_sorting.feature
> +    Then I visit "admin/structure/block/manage/exposedformshowcase_searchpage_test/delete"
deleting this is not needed, rather check also the pager

2021-09-09 11:23 UTC, drishu commented on modules/oe_showcase_search/tests/src/Functional/ShowcaseViewTest.php
> +<?php
delete this, the behat one is enough

2021-09-09 11:23 UTC, drishu commented on runner.yml.dist
> +    - "cp -R default_images/. build/sites/default/files/."
lets check if we can set the path for these to be inside the files folder, so we dont have this folder in root

2021-09-09 11:26 UTC, GilNovacomm commented on composer.json
> +        "npm-asset/jquery-ui-touch-punch": "^0.2.3",
Touch punch is a library used by Better Exposed filters, it works without it (I havent tested it on a mobile view):
![image](https://user-images.githubusercontent.com/57403283/132677583-15cfff0b-0500-4c4c-8965-521e7c691bf9.png)

2021-09-09 12:37 UTC, GilNovacomm commented on modules/oe_showcase_search/tests/src/Functional/ShowcaseViewTest.php
> +<?php
Test removed as per meeting with Francesco.

2021-09-09 12:39 UTC, GilNovacomm commented on modules/oe_showcase_search/tests/features/showcase_search_sorting.feature
> +    Then I visit "admin/structure/block/manage/exposedformshowcase_searchpage_test/delete"
Test removed as per meeting with Francesco.

2021-09-09 12:39 UTC, GilNovacomm commented on modules/oe_showcase_search/tests/features/showcase_search_sorting.feature
> +    Then I should see "Abico Diam Jugis"
Test removed as per meeting with Francesco.

2021-09-09 12:39 UTC, GilNovacomm commented on modules/oe_showcase_search/tests/features/showcase_search_sorting.feature
> +    When I visit "admin/structure/block/add/views_exposed_filter_block%3Ashowcase_search-showcase_search_page/bartik?region=content"
Test removed as per meeting with Francesco.

2021-09-09 12:39 UTC, GilNovacomm commented on modules/oe_showcase_search/tests/features/showcase_search_sorting.feature
> +@api
Test removed as per meeting with Francesco.

2021-09-09 12:39 UTC, GilNovacomm commented on behat.yml.dist
>          - Drupal\DrupalExtension\Context\DrupalContext
Path removed

2021-09-09 12:39 UTC, GilNovacomm commented on behat.yml.dist
> +        - "%paths.base%/modules/oe_showcase_search/tests/features"
Path removed.

2021-09-09 14:26 UTC, drishu commented on composer.json
> +        "npm-asset/jquery-ui-touch-punch": "^0.2.3",
Lets remove BEF for now, and figure it out at theming

2021-09-10 09:52 UTC, drishu approved these changes

2021-09-10 09:53 UTC, Maxfire approved these changes
Approved :+1:

2021-09-10 09:54 UTC, merged