OEL-1284: Override whitelabel search form block to enable autocomplete.
openeuropa/oe_showcase pull request #84
Opened 2022-03-08 11:34 UTC by GilNovacomm

## OPENEUROPA-[Insert ticket number here]

### Description

[Insert description here]

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2022-03-08 11:42 UTC, drishu requested changes

2022-03-08 11:42 UTC, drishu commented on config/optional/block.block.oe_whitelabel_search_form.yml
> +    action: '#'
```suggestion
    action: 'search'
```

2022-03-08 11:42 UTC, drishu commented on config/optional/block.block.oe_whitelabel_search_form.yml
> +    name: text
```suggestion
    name: search_api_fulltext
```

2022-03-08 11:42 UTC, drishu commented on config/optional/block.block.oe_whitelabel_search_form.yml
> +    classes: ''
```suggestion
    classes: null
```

2022-03-08 11:42 UTC, drishu commented on config/optional/block.block.oe_whitelabel_search_form.yml
> +    classes: ''
```suggestion
    classes: null
```

2022-03-10 08:18 UTC, drishu approved these changes

2022-03-10 08:47 UTC, Maxfire approved these changes

2022-03-10 09:01 UTC, merged