OEL-486: Add search feature integration test
openeuropa/oe_showcase pull request #87
Opened 2022-03-09 13:22 UTC by drishu

## OEL-486

### Description

Add search feature integration test

2022-03-11 10:17 UTC, escuriola requested changes

2022-03-11 10:17 UTC, escuriola commented on modules/oe_showcase_search/tests/src/ExistingSite/IntegrationTest.php
> +  public function testCreateShowCasePage() {
The name with Create and Page confuses me. Remove the "Create": testShowCasePage.
```suggestion
  public function testShowCasePage() {
```

2022-03-11 11:31 UTC, drishu commented on modules/oe_showcase_search/tests/src/ExistingSite/IntegrationTest.php
> +  public function testCreateShowCasePage() {
we agreed to name it "testSearchFeature"

2022-03-11 11:37 UTC, escuriola approved these changes, later dismissed

2022-03-29 10:11 UTC, escuriola submitted a review, later dismissed

2022-04-11 16:38 UTC, donquixote commented on modules/oe_showcase_search/tests/src/ExistingSite/IntegrationTest.php
> +  public function testCreateShowCasePage() {
Right. The one thing I don't want to see in test method names is "showcase" :)

2022-04-11 16:45 UTC, donquixote commented on modules/oe_showcase_search/tests/src/ExistingSite/IntegrationTest.php
> +    $assert->fieldExists('Category 5');
We can be more precise:

```suggestion
    $assert->fieldExists('Category 1', $offcanvas);
    $assert->fieldExists('Category 2', $offcanvas);
    $assert->fieldExists('Category 3', $offcanvas);
    $assert->fieldExists('Category 4', $offcanvas);
    $assert->fieldExists('Category 5', $offcanvas);
```

2022-04-11 17:11 UTC, donquixote commented on modules/oe_showcase_search/tests/src/ExistingSite/IntegrationTest.php
> +    $assert->fieldExists('Sort by');
We could try to be more precise here, but I did not see a good selector in the parent elements. So..

2022-04-12 12:16 UTC, donquixote commented on modules/oe_showcase_search/tests/src/ExistingSite/IntegrationTest.php
> +    $this->assertSame('Obruo', $items[4]->getText());
Not a criticism, just a thought:
It would be nice if we could compare arrays of texts.
Unfortunately it is ugly and more verbose than the single assertions, if we don't have a reusable mechanism for it:
```php
    $this->assertSame(
      [
        'Imputo Neo Sagaciter',
        'Distineo',
        'Quae Vulputate',
        'Abico Diam Jugis',
        'Obruo',
      ],
      array_map(
        static fn(NodeElement $item): string => $item->getText(),
        $view->findAll('css', '.card-title')));
```
We can create a method `assertElementsTexts()`, then it would look like this:

```php
    $this->assertElementsTexts([
      'Imputo Neo Sagaciter',
      'Distineo',
      'Quae Vulputate',
      'Abico Diam Jugis',
      'Obruo',
    ], $items);
```
```php
  /**
   * Asserts text contents for multiple elements at once.
   *
   * @param string[] $expected
   *   Expected element texts.
   * @param \Behat\Mink\Element\NodeElement[] $elements
   *   Elements to compare.
   */
  protected function assertElementsTexts(array $expected, array $elements): void {
    $this->assertSame($expected, array_map(
      static fn(NodeElement $item): string => $item->getText(),
      $elements,
    ));
  }
```
I think this version _does_ look more readable.

2022-04-13 07:54 UTC, drishu commented on modules/oe_showcase_search/tests/src/ExistingSite/IntegrationTest.php
> +    $this->assertSame('Obruo', $items[4]->getText());
love it

2022-04-19 22:24 UTC, donquixote submitted a review, later dismissed

2022-04-28 10:52 UTC, donquixote approved these changes

2022-04-29 07:55 UTC, escuriola approved these changes

2022-04-29 10:37 UTC, merged