OEL-1292: Fields and post update changes to make oe_content compatible.
openeuropa/oe_showcase pull request #89
Opened 2022-03-11 13:46 UTC by Maxfire

Fields modified, tests adapted as well and post update to remove and update fields.

2022-03-16 13:45 UTC, drishu requested changes

2022-03-16 13:45 UTC, drishu commented on composer.json
> +        "openeuropa/oe_whitelabel": "dev-OEL-1291"
for the module it's ok, but the convention for the themes is to use a diff, you can change ..1.x for ..OEL-1291.diff, if it was discussed like this with @brummbar then I dont mind, but I'd keep to our normal way of working

2022-03-16 14:35 UTC, drishu approved these changes, later dismissed

2022-03-16 14:35 UTC, drishu commented on modules/oe_showcase_page/config/install/core.entity_view_display.node.oe_showcase_page.teaser.yml
> +  oe_content_content_owner: true
these will be resolved by OEL-1301

2022-03-16 17:06 UTC, brummbar requested changes
All looks good but let's re-export the fields and roles configuration, as they are not up to date.

2022-03-17 12:12 UTC, brummbar approved these changes, later dismissed

2022-03-17 13:08 UTC, abel-santos-corral approved these changes

2022-03-17 13:09 UTC, drishu approved these changes

2022-03-17 13:09 UTC, merged

2022-03-17 13:10 UTC, brummbar requested changes
N

2022-03-17 13:10 UTC, brummbar commented on composer.json
> +                "1.x latest": "https://github.com/openeuropa/oe_whitelabel/compare/1.0.0-alpha5..1.x.diff"
Let's swap with branch as mac patching is buggy when deleting code.