OEL-461: Add OE_Whitelabel theme and theme search block facets.
openeuropa/oe_showcase pull request #9
Opened 2021-09-14 14:45 UTC by GilNovacomm

## OPENEUROPA-[Insert ticket number here]

OEL-461: Add OE_Whitelabel theme and theme search block facets.

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2021-09-15 09:24 UTC, drishu requested changes

2021-09-15 09:24 UTC, drishu commented on docker-compose.yml
> +  node:
in future, the realeases will contain the needed assets (as in bootstrap theme now), so, till then, move this to your docker-compose.override.yml

2021-09-15 09:24 UTC, drishu commented on modules/oe_showcase_search/config/install/facets.facet.published_on.yml
> +_core:
fi you use config devel then stuff like this does not get added and you wont need to mange it manually anymore, just drush cdi oe_showcase_search after making changes in the db

2021-09-15 14:16 UTC, drishu approved these changes

2021-09-15 16:58 UTC, drishu approved these changes, later dismissed

2021-09-15 17:02 UTC, timpevi approved these changes, later dismissed

2021-09-16 05:47 UTC, drishu approved these changes

2021-09-16 08:09 UTC, timpevi approved these changes

2021-09-16 08:09 UTC, merged