OEL-1167: Theme the multilingual content block
openeuropa/oe_showcase pull request #91
Opened 2022-03-17 11:59 UTC by GilNovacomm

## OEL-1167

### Description

Require oe_whitelabel_multilingual as a dependency for oe_showcase_navigation.

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2022-03-17 19:12 UTC, drishu requested changes

2022-03-17 19:12 UTC, drishu commented on config/optional/block.block.openeuropa_content_language_switcher.yml
>    id: oe_multilingual_content_language_switcher
lets remove this file, I think the defaults from whitelabel will be enough

2022-03-17 19:12 UTC, drishu commented on modules/oe_showcase_navigation/oe_showcase_navigation.info.yml
> +  - oe_whitelabel:oe_whitelabel_multilingual
dont we have oe_showcase_multilingual for this ? and add also to oe_showcase.info.yml

2022-03-19 22:58 UTC, donquixote reviewed
Seems good to me. I left one comment, not sure if we should change this.

2022-03-19 22:58 UTC, donquixote commented on oe_showcase.info.yml
> +  - oe_whitelabel_multilingual
Do we need this, if we already depend on oe_showcase_multilingual?
Or can/should we rely on indirect dependency?

2022-03-21 11:49 UTC, drishu commented on oe_showcase.info.yml
> +  - oe_whitelabel_multilingual
It's the same model as in ewcms, see https://github.com/openeuropa/oe_theme/blob/3.x/modules/oe_theme_content_event/oe_theme_content_event.info.yml and 
https://github.com/ec-europa/ewcms/blob/develop/ewcms.info.yml#L111

but yes, I should take time to ask as to the reason why this practice is being done

2022-03-21 12:29 UTC, donquixote commented on oe_showcase.info.yml
> +  - oe_whitelabel_multilingual
For module info files and composer.json, if we want to do it right, we should distinguish explicit dependencies vs implicit dependencies.
For a profile, we could ask this question in various ways, but in the end i don't care enough :)
Let's keep it as it is in this PR.

2022-03-21 12:30 UTC, donquixote approved these changes, later dismissed

2022-03-21 17:52 UTC, drishu approved these changes

2022-03-21 18:08 UTC, donquixote approved these changes

2022-03-21 18:13 UTC, merged