OEL-1322: PHP 8.0 upgrade for oe_showcase.
openeuropa/oe_showcase pull request #92
Opened 2022-03-18 14:36 UTC by escuriola

## OPENEUROPA-[Insert ticket number here]

### Description

[Insert description here]

### Change log

- Added:
- Changed: PHP version to 8.0
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2022-03-21 16:29 UTC, brummbar requested changes
I made a mistake in the ticket. oe_showcase should work on one php version only. Let's put 8.0.

2022-03-21 16:53 UTC, brummbar submitted a review, later dismissed

2022-03-22 10:47 UTC, donquixote commented
Interesting that we don't need to add token and prophecy-phpunit.
But no need to speculate why - tests are green, we are good.

2022-03-22 10:47 UTC, donquixote approved these changes

2022-03-22 10:55 UTC, brummbar approved these changes

2022-03-22 11:19 UTC, merged