OEL-759: Add facts and figure paragraph to the example page.
openeuropa/oe_showcase pull request #94
Opened 2022-03-22 11:04 UTC by escuriola

## OPENEUROPA-[Insert ticket number here]

### Description

[Insert description here]

### Change log

- Added: 
- Changed: Add Facts and Figures paragraph in the example page.
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2022-03-22 11:18 UTC, drishu approved these changes, later dismissed

2022-03-22 11:18 UTC, abel-santos-corral submitted a review, later dismissed

2022-03-28 07:54 UTC, abel-santos-corral requested changes
Please, activate the paragraphs Facts and figures (not Fact sub-paragraph) at Body of Demo Page content type.

Many thanks in advance.

2022-03-28 13:50 UTC, abel-santos-corral approved these changes, later dismissed

2022-04-05 13:23 UTC, drishu requested changes
the paragraphs will move so this needs to be re-tested after, I also dont extra lines in the test as the ticket requested

2022-04-05 13:23 UTC, drishu commented on modules/oe_showcase_page/oe_showcase_page.info.yml
> +  - openeuropa:oe_bootstrap_theme_paragraphs
attention, this will soon be oe_whitelabel_paragraphs

2022-04-06 11:49 UTC, drishu approved these changes, later dismissed

2022-04-06 13:06 UTC, abel-santos-corral commented on modules/oe_showcase_page/oe_showcase_page.info.yml
> +  - openeuropa:oe_bootstrap_theme_paragraphs
We had this change by rebasing 1.x.

2022-04-06 14:46 UTC, brummbar approved these changes

2022-04-06 14:52 UTC, Maxfire approved these changes
Blind approval as requested by @brummbar

2022-04-06 14:54 UTC, merged