OEL-1369: Hide paragraph Contextual navigation and item paragraphs
openeuropa/oe_showcase pull request #96
Opened 2022-03-28 15:55 UTC by abel-santos-corral

## OPENEUROPA-[OEL-1369](https://citnet.tech.ec.europa.eu/CITnet/jira/browse/OEL-1369)

### Description

At Page content type disable Accordion list item and List item.
At Content row paragraph type, disable Contextual navigation sub-paragraph.

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2022-03-29 12:56 UTC, drishu submitted a review, later dismissed

2022-04-01 19:49 UTC, brummbar requested changes
I re-enabled the paragraphs, simulating a future update, and the tests were still green. This means that we don't have test coverage for what we did in this ticket.

2022-04-05 17:15 UTC, brummbar approved these changes

2022-04-05 17:17 UTC, drishu approved these changes

2022-04-05 17:23 UTC, abel-santos-corral reviewed
I reviewed the changed added by Francesco and agreed with  them

2022-04-05 17:23 UTC, merged