OEL-1300: Integrate the extended project content type.
openeuropa/oe_showcase pull request #97
Opened 2022-04-01 11:22 UTC by Maxfire

2022-04-01 14:26 UTC, drishu reviewed
OK for now, two considerations:
1. the fields might need to be revisited after merge of the whitelabel PR
2. for future I will create a ticket to move these content type related config into a suibmodule, but not now because it should be done right and include news and event

2022-04-01 14:59 UTC, drishu requested changes
One thing I realized we should add is alias pattern like here https://github.com/openeuropa/oe_showcase/blob/1.x/modules/oe_showcase_page/config/install/pathauto.pattern.page_url_alias_pattern.yml

2022-04-04 07:03 UTC, drishu requested changes
1) Please double check that anonymous users can see project nodes and skos.
2) Please add a test called **ProjectTest.php** in  tests/src/ExistingSite that:

- asserts users without permission dont have access to the project creation page
- set up assets programatically (images or whatever u need to have ready)
- with a user that has permissions create a project **through the UI**
- save, go to the node url and assert the values are present

2022-04-04 11:44 UTC, donquixote requested changes

2022-04-04 11:44 UTC, donquixote commented on tests/src/ExistingSite/ProjectTest.php
> +    $page->fillField('Contribution to the budget', '19.9');
The selectors are ambiguous.

2022-04-04 11:44 UTC, donquixote commented on tests/src/ExistingSite/ProjectTest.php
> +    $page->fillField('Contribution to the budget', '19.9');
Also, are we not forgetting fields?
Lead contributors?

2022-04-04 11:44 UTC, donquixote commented on tests/src/ExistingSite/ProjectTest.php
> +    $assert_session->pageTextContains('Name');
We should use some kind of selector.
Not sure what's the best solution here.

2022-04-04 11:44 UTC, donquixote commented on tests/src/ExistingSite/ProjectTest.php
> +    $assert_session->pageTextContains('Name');
Also, "Name" alone is not very useful to test.
We want to verify that "Name" appears left of "Developer participant name", and all that within the participants section.

2022-04-04 12:32 UTC, drishu submitted a review, later dismissed
enough for now

2022-04-04 12:54 UTC, abel-santos-corral approved these changes, later dismissed

2022-04-06 18:01 UTC, drishu approved these changes
ok for now

2022-04-06 20:02 UTC, donquixote approved these changes

2022-04-06 20:11 UTC, merged