OEL-1159: Align templates with modified search variant pattern
openeuropa/oe_showcase pull request #98
Opened 2022-04-05 18:35 UTC by donquixote

2022-04-06 08:53 UTC, escuriola requested changes

2022-04-06 08:53 UTC, escuriola commented on modules/oe_showcase_search/templates/node--search-result.html.twig
>    <a class="text-underline-hover" href="{{ url }}">{{ label }}</a>
Not related, but text-underline-hover must be changed to standalone class

2022-04-06 08:53 UTC, escuriola commented on modules/oe_showcase_search/templates/node--search-result.html.twig
> +    label: _item,
badges are links, and links need to add the class standalone, if not, you'll see an underline: 
![image](https://user-images.githubusercontent.com/6751237/161934454-3eaef345-12a2-49e8-9ca9-c271bdede5bf.png)

2022-04-06 11:04 UTC, donquixote commented on modules/oe_showcase_search/templates/node--search-result.html.twig
> +    label: _item,
In the old version there were no links for these category items.
I am pushing a fix that reproduces that old behavior without links.

2022-04-06 11:05 UTC, donquixote commented on modules/oe_showcase_search/templates/node--search-result.html.twig
>    <a class="text-underline-hover" href="{{ url }}">{{ label }}</a>
Fixed.

2022-04-06 11:22 UTC, escuriola submitted a review, later dismissed

2022-04-07 06:45 UTC, drishu approved these changes

2022-04-07 07:21 UTC, escuriola approved these changes

2022-04-07 07:24 UTC, merged